### ISSUE TITLE
Загрузка структуры конфигурации

### ISSUE THREAD

**Issue by capitoshko** [BlizD/Tasks#100]
Сейчас загрузка структуры возможно только при наличии изменений в хранилище. Я предлагаю добавить загрузку всей структуры конфигурации, независимо от того были изменения или нет. Подобное есть в ERP, автоматизированной проверке конфигурации.

**Comment by BlizD** [comment]
В случае загрузки всех изменений первый коммит содержит всю конфигурацию

**Comment by capitoshko** [comment]
Я пробовал у меня загрузка не происходит. Попробую ещё раз

**Comment by capitoshko** [comment]
Полная загрузку истории хранилища не присходит. Само создания хранилища с усеми метаданными не загружается пока для этого не создать специальную задачу.

Загрузка изменений на платформе 8.3.12 работает только в альтернативном режиме. А он загружает только когда хранилище размещено локально. Для сервера хранилища использовать exe компоненту не получаеться. 

Предлагаю зарегистрировать как ошибку

**Comment by BlizD** [comment]
>Загрузка изменений на платформе 8.3.12 работает только в альтернативном режиме

Да, это так. Поэтому альтернативный вариант и появился, так как типовая выгрузка с помощью платформы 1с не срабатывает.

>А он загружает только когда хранилище размещено локально. Для сервера хранилища использовать exe компоненту не получаеться.

Под локально имеется ввиду в текущей локальной сети, верно?
А проблема когда хранилище размещено вне локальной сети, да?

**Comment by capitoshko** [comment]
А почему не срабатывает? Изменился формат отчета типового с хранилища? Или у вас не было времени разбираться?

**Comment by BlizD** [comment]
>А почему не срабатывает? Изменился формат отчета типового с хранилища? Или у вас не было времени разбираться?

Можно почитать вот тут в комментариях: https://infostart.ru/public/645512/
>До этого и обходился штатными средствами, но для конфигураций в которых указан режим совместимости 8.2.13 и ниже 
отчет выдается в другом формате он мне не подходил в нем нет нужных мне сведений: 
нет версии, нет пользователя, нет даты версии, нет признака (добавлен, изменен, удален) или не было комментария. 
>+ сведений группируются по объектам метаданных. 
Возможно, что то делал не так, но не получилось сформировать нужный мне отчет.

**Comment by BlizD** [comment]
Похоже протупил, речь о платформе 8.3.12? А глаз мой прочитал 8.2.13

**Comment by capitoshko** [comment]
У нас режим совместимости 8.3.9
 Но почитаю обязательно

**Comment by capitoshko** [comment]
Да, 8.3.12

**Comment by BlizD** [comment]
Если хранилище размещено локально и режим совместимости выше 8.2.13, тогда должна работать и альтернативная и типовая загрузка.

На 8.3.12 еще не пробовал загружать, у нас 8.3.10

**Comment by BlizD** [comment]
@capitoshko 
Попробуйте открыть "Загрузку изменений из хранилища" там есть кнопка "Получить команду"
![image](https://user-images.githubusercontent.com/10989306/46023071-7dc9eb80-c0ec-11e8-888a-67697483cbaa.png)
![image](https://user-images.githubusercontent.com/10989306/46023105-94704280-c0ec-11e8-9883-a9afaa5369f4.png)

Попробуйте ее выполнить в CMD файле, если появится файл "StorageHistory..."- то все ок

**Comment by capitoshko** [comment]
У меня происходит считывание, выводиться отчёт но почему-то запись измененных объектов не происходит . Можете скинуть хотя бы примерно того какой у вас таб.документ формируется?

**Comment by capitoshko** [comment]
Спасибо. Сегодня попробую.

**Comment by capitoshko** [comment]
у меня конфигурация есть с режимом совместимости 8.2.13. По-этому типовая загрузка истории не работает...

Думаю вопрос можно закрывать.
