### ISSUE TITLE
Сортировка в канбан доске по порядку

### ISSUE THREAD

**Issue by capitoshko** [BlizD/Tasks#101]
Можно ли в канбан доске сортировать статусы задач по указанному порядку в соответствующих элементах справочника?

**Comment by BlizD** [comment]
>При изменении порядка в статусах задач новый порядок применяться только при закрытии формы и повторном открытии.

Да, сейчас необходимо закрыть форму канбан доски и открыть ее. 
Генерация формы происходит или при открытии формы или когда изменена видимость колонок в настройках канбан доски:

![image](https://user-images.githubusercontent.com/10989306/45955689-3de60400-c019-11e8-8884-2c5c150b6d0b.png)

**Comment by capitoshko** [comment]
Думаю можно закрывать. Не критично
