### ISSUE TITLE
Ошибка в механизмах отправки писем

### ISSUE THREAD

**Issue by capitoshko** [BlizD/Tasks#102]
Тестирую механизмы оповещения почтой. Нашел кусок кода, который считаю ошибкой

Основная конфигурация ОбщийМодуль.узОбщийМодульСервер.Модуль(20, 40) : ДокОбъект.ОтправительПредставление = "1с: Управление задачами";

Я себе настроил системную учетную запись с другий наименованием. Если в метод не передаеться учетная запись, тогда это наименование остаеться.

**Comment by BlizD** [comment]
Да ошибка

**Comment by capitoshko** [comment]
#102 Исправил
