### ISSUE TITLE
Ошибка при отправке письма заказчику

### ISSUE THREAD

**Issue by capitoshko** [BlizD/Tasks#103]
Если я хочу прямо из задачи отправить письмо заказчику, то при открытии фомы gисьма представление контакта отображаеться верно. Но если я хочу открsть список контактов, то в форме адпресной книги для контакта не указан электронный адрес, хотя в карточке контрагентов адрес указан.

Нашел проблему в програмном коде - когда подключали систему взаимодействия не прописали справочник контрагентов в методе: 

Документ.ЭлектронноеПисьмоИсходящее:
Процедура  ЗаполнитьКонтакты
строка 57
Взаимодействия.ДозаполнитьПоляКонтактов(НоваяСтрока.Контакт, НоваяСтрока.Представление,
			НоваяСтрока.Адрес, Перечисления.ТипыКонтактнойИнформации.АдресЭлектроннойПочты);

Далее переход 
Адреса = ВзаимодействияВызовСервера.ПолучитьНаименованиеИАдресаЭлектроннойПочтыКонтакта(Контакт);

Далее переход

МассивОписанияТиповКонтактов = ВзаимодействияКлиентСервер.ПолучитьМассивОписанияВозможныхКонтактов();

**Comment by BlizD** [comment]
Да, ошибка

**Comment by capitoshko** [comment]
верно ли я понимаю, ч то на каждую задачу я беру сф-ку текущего релиза, вношу изменения и прикрепляю к задаче? и так каждій раз. верно? а ві потом єто все обїедените.

**Comment by BlizD** [comment]
В случае работы через CF - да, верно. Единственное, давайте отправлю, Вам на почту последний CF из ветки Develope. 
Напишите, свою почту.

**Comment by BlizD** [comment]
сейчас в облако выложу, скину ссылку.

**Comment by capitoshko** [comment]
Может к хранилища Dev подключете?

**Comment by BlizD** [comment]
честно говоря думал, этот проект делать через механизмы гитхаб, то есть без использования хранилища.

Плюс еще такой вопрос, по идее нужен же IP адрес статический, плюс опубликовать это все.
Поправьте если не прав.

Вообщем пока без хранилища на Dev, если будет большой поток, тогда еще раз подумаем на эту тему.

**Comment by BlizD** [comment]
Ссылка на CF
https://cloud.mail.ru/public/KpaF/kgmjiMFe9

**Comment by BlizD** [comment]
Плюс, Вы, можете сами получить последний CF из ветки Develope.
Для этого необходимо сделать Fork - далее загрузить конфигурацию из Файлов. Как по шагам в инструкции.

**Comment by capitoshko** [comment]
По поводу хранилища вы правы.

Я могу и на git попробовать. Как скажете. Установлю платформу 8.3.9 и сделаю все как в инструкции.

**Comment by BlizD** [comment]
@capitoshko - давайте пока через CF, чтобы у Вас интерес не пропал)
Потом если еще будет желание. тогда сделаете через Git.

**Comment by capitoshko** [comment]
У меня интересует не пропадет. Я наоборот готов немного времени и уделить социальной работе на благо человечества 2с

**Comment by capitoshko** [comment]
я с Украины, мейл ру у нас заблокирован. попробую забрать с Fork

**Comment by BlizD** [comment]
Выложу на другое, скину позже

**Comment by BlizD** [comment]
https://dropmefiles.com/03gSq

**Comment by capitoshko** [comment]
Ошибку исправил, комментарий //+ #103

**Comment by capitoshko** [comment]
https://dropmefiles.com/OpwyE

сдесь все мои исправления

**Comment by BlizD** [comment]
Залил в Dev ветку.
Файл CF после изменений 
https://dropmefiles.com/ychXf

**Comment by capitoshko** [comment]
У меня глобальная проблема - установить себе синхронизацию с GitHub не могу, так как установка .net Framework 4.7.1 в нашей компании заблокировано :( по вашей инструкции подключиться не могу. Есть ли альтернативный вариант работать с Git?

**Comment by BlizD** [comment]
>Есть ли альтернативный вариант работать с Git?

Да, есть еще:
* Git Extensions;
* GitHub (приложение от GitHub);
* Tortoise Git;
* из cmd командами gita=)

Есть еще, можно спросить у @nixel2007

**Comment by capitoshko** [comment]
Я тут думал над сервис детском. 

У меня вопрос - например пользователь написал, что хочет новый отчёт. Система зарегистрировала запрос и отписалась автоматически. Потом я зашёл в систему и через систему взаимодействия попросил согласовать техническое задание на разработку. Как при последующем письме пользователя определяешься к какой задаче прикрепить письмо? Читаеться знак диеза в теме письма? Если так, то может стоит как-то спрятать этот признак, чтобы пользователь не мог его удалить и в результате чтобы не зарегистрировался ещё один запрос, хотя на самом деле это письмо согласование?
