### ISSUE TITLE
Учет использованого времени на задачу

### ISSUE THREAD

**Issue by capitoshko** [BlizD/Tasks#104]
Создаю отдельную задачу для учета времени, потраченого на выполнение задачи

**Comment by capitoshko** [comment]
Предлагаю сделать изменения следующим образом:

1. Добавить документ "Учет времени по задачах"
Реквизиты:
- Исполнитель
- Задача
- Дата начала
- Дата окончания
- Время
- Комментарий

2. Документ должен делать проведения по регистру накопления "Фактическое время выполнения работ".
Измерения регистра:
- Исполнитель
- Задача
Ресурсы:
- Время
Реквизиты:
- Дата начала
- Дата окончания

3. В Справочнике "Задачи" имя в табличной части "Фактические часы" изменить на "Удалить фактические часы".

В форме задачи над динамическим список добавить кнопку добавления рабочего времени. При нажатии на кнопку должен 

открываться новый документ "Учет времени по задачах". создавать такой документ может только текущий исполнитель задачи или 

пользователь с административными правами. Если нужно провести документ по учету времени "задним" числом, то нужно указать дата начала и дату окончания в период, когда пользователь был исполнителем задачи

В форме документа добавить динамический список "Фактические часы". Заполнять его с данных регистра накопления с отбором по 

задачи.

4. Добавить обработку по переходу на новый механизм учета рабочего времени. При обновлении рабочей системы ее нужно 

запустить и перенести все данные с табличной части "Удалить фактические часы", создать документы "Учет времени по задачах" 

текущей датой, очистить табличную часть "УдалитьФактическиеЧасы". сделать все в трансакции. чтобы не потерять часть данных

**Comment by BlizD** [comment]
@capitoshko перенес в файл ворда, там расписал метаданные название и т.п.
Прошу вопросы и ответы, комментарии прям там же в файле отмечай (через механизм примечаний).
[#104 учет использования времени.docx](https://github.com/BlizD/Tasks/files/2433343/104.docx)

Пока кодировать не надо, сначала в файле обо всем договоримся.

**Comment by capitoshko** [comment]
Мне так же выкладываться вордовский файл?

**Comment by 7OH** [comment]
а может на гугле тогда док выложить, у меня качать предлагает.
По документу согласен - красиво будет - не будем каждый раз задачу перезаписывать. А вот с динамическим списком регистра не понятно - просто показываем все текущие значения по задаче ? Тогда вроде ОК.
4. Функция при обновлении тоже может перенести текущие значения.

**Comment by 7OH** [comment]
Можно я пока тут спрошу ? А зачем табличная часть в документе ? Если я как исполнитель ввожу время - то обычно это вот на сейчас - сколько я отработал - одна запись . Или открывать и править один док на спринт ?

**Comment by 7OH** [comment]
Ну и показывать мы в таблице в той же задаче что будем - доки ? Тогда будет не информативно, так как табличную часть видно не будет.

**Comment by capitoshko** [comment]
1. Согласено, но в файле есть эти замечания, качните и увиидите.
2. По задаче - будем показывать отбор по регистру - динамический список.

**Comment by 7OH** [comment]
Да, да. Смотрел. Просто в файле не совсем удобно - лучше всё же в облаке держать.
В целом и в табличной части неплохо будет скопом указывать время.
То есть добавляем документ, а показываем уже результат из регистра - отлично.

**Comment by BlizD** [comment]
Добавил комментарии и ответы. 
Искать можно по //2
[#104 учет использования времени_031018.docx](https://github.com/BlizD/Tasks/files/2441598/104._031018.docx)

**Comment by 7OH** [comment]
В обработке по переносу времени из задачи в документы просьба маленькая , если получится, учесть возможное наличие реквизита спринт в табличной части.

**Comment by capitoshko** [comment]
ДОбавил комментарии

Искать можно по //3
[104._041018.docx](https://github.com/BlizD/Tasks/files/2446892/104._041018.docx)

**Comment by 7OH** [comment]
[104._041018_04.docx](https://github.com/BlizD/Tasks/files/2447867/104._041018_04.docx)
//4 моё

**Comment by capitoshko** [comment]
Семен, а где у вас ТЧ?
"у меня УЖЕ есть спринт в табличной части. Если получится (с проверкой наличия в метаданных) заполнять и реквизитом СПРИНТ из этой вот ТЧ ?" - можете объяснить?

**Comment by 7OH** [comment]
Я кидал cf-ку свою с доработкой (в 86 тикете), где в ТЧ задач добавлен спринт, и он же учтен в отчете.

**Comment by BlizD** [comment]
[#104 учет использования времени_051018.docx](https://github.com/BlizD/Tasks/files/2449094/104._051018.docx)
Добавил комментарии искать по //5
Можно кодировать.

**Comment by 7OH** [comment]
По своей просьбе - принято, буду готовиться.
Кто будет кодить?

**Comment by capitoshko** [comment]
Да, я буду.

**Comment by BlizD** [comment]
https://drive.google.com/open?id=1a6XEPEKATejjbWXkFAgP6o9OCwbjE6zT

**Comment by capitoshko** [comment]
Предлагаю Исполнителя также перенести в шапку документа.

**Comment by 7OH** [comment]
Да. Другой исполнитель создаст свой документ. Вряд-ли кто-то будет за кого-то вводить работы.

**Comment by BlizD** [comment]
>Предлагаю Исполнителя также перенести в шапку документа.

Пока этого не надо делать, пусть Исполнитель остается в табличной части. 
В самой задаче ввод факта будет реализован максимально удобно, скорее всего это будет отдельная форма для ввода факта.

**Comment by capitoshko** [comment]
Отжельрую флтму не делаю. Я никак не пойму зачес исполнителя в табличной части. Можете объяснить детальнее?

**Comment by capitoshko** [comment]
Если нужна отдельная форма ввода факта, упрощённая, то может вообще от нее отказаться? Сделать одну простую форму, в которой исполнитель введёт время по задаче и все? Перенести обработкой существующие записи не будет проблемой?

**Comment by BlizD** [comment]
>Если нужна отдельная форма ввода факта, упрощённая, то может вообще от нее отказаться? Сделать одну простую форму, в которой исполнитель введёт время по задаче и все? 

@capitoshko пока не думайте об этом. Делаем как договорились.

**Comment by capitoshko** [comment]
Я себе представляю сценарий работы в котором время вводиться для задачи и исполнителя, то тогда табличная часть нужна только для ввода различных дат выполнения и для разных спринтов .

**Comment by capitoshko** [comment]
Есть ещё вопрос: дату начала и окончание не добавлять как реквизиты регистра?

Если нет, то какое значение писать в период записи регистра?

**Comment by BlizD** [comment]
@capitoshko - когда есть ТЧ, то это более универсально. Если допустим потребуется загружать из  Excel или из другой системы факт, то в этом случае удобнее создавать 1 документ на 1 задачу.

**Comment by BlizD** [comment]
>Есть ещё вопрос: дату начала и окончание не добавлять как реквизиты регистра?
Если нет, то какое значение писать в период записи регистра?

Нет, не добавлять. В регистр в период писать дату документа.

**Comment by capitoshko** [comment]
А для переноса первичного как переносить? В табличной части мы добавляем реквизиты дату начала и дату окончания. Мы если захотим будем с тс выбирать данные?

**Comment by BlizD** [comment]
В табличной части задачи тоже есть такие реквизиты: дата начала и дата окончания. Возможно не понял вопроса.

**Comment by capitoshko** [comment]
В табличной части есть реквизиты Дата Начала, ДатаОкончания. Есть еще реквизит документа "Дата". Если вводить данные 08.10 за период 01.10 - 03.10, то как мне кажеться, верно писать все 3 даты, чтобы потом использовать в отчетности.

**Comment by capitoshko** [comment]
> > Есть ещё вопрос: дату начала и окончание не добавлять как реквизиты регистра?
> > Если нет, то какое значение писать в период записи регистра?
> 
> Нет, не добавлять. В регистр в период писать дату документа.

Как тогда переносить данные при обновлении? Переносить текущей датой? не будет интересно когда и за какой период будут вносить исполнители данные?

**Comment by 7OH** [comment]
Будет конечно. Датой начала работы из тч, например.

**Comment by capitoshko** [comment]
> Будет конечно. Датой начала работы из тч, например.

Для начального заполнения так сделаю. Далее - только датой документа. Согласны?

**Comment by 7OH** [comment]
+

**Comment by capitoshko** [comment]
Прошу не плевать в меня, сделал как умел

https://drive.google.com/file/d/17pFT6an0AwokZ-uitG_WbMYejmxeL0f6/view?usp=sharing

**Comment by capitoshko** [comment]
исправленный вариант

https://drive.google.com/file/d/1KAkX-Ku8CntOSXZNQx3FfPxvoxH0HxUw/view?usp=sharing

**Comment by 7OH** [comment]
У вас нормально обновилось ? Загрузил конфигурацию (с заменой - не объединял). При запуске ошибка обновления. Документ не может записать.
![default](https://user-images.githubusercontent.com/3063507/46665328-2cc9f500-cbcc-11e8-9c10-25320175dec7.png)

**Comment by capitoshko** [comment]
Сейчас проверю

**Comment by capitoshko** [comment]
Воссоздал, буду править

**Comment by 7OH** [comment]
Ещё возможно бага - при нажатии провести в форме ввода (её бы немного примарафетить) - данные записываются куда-то и.... и при повторном нажатии провести - ещё раз добавляются. Это если так задумывалось - немного сбивает с толку. Я три раза нажал провести, пока понял. Итого 3 раза запись времени.

**Comment by capitoshko** [comment]
Да, есть ошибка. Форму примарафетить - даже не знаю как удобно.

**Comment by 7OH** [comment]
никак не найду - тут можно личные сообщения писать ?

**Comment by capitoshko** [comment]
Мой Скайп capitoshko

**Comment by 7OH** [comment]
И ещё - дата начала и окончания - таки дата+время ?

**Comment by capitoshko** [comment]
https://drive.google.com/file/d/1veTkw1QaUBw6Jcl_MMH5uKci8I3GgiSm/view?usp=sharing

**Comment by 7OH** [comment]
С вашего позволения - +косметика, +время в реквизиты дат и фикс по 120 задаче.
https://drive.google.com/open?id=1GCyoD7DXZkVcWaD-Xf1nPTmCFTITUtgc

**Comment by capitoshko** [comment]
Если Антон  не против, то будем ваши последние изменения юзать

**Comment by BlizD** [comment]
![image](https://user-images.githubusercontent.com/10989306/46732684-da093f80-cc96-11e8-9666-b4e6dc51a51a.png)
