### ISSUE TITLE
Ошибка при использовании протокола IMAP

### ISSUE THREAD

**Issue by capitoshko** [BlizD/Tasks#105]
Если в настройках системной учетной записи выбрать протокол IMAP и при этом указать в настройках получения почты только "Оставлять копии писем на сервере" = Истина и "Исключать дубли писем" = Ложь, тогда регламентное задание получения рассылки потчы заходить в безконечный цикл. Проверено на тестовой базе. Прошу зарегистрировать как Баг.

**Comment by BlizD** [comment]
@capitoshko 
Правильно понимаю, что настраивал по инструкции:
https://github.com/BlizD/Tasks/wiki/Настройка-получения-почты-по-протоколу-IMAP

**Comment by capitoshko** [comment]
Да. Выбрал папку ,Invox но не установил исключать дубли

**Comment by capitoshko** [comment]
Попробую сегодня раскопать почему ошибка возникает.

Развернул у себя репозиторий, попробую залить изменения с платформы 8.3.12

**Comment by capitoshko** [comment]
В отладке просмотрел - проблема заключаеться в том, что если снять флаг "Исключать дубли", то механизм работает как при подключении POP3, но прочитать письма при инициализированном подключении через IMAP не может. Как простой вариант - проставлять этот признак по умолчанию, как это сделано для папки входящих писем. Исключение дублей очень хорошая штука.

**Comment by 79vlad** [comment]
Добрый вечер.
Сравнил крайний релиз с моей доработкой по IMAP: в релиз попал алгоритм немного видоизмененный.
Ссылка на пост с cf где этот механизм добавлялся: https://github.com/BlizD/Tasks/issues/84#issuecomment-398467164

**Comment by capitoshko** [comment]
Может тогда ваш механизм добавить полностью сейчас? Было бы хорошо исправить такую неточность

**Comment by capitoshko** [comment]
Да, просмотрел исходную конфигурацию. Есть отличия именно в куске кода, в котором идет бесконечный цикл. Но Если для протокола IMAP не проставить признак "Исключать дубли писем, то и в вашем варианте, я так предполагаю, будет бесконечній цикл также, поскольку для этого протокола нужно указать конкретную папку для чтения писем. То-есть инициализация самого подключения осуществляеться по-другому нежели в POP3, авото чтение есои не указано, что надо исключать дубли, программно делаеться как в POP3. Єто и приводит к ошибке.

П.С. не знаю понятно ли я объяснил...

**Comment by 79vlad** [comment]
Пересмотрел код (в релизе и в исходной конфе), не могу найти когда будет бесконечній цикл. Текущий почтовій ящик устанавливается сразу на всю сессию по вічитке почті: `Почта.ТекущийПочтовыйЯщик = ?(ЗначениеЗаполнено(пПапкаВходящейПочтыIMAP),пПапкаВходящейПочтыIMAP,"INBOX");`
Дальше только разделение по протоколу: IMAP - вічитіваем заголовки (они содержат ИдентификаторСообщения (вот это и является неизменным идентификатором (он "длинный")) и Идентификатор (это идентификатор, который неизменен пределах одной сессии (он "короткий")). Если на почтовике работает почтовый антивирус - то идентификатор - может поменяться при следующем подключении (именно этот эффект я и получил у себя).
Могу предположить, что почтовый ящик содержит большое кол-во сообщений, которое долго вычитывается и получаем эффект зависания. Передаваемые параметры отбора (вычитывать только не прочтенные письма) не всегда отрабатываются почтовиком (зависит от настроек почтового сервера и кривизны рук админа почтовика), для этого я и оставил проверку с регистром на то, что письмо уже было ранее получено.
Можно попробовать поиграться с передаваемыми параметрами, например, отобрать письма с датой >= "ДатаНачалаРаботыСПочтой".   (Эту дату, например, можно добавить как константу или как реквизит настройки учетной записи)

**Comment by capitoshko** [comment]
В отладке попробовал

1. Вариант без включенной настройки "Исключать дубли"

![_3](https://user-images.githubusercontent.com/25638430/46477958-91640900-c7f4-11e8-8831-23c2a5786920.png)
![_2](https://user-images.githubusercontent.com/25638430/46477959-91640900-c7f4-11e8-86b5-dfa385e290f9.png)
![default](https://user-images.githubusercontent.com/25638430/46477960-91640900-c7f4-11e8-817c-7afc2c883d63.png)

2. Вариант свключенной настройки "Исключать дубли"

![_2](https://user-images.githubusercontent.com/25638430/46478126-f28bdc80-c7f4-11e8-8601-968b35efe22d.png)
![default](https://user-images.githubusercontent.com/25638430/46478128-f3247300-c7f4-11e8-8361-fd8cf68c127b.png)

**Comment by 79vlad** [comment]
Добрый день.
Спасибо за скрины - нашел причину бага. Немного переделал алгоритмы [1Cv8_IMAP_v_1_0_4_010.7z](https://drive.google.com/open?id=1_F7Q4W89XkaGpFpieUrXm03DiPLXm_BV)

Воспроизвести баг - не могу, т.к. нет возможности подключить свою тестовую к почтовику. Внесенные изменения, на работу с включенной "исключать дубли" не повлияло - эта конфигурация у меня сейчас работает как "prod"

**Comment by 79vlad** [comment]
Добрый день.
Проверил моё исправление на "prod" - при протоколе IMAP и снятым флагом "Исключать дубли" - все работает, почта получается и не зависает. Баг исправлен -  можно использовать для релиза.

**Comment by BlizD** [comment]
Спасибо, обязательно залью.

**Comment by capitoshko** [comment]
Я пповерю еще у себе, для надежности

**Comment by BlizD** [comment]
Залил изменения.

**Comment by capitoshko** [comment]
А можно сф-ник с полседними изменениями?

**Comment by BlizD** [comment]
https://drive.google.com/open?id=1SpoxyN4QuD_VgO-R7FLxkavtffzvcta6
