### ISSUE TITLE
Ошибка в Канбан доске

### ISSUE THREAD

**Issue by capitoshko** [BlizD/Tasks#106]
Если перейти на страницу "Настройки" и нажать кнопку "Установить стандартный настройки", то талица "Видимость колонок" заполняеться еще раз теме же значениями. При обновлениее доски возникает ошибка.

**Comment by capitoshko** [comment]
Попробовал закомитить с GitHub desktop. Как вы писали об индексайции файлов, то я не нашел такой фишки в этом приложении. Конфигурацию фалов выгружал с платформы 1С:Предприятие 8.3 (8.3.12.1595). Насколько я понял  высможете отменить мою заливку.

**Comment by capitoshko** [comment]
напишите все ли верно прошло, мне интересно смогу ли я работать по вашей схеме кодинга

**Comment by capitoshko** [comment]
По ходу залились все изменения. Можете отменить мой коммит?

**Comment by capitoshko** [comment]
Попробовал еще раз залить, С помощью Git Extention. Он сразу показал различия между версиями без повторной индексации. Мне перезалить с использованием 8.3.9 ?

**Comment by capitoshko** [comment]
Или может перейдем на платформу 8.3.12? и будем с использованием ее заливать изменения?

П.С Прям проситься новая подредакция :)

**Comment by BlizD** [comment]
Пока менять режим платформы не буду. Поэтому надо использовать для выгрузки/загрузки платформу 8.3.9.1850

**Comment by capitoshko** [comment]
Вы мой комит отменили? Я попробую с 8.3.9 залить ещё раз?

**Comment by BlizD** [comment]
Ничего не отменял, напрямую в мой репозиторий коммитить не получится.

**Comment by capitoshko** [comment]
Вроде добавил, не знаю верно ли, но вот что-то появилось

**Comment by capitoshko** [comment]
Если я следал все верно, то далее могу работать через репозиторий и файлов на внешнем диске не надо.

**Comment by BlizD** [comment]
Теперь необходимо еще сделать Pull request из Вашего форка "capitoshko/Tasks" из вашей ветки Develope  в мой репозиторий в ветку Features.

![image](https://user-images.githubusercontent.com/10989306/46405354-b1220100-c710-11e8-9525-776abf3c2418.png)

Давайте пока все таки будем через CF делать, так быстрее.

**Comment by capitoshko** [comment]
Блин, я наверное тупой. А как єто сделать?

**Comment by BlizD** [comment]
iabBliz - скайп

**Comment by BlizD** [comment]
@capitoshko - это подправил.
Можешь не исправлять.
![image](https://user-images.githubusercontent.com/10989306/46521917-c5d5d480-c889-11e8-87ae-a51d79e4054e.png)
