### ISSUE TITLE
Добавить настройки 3 строки карточки задачи 

### ISSUE THREAD

**Issue by BlizD** [BlizD/Tasks#108]
1. Добавить справочник узНастройкиКарточкиЗадачи с такими реквизитами
* ПоказыватьПризнакЕстьФайлыПоЗадаче (Булево);
* ПоказыватьПризнакЕстьПисьмаПоЗадаче (Булево);
* ПоказыватьЗаказчика (Булево);
* ПоказыватьВыполнениеЧеклистаДробь (Булево);
* ПоказыватьВыполнениеЧеклистаПроцент (Булево);

2. Добавить реквизит НастройкаКарточкиЗадачи в канбан доску. 
Если не заполнена настройка, тогда пусть показывается по умолчанию: ЕстьФайлыПоЗадаче, ЕстьПисьмаПоЗадаче, Заказчик.

**Comment by capitoshko** [comment]
Теперь понял - вы хотите ссылку на справочник добавить на доску. А может обойтись без справочника?
Может просто параметры в канбан доску добавить? Как выбор отдельных настроек. Без справочника. Тогда в общем хранилище настроек все сохраниться.

Вот я представил как я буду работать с этим справочником. У меня там будет в будущем скажем 10 параметров. Мне нужно создать настройку с чек-листом в процентах. Я ее назову Настройка 1, потом зайдете вы, назвете Настройка 2. Как мне понять что в настройке без открытия формы и просмотра?
А в канбан доске я могу легко их указать и менять очень явно прямо на доске, и это будут только мои настройки.

**Comment by BlizD** [comment]
В целом согласен, просто на закладке настройки в канбан доске, уже и так много настроек. 
Поэтому думал вынести данные настройки в другое место, чтобы снизить давление на глаза тому кто первый раз заходит в настройки.

Пока вопрос открыт подумаем еще.

**Comment by capitoshko** [comment]
Может сделать отдельную закладку для настроек? мі с ребятами смотрели доску - она крутая, всем очень понравилась. Давайте попробуем подумать

**Comment by BlizD** [comment]
@capitoshko тогда лучше сделать свернутую группу настройки карточки задачи, без добавления справочника.

**Comment by capitoshko** [comment]
Может добавить хранилище общих настроек прям в базе данных? Мне как-то спокойнее, когда на уровне БД храняться данные.

**Comment by BlizD** [comment]
В этом случае, я за справочник отдельный=)

**Comment by capitoshko** [comment]
:) я уже почти сделал без справочника

**Comment by capitoshko** [comment]
https://drive.google.com/file/d/1jjF84KsF0oXoLFtBPve2NOcbF5dowbom/view?usp=sharing

Готово, вроде работает.
