### ISSUE TITLE
Цветовое оформление задач.

### ISSUE THREAD

**Issue by BUDIVAL** [BlizD/Tasks#11]
Добавить возможность указывать цвет для таких элементов как "Важность", "Спринт", "Основная задача" и "Задача" и отображение на доске в соответствии с указанным цветом.

**Comment by BlizD** [comment]
На первом этапе стоит сделать настраиваемый цвет только для "Важности".

**Comment by BlizD** [comment]
Оформление в канбан доске должно добавляться программно.

**Comment by BUDIVAL** [comment]
Я уже реализовал, но возился с фича файлом (так толком и не получилось). Залью вместе с учетом времени. А пока у сторожил поспрашиваю про фича файл.

**Comment by BlizD** [comment]
> Я уже реализовал, но возился с фича файлом (так толком и не получилось). Залью вместе с учетом времени. А пока у сторожил поспрашиваю про фича файл.

@BUDIVAL Дима, только отдельными Pull requstами делай, не надо сразу две задачи за один пул реквест делать.

**Comment by BUDIVAL** [comment]
Хорошо

**Comment by BlizD** [comment]
При создании новой задачи выдает ошибку

{Справочник.узЗадачи.Форма.ФормаЭлемента.Форма(61)}: Поле объекта не обнаружено (ЦветЗадачи)
	ТекущийОбъект.ЦветЗадачи = Новый ХранилищеЗначения(ЦветЗадачиНаФорме);

**Comment by BlizD** [comment]
обновись еще раз с ветки Develope
И сделай еще раз пулреквест.
