### ISSUE TITLE
Ошибка при загрузке истории хранилища

### ISSUE THREAD

**Issue by VVi3ard** [BlizD/Tasks#111]
Если не заполнена константа: "Список пользователей кому отправлять системные уведомления"
и в загружаемой истории есть не заполненный комментарий система падает с ошибкой 
"{Обработка.узЗагрузкаИзмененийИзХранилища.МодульОбъекта(572)}: Итератор для значения не определен".

**Comment by VVi3ard** [comment]
Дубликат

**Comment by capitoshko** [comment]
Ошибку исправили. В следующем релизе надеюсь заедит
