### ISSUE TITLE
Обновление БСП конфигурации

### ISSUE THREAD

**Issue by capitoshko** [BlizD/Tasks#117]
Предлагаю начать обновление к последнему релизу БСП.

Какое ваше мнени - сразу на последний релиз или поэтапно?

**Comment by BlizD** [comment]
Пока бы не спешил. 
Есть объективные причины почему необходимо обновиться на новый релиз БСП?

**Comment by capitoshko** [comment]
Кроме мобільного клиента нет

**Comment by capitoshko** [comment]
А можете сможем забрать новые подсистемы?

**Comment by pallid** [comment]
> Есть объективные причины почему необходимо обновиться на новый релиз БСП?

Ну первое что приходит это поднятие режима совместимости платформы, для использования например хотяб системы взаимодействия

**Comment by BlizD** [comment]
Тестов к сожалению нет

**Comment by capitoshko** [comment]
Поэтапный переход это сравнимо с обновлением типовых конфигураций. В чем вы видите сложность

**Comment by capitoshko** [comment]
По системе взаимодействия я так и не могу понять чем она поможет в реальной работе?

**Comment by pallid** [comment]
@capitoshko 

> В чем вы видите сложность

в том что это как раз и не сравнимо...если я не прав, прошу переубедить

тем более, точно не помню, но кажется tasks в dev варианте не имеет в наличии БСП как конфигурации поставщика

@BlizD или я не прав на счет конфигурации поставщика?

**Comment by capitoshko** [comment]
Сравнивал с 2.4.4. есть различия, но структурных особенно нет

**Comment by pallid** [comment]
@capitoshko 

> чем она поможет в реальной работе?

ну маркетинговая ее часть как раз очень здорово ложится в tasks как мне кажется, т.е переписка по предмету, т.е так сказать фоновая переписка.

Как у нас сейчас происходит...Есть задача, по задаче появились вопросы, а для ответа постановщику задачи надо по хорошему пообщаться еще дополнительно с вопрощающим...

и вот чтоб много шума не делать в задаче они это обсуждение ведут вне задачи (скайп, чаты и т.д)

а свой нормально сформированный ответ постановщик уже пишет в задаче

**Comment by BlizD** [comment]
@pallid 
>@BlizD или я не прав на счет конфигурации поставщика?

В дев ветке конфа поставщика сохранена. То есть стоит на поддержке бсп.

**Comment by pallid** [comment]
@capitoshko 

> Сравнивал с 2.4.4

может тогда сразу на 3.0

**Comment by pallid** [comment]
@BlizD @capitoshko может тогда экспериментальную ветку под это?

у меня вроде как  созрели начать пробовать tasks, можем и на такой сразу посидеть

**Comment by pallid** [comment]
@capitoshko заколобарируемся под эту задачу? ))))

**Comment by pallid** [comment]
@capitoshko на 3.0.1 надо переходить с 2.4.6

**Comment by capitoshko** [comment]
Сжечь ещё 2.3.2 используется

**Comment by pallid** [comment]
Ну в общем были правы, придется поднимать версию поэтапно, с 2.3.2

**Comment by pallid** [comment]
А может тогда взять и сравнить с БСП 2.3.2 посмотреть разницу, и ее перенести в новую 3.0.1?

**Comment by pallid** [comment]
а 2.3.2.76 вообще нет в релизах, видимо он был отозван

**Comment by capitoshko** [comment]
Я бы для начала перешел на последний релиз 2.3.2.205 а потом уже сравнивал с 3.0.1

**Comment by BlizD** [comment]
Все таки, я бы пока БСП не обновлял, работы много, а пользы мало.
Пока плюсы от нового БСП нового это:
* смена режима совместимости в конфигурации (это поможет мобильному клиенту и расширениям);
* система взаимодействия.

Предлагаю подождать еще мотивов.

**Comment by 7OH** [comment]
Вчера посидел подумал - надо перейти минимум на БСП с поддержкой 8.3.8, так как в ней были запреты на серверные действия при завершении работы.
Да и типовые вроде уже меньше 8.3.8 не просят.
Дальше уже кто захочет - поднимет выше без проблем как сейчас.
Расширения - это хороший приятный кусочек )).

**Comment by capitoshko** [comment]
Для нормальной разработки ограничений доступа, нужно обновлять версию БСП, В текущей есть ошибки программные по настройке доступов.Их все исправлять значительнее дольше нежели обновиться к более стабильной версии

**Comment by 7OH** [comment]
Не обнаружил в поддержке конфы оригинальной БСП (2.3.2.76). На релизах 1С только 2.3.2.195 есть минимальный. У кого есть - киньте плиз.

**Comment by capitoshko** [comment]
Та же ситуация

**Comment by capitoshko** [comment]
Может сначала переделаем историю статусов?

Я бы тогда мог делать внешние отчёты

Я могу сегодня начать обновление, если не получается.

**Comment by 7OH** [comment]
> его можно получить через "Конфигурация - Поддержка - Настройка поддержки - Сохранить в файл"

В моей конфе - есть выбор - понимаю где это.
![default](https://user-images.githubusercontent.com/3063507/46996323-effa8280-d124-11e8-8710-422983947666.png)

но в конфе нету выбора
![default](https://user-images.githubusercontent.com/3063507/46996539-bc6c2800-d125-11e8-8d7b-52e6c1d3e3d9.png)

Спасибо за ссылку на БСП - попробую у себя сегодня на новую подсадить и глянуть как работать будет.

**Comment by BlizD** [comment]
Конфа поставщика БСП есть только в дев ветке.

**Comment by capitoshko** [comment]
Вроде дымный тест


Вроде дымный тест




[Отчет об автоматическом тестировании.xlsx](https://github.com/BlizD/Tasks/files/2493529/default.xlsx)

**Comment by BlizD** [comment]
А что если не обновлять БСП, а просто подымать уровень совместимости выше? Может так будет проще и безопаснее?

**Comment by BlizD** [comment]
Что касается:
>Для нормальной разработки ограничений доступа, нужно обновлять версию БСП, В текущей есть ошибки программные по настройке доступов.Их все исправлять значительнее дольше нежели обновиться к более стабильной версии

Мне кажется не надо использовать RLS от БСП. Скину как можно реализовать ограничение доступа. На конференции Инфостарт, от 1с-Коннект был доклад, они рассказали как они RLS реализовали там.

**Comment by 7OH** [comment]
@BlizD платформа 8.3.8 запрещает северные вызовы при завершении работы. В этом вся соль. Наша укр УТ никак этот рубеж не пройдет.

**Comment by capitoshko** [comment]
Украинская УТ 3.1 имеется ввиду?

**Comment by 7OH** [comment]
@capitoshko да, она самая. В целом как и тут - работать можно. Но при закрытии программы тонна ошибок. Оно и формы прыгают на сервер и перед завершением работы тоже. Если эти вещи исправить - то можно и тут остаться.

**Comment by capitoshko** [comment]
Да. Режим совместимости 8.3.4 для Уточнения 3.1

**Comment by 7OH** [comment]
@capitoshko ,именно, хотя требуют 8.3.8 зачем-то. В формах по идее не сложно убрать ненужные вызовы при завершении, а вот в модуле приложения - я в нашей Ут месяц костыли рисовал, чтобы не вылазило нигде.  Пробовал на выходных на новую бсп накатить УЗ - брал полную бсп. Объекты вижу, но отчет не взлетел - надо модули бсп менять, где надо. Видел вызовы в нашей конфе, где в модуле бсп доработка, хотя её надо бы в пепеопределяемый поместить, чтобы легче обновлять. В общем мне кажется, всё таки на новую бсп легче будет накатить (особенно тому, кто конфигурацию на ноги ставил),чем менять и осмысливать кучу вызовов.

**Comment by 7OH** [comment]
А вот ещё один повод всё таки немного "подрасти" в версии.
Хотел в расширении обработку под себя исправить.
"Добавление дочерних объектов этого типа к заимствованным в расширениях недопустимо в режиме совместимости 8.3.8 и ниже"

**Comment by capitoshko** [comment]
Я ждать не могу, с последнего релиза буду переводить на послудний релиз БСП 2.3.2, чтобі седлать ограничения на уровне РЛС. Когда сделаю - выложу, может автор конфигурации примет изменения.

**Comment by 7OH** [comment]
Круто, у меня спрашивали - можно ли сделать ограничение, чтобы в одной базе работать группами, типа чтобы люди из одной группы не видели задач и работ от людей из другой группы. Предприятие одно, а направлений разработки несколько и вот видеть всё в одной куче не интересно.

**Comment by capitoshko** [comment]
> Круто, у меня спрашивали - можно ли сделать ограничение, чтобы в одной базе работать группами, типа чтобы люди из одной группы не видели задач и работ от людей из другой группы. Предприятие одно, а направлений разработки несколько и вот видеть всё в одной куче не интересно.

У нас та же проблема. Есть заказчики по нескольких направлениях, они дожлны работать только со своими задачами, но задачи других долдны видет и не менять. Идея - добавить РЛС на справочник "УзЗадачи".

**Comment by 7OH** [comment]
А к чему привязка будет ? Ну - кто и что может видеть. Отдельная ТЧ\РС ? Это же и ответственных (наблюдателей) и разработчиков тоже надо поделить.

**Comment by capitoshko** [comment]
Мы хотим запустить работу в русле изменений по user story. ограничения будут только за группы задач. По идеи, если у вас есть специализация, то и разработчиков нужно поделить.

**Comment by 7OH** [comment]
мой скайп Simpson.Gomer - я вам писал, можем там тесты обсуждать более детально , если нужно.

**Comment by BlizD** [comment]
@capitoshko по поводу RLS может быть есть смысл сделать разграничения доступа без привязки к БСП? В этом случае не будет проблем в будущем при обновлении с БСП.

**Comment by capitoshko** [comment]
Можно и так.  У меня есть наработки в упаковці. Можем взять их

**Comment by BlizD** [comment]
Еще такой момент не понял, только сейчас увидел что в поставке к БСП нет файлов обновлений cfu. 
Может не так ищу. То есть только файл CF.

**Comment by capitoshko** [comment]
Да. Есть только сф файл

**Comment by Renzes** [comment]
> В моей конфе - есть выбор - понимаю где это. ![default](https://user-images.githubusercontent.com/3063507/46996323-effa8280-d124-11e8-8710-422983947666.png)
> 
 А у вас БСП 2.4.2.64 осталась? С портала ее убрали, а она мне нужна. Мне досталась самописка, в которой стоит она без поддержки

**Comment by BlizD** [comment]
@Renzes вопрос не понял напишите в чат вопрос https://t.me/tasksch
