### ISSUE TITLE
Обработчик подписки УстановитьПометкуУдаленияПрисоединенныхФайлов

### ISSUE THREAD

**Issue by 7OH** [BlizD/Tasks#120]
В подписке УстановитьПометкуУдаленияПрисоединенныхФайлов не указано событие - скорее всего ПриЗаписи.
Обнаружил при попытке смены режима совместимости.

**Comment by BlizD** [comment]
@7OH не увидел изменений в твоем CF, если скинешь файл, то залью.

**Comment by 7OH** [comment]
https://drive.google.com/open?id=1Atxxrhddp8n9MdvzoBAOfD0uO-tN3-1m

**Comment by BlizD** [comment]
Там событие "Перед записью" должно быть, проблема была в том, что ОпределяемыйТип.ВладелецПрисоединенныхФайловОбъект указан был ДокументОбъект.узВыпускРелиза убрал его. 
Событие перед записью отобразилось.
