### ISSUE TITLE
Перенос данных таблично части "ИсторияСтатусов" в отдельный регистр сведений

### ISSUE THREAD

**Issue by capitoshko** [BlizD/Tasks#122]
Для дальнейшей настройки отчетов необходимо точно знать когда меняеться статус задачи. без периодического регистра сведений не обойтись

**Comment by capitoshko** [comment]
1. Добавить периодический независимый регистр сведений "узСтатусыЗадач".
Измерения регистра:
- Задача - СправочникСсылка.узЗадачи
Ресурсы:
- Статус - СправочникСсылка.узСтатусыЗадачи

2. В справочнике узЗадачи:
- переименовать "ИсторияСтатусов" на "Удалить_ИсторияСтатусов"
- перенести записи табличной части в регистр сведений при обновлении на новый релиз. Период записи - Дата начала табличной части
- убрать видимость табличной части и вывести динамический список с отбором по задаче в форме элемента справочника
- запись в регистр сделать по тем самим событиям, по которым в текущем релизе добавляются  записи в табличнуй часть "ИсторияСтатусов".

**Comment by BlizD** [comment]
Чуть позже посмотрю. На первый взгляд еще не хватает Исполнителя.

**Comment by capitoshko** [comment]
Согласен. Исполнитель был бы очень уместен. По такому признаку можно отслеживать всех кто был причастен к работе над задачей. Можно так же понимать сколько времени задача ждала выполнения а сколько была в статусе wip

**Comment by BlizD** [comment]
@capitoshko 
>Хотел бы историю статусов начать делать - предлагаю согласовать описание, что я начал делать?

Вроде мы говорили последний раз, что жду от тебя файл в том же формате, что делали для факта по задачам.
Давай все таки также в Word файле, не на гугл докс.

**Comment by capitoshko** [comment]
Да. Сори. Сегодня подготовлю и выложу

**Comment by capitoshko** [comment]
[117.docx](https://github.com/BlizD/Tasks/files/2527176/117.docx)

Добавил

**Comment by BlizD** [comment]
Ок, посмотрю.

**Comment by BlizD** [comment]
Поправил ТЗ 
[#117_Антон_031118.docx](https://github.com/BlizD/Tasks/files/2544687/117_._031118.docx)

**Comment by capitoshko** [comment]
я не понимаю. у меня была идея перенести истории в отбельные регистры сведений, чтобы данные регистров использовать для отборов данных для метрик. для этого нужно перенести данные с ТЧ ИсторияСтатусов и ТЧ История, и уже с них брать данные для анализа

**Comment by BlizD** [comment]
@capitoshko для отчетов насколько, помню была проблема, что нельзя за указанную дату получить статусы задач. Вот как раз в этой задаче это необходимо реализовать. Пока уход от использования ТЧ. История и ТЧ ИсторияСтатусов не нужен.

**Comment by capitoshko** [comment]
Да. Но я думал, что заодно перенести все данные в периодические регистры сведений

**Comment by capitoshko** [comment]
Исполнителя и спринт добавил для простоты связки в регистрах. Отборы по исполнителях также нужны для статистики работы конкретного пользователя. Скажем, нужно просмотреть какие задачи в каких исполнителей в каких статусах находятся

**Comment by capitoshko** [comment]
Хотя согласен. Пока непонятны выгоды от такого переноса до конца. Как промежуточный вариант можно сделать так.

Сегодня приступлю к работам по переносу только истории статусов. 

Можно последний dev сф - ник выложить?

**Comment by BlizD** [comment]
@capitoshko пока надо дождаться обновления БСП до версии 2.3.2.205.

**Comment by capitoshko** [comment]
Ок, тогда жду обновления

**Comment by BlizD** [comment]
@capitoshko можешь не ждать обновление БСП затягивается. Поэтому делай на текущем CF. Первая попытка залить БСП не очень удалась, надо немного иначе делать.

**Comment by capitoshko** [comment]
https://drive.google.com/file/d/1Qnvlc9OXYFKMFlOiUnp5KSRjMHO-e3-G/view?usp=sharing

Прошу добавить в дев ветку

И еще - для отчетов добавил общие формы с БСП

**Comment by BlizD** [comment]
@capitoshko 
Игорь, 
Ок, как перенесу напишу. Спасибо.

**Comment by BlizD** [comment]
@capitoshko перенес изменения.
Обновил файл CF и промежуточные релизы.
