### ISSUE TITLE
При выгрузке файлов задач, выгружать файлы в разрезе конфигураций

### ISSUE THREAD

**Issue by 79vlad** [BlizD/Tasks#124]
Задачи ведутся в разрезе нескольких конфигураций и для каждой конфигурации указана своя папка выгрузки файлов.
При формировании файлов задач, в каждой папке формируются идентичные файлы (они не формируются в разрезе задач).

**Comment by BlizD** [comment]
Тут вопрос спорный например у нас есть задачи которые затрагивают разные конфигурации

**Comment by 79vlad** [comment]
Так как по текущей структуре задачи - одна задача не должна быть связана с несколькими конфигурациями (потому, что это реквизит объекта). Привязка к разным конфигурациям возможна только через историю хранилища.
Думаю, что в  таких случаях можно действовать по двум вариантам: создать подзадачу в которой будет указана связанная конфигурация или изменять механизм выгрузки файлов:
1. Путь к файлам - вынести в константу и в сам файл писать к какой конфигурации/конфигурациям принадлежит задача
2. Добавить константу "узФормироватьФайлыВРазрезеКонфигураций" и тогда использовать пути выгрузки из реквизита спр.узКонфигурации с отбором задач по нужной конфигурации

**Comment by BlizD** [comment]
> Путь к файлам - вынести в константу и в сам файл писать к какой конфигурации/конфигурациям принадлежит задача

Путь к файлу листа по задачам, пусть также остается в справочнике Конфигурации, это менять не надо.

>Добавить константу "узФормироватьФайлыВРазрезеКонфигураций" и тогда использовать пути выгрузки из реквизита спр.узКонфигурации с отбором задач по нужной конфигурации

Да, это нормально. Единственно, вынести этот реквизит в справочник "Конфигурации" назвать его "Формировать файл лист задач с отбором по текущей конфигурации" (Булево).

**Comment by 79vlad** [comment]
Готово.
[1Cv8_TasksFiles_v_1_0_4_010.7z](https://drive.google.com/open?id=1IDkuFe8XxF0RGiKrzT2i7gRKpsGq6PBJ)

Также в этой выгрузке добавил:
1) в форме конфигураций изменил управление видимостью реквизитов для альтернативной загрузки.
2) в модуле объекта отменил обязательное заполнение параметров промежуточной файловой базы, если установлен альтернативный режим 

Желательно в ВИКИ внести изменения на этот счет: если альтернативная загрузка - то достаточно указать путь к хранилищу, пользователя хранилища и пароль этого пользователя

**Comment by capitoshko** [comment]
79vlad, а можете залить свои изменения в последнюю dev сф от Антона?

**Comment by 79vlad** [comment]
хорошо, вечером сделаю

**Comment by BlizD** [comment]
@79vlad 
Можете немного изменить реализацию, следующим образом:
* в обработку "узФормированиеФайлаСоСпискомЗадач" добавить реквизиты:
   * Конфигурация;
   * узФормироватьФайлСОтборомПоКонфигурации (Булево)
* Если стоит признак "узФормироватьФайлСОтборомПоКонфигурации" в обработке "узФормированиеФайлаСоСпискомЗадач" тогда делать такой отбор.
* в запросе где формируется список задач, можете исправить, чтобы запрос не дробился на части
![image](https://user-images.githubusercontent.com/10989306/46808709-99342800-cd75-11e8-8309-9f1ae19e6230.png)
Вместо этого необходимо вставить в запрос следующую конструкцию:
```
ВЫБОР КОГДА &ИспользоватьОтборПоКонфигурации ТОГДА
        узЗадачи.Конфигурация = &узКонфигурация
ИНАЧЕ
        ИСТИНА
КОНЕЦ
```

**Comment by BlizD** [comment]
* Название реквизита "узФормироватьФайлСОтборомКонфигураций" необходимо заменить на "узФормироватьФайлСОтборомПоКонфигурации" в справочнике "Конфигурации";

**Comment by 79vlad** [comment]
хорошо

**Comment by 79vlad** [comment]
@BlizD 
Изменил реализацию.
также в спр.узКонфигурации, добавил подсказки по альтернативной загрузке из хранилища и видимость полей, если выбрана альтернативная загрузка
[dev_Tasks111018_1804.cf](https://drive.google.com/open?id=1s68WJJGXRKUyqq9zMxEVAzMUUlv4SBe)
