### ISSUE TITLE
Цвет задачи в зависимости от последней даты изменения

### ISSUE THREAD

**Issue by capitoshko** [BlizD/Tasks#125]
Максим Дорофеев в своих видео вспоминал, что в одной с команд, они запустили механизмы разкашивание задач в зависимости от последней даты редактирования. Может реализуем такую настройку в системе?

**Comment by BlizD** [comment]
В этом случае на канбан доску необходимо еще добавить 2 признака:
* ВозрастЗадачиВДнях - считается от даты создания до текущего дня;
* КоличествоДнейСПоследнегоРедактирования

По поводу цвета пока бы не стал торопиться, так честно говоря расцветка по цветам, как минимум у нас особо не прижилась.
Также хотел спросить, почему не устраивает расцветка "Буфер канат", что сейчас реализована?

>* Цветовое выделение задач с помощью буфера (см. видео **Максима Дорофеева** "Апгрейд канбан — Барабан-буфер-канат" https://youtu.be/V-1RAneibos);
    * если у задачи указана важность "Обычная" и указан срок выполнения задачи, тогда для нее будет цвет меняться согласно буферу:
![default](https://user-images.githubusercontent.com/10989306/46809099-77877080-cd76-11e8-9dae-e3f7df0bd34e.png)

**Comment by capitoshko** [comment]
блін, я этого не читал
