### ISSUE TITLE
Проведение документа узВводФактаПоЗадаче

### ISSUE THREAD

**Issue by 7OH** [BlizD/Tasks#127]
При проведении документа Спринт зачем-то берётся последний на дату документа, хотя в табличной части уже есть заполненный спринт. 
Тест кейс - в регистре привязки спринта к задаче "почему-то" не оказалось записи, в документе указан спринт. При проведении в регистре тоже пусто.
Может стоит брать из ТЧ ?

**Comment by BlizD** [comment]
Да, надо брать из тч

**Comment by BlizD** [comment]
В данном случае спринт указанный в тч нужно брать для движений.

**Comment by 7OH** [comment]
Ну тут не подскажу, но по факту у меня текущий спринт с таким же в доке - провёлся на ура.
А документ с прошлой датой и прошлым спринтом в тч - пустой спринт попадает, видимо на дату документа записи нет. 
Ну и в принципе - проведение ведь должно быть прогнозируемым - в табличной части одни данные, в регистре могут быть (или не быть) другие - обычно я делаю как - в таблицу пишу те данные которые были в регистре и потом меняй сколько хочешь рег, а документ останется таким , как был введен.

**Comment by capitoshko** [comment]
Вы верно пишете. Но по факту регистр периодический и срез последних на дату должен давать последнюю запись спринта по задаче

**Comment by BlizD** [comment]
Если бы спринта в документе не было тогда да берем из регистра сведений.
