### ISSUE TITLE
Не верный реквизит спринт в канбан доске (1.0.4.018 )

### ISSUE THREAD

**Issue by 7OH** [BlizD/Tasks#128]
Релиз 1.0.4.018.
В канбан доску тянется реквизит Удалить_Спринт из шапки узЗадачи, вместо нового регистра "узФактПоЗадачам".

**Comment by 7OH** [comment]
По крайней мере есть бага. В регистре СпринтыЗадач задача числится в старом спринте.
В канбан доске ставлю отбор "Спринт.Завершен = Ложь",Ю но задача по прежнему на доске.
Посмотрел реквизиты - в реквизите "Удалить_Спринт" = стоит последний спринт.
Поставил ручками старый - из канбан доски пропало. в Запросе компоновки есть упоминание "Удалить_Спринт как Спринт" .

**Comment by BlizD** [comment]
Попробуйте, в канбан доске нажать "установить стандартные настройки". По идее в запросе указано все верно.

**Comment by 7OH** [comment]
нене - там наличие файлов берётся из задач, и спринт из удаленного, а дальше в срезе почему-то задачи из неверного запроса выше - там явно надо исправить запрос. Не должно ведь нигде мелькать использование реквизитов с "Удалить_".

**Comment by BlizD** [comment]
да, увидел.

**Comment by BlizD** [comment]
@7OH посмотри в 19 релизе ушла проблема? И по документам ввод задач.

**Comment by 7OH** [comment]
Простите мне, если что, а где взять ?
тут (https://github.com/BlizD/Tasks/releases) 18й

**Comment by BlizD** [comment]
Вот тут https://github.com/BlizD/Tasks/issues/129

**Comment by 7OH** [comment]
> 
> 
> @7OH посмотри в 19 релизе ушла проблема? И по документам ввод задач.

Работает отлично

**Comment by BlizD** [comment]
Хорошо
