### ISSUE TITLE
Не работает перетаскивание карточек в канбан доске

### ISSUE THREAD

**Issue by pallid** [BlizD/Tasks#130]
Управление задачами (1.0.4.018),
1С:Предприятие 8.3 (8.3.9.1850)

не работает перетаскивание карточек в канбан доске

Или это только у меня?

**Comment by capitoshko** [comment]
У меня работает. ПРобовал перемещать по разнх статусах. перемещаеться

**Comment by BlizD** [comment]
Василий, 
не смог повторить ошибку, карточки перетягиваются у меня.
Правда у меня на локальной машине:
Управление задачами (1.0.4.019),
1С:Предприятие 8.3 (8.3.9.1850)
А на работе: 
Управление задачами (1.0.4.018)
1С:Предприятие 8.3 (8.3.10.2639)

и там и там все ок.

**Comment by pallid** [comment]
Странно, почему то теперь стало перетаскивать

видимо надо было настояться базе )))

я эту проблему не один видел, правда, была.

закрываю

**Comment by BlizD** [comment]
Бывает когда карточка задачи почему то не выделилась, хотя показывает что была отмечена.
Помогает выбрать поставить курсор на другую задачу в другой колонке.
Скорее всего это платформа так себя ведет иногда.
