### ISSUE TITLE
В задачах на закладке "Учет времени" не отображаются примечания исполнителя

### ISSUE THREAD

**Issue by 79vlad** [BlizD/Tasks#131]
В задачах на закладке "Учет времени" не отображаются примечания исполнителя.
В приложенном  [cf](https://drive.google.com/open?id=1H-UMs0x1Bizv_Eh12qfv-Cw7t2r-eoRV) это неудобство исправлено следующим образом:
1) в регистр накопления добавлен реквизит "Примечание"
2) при проведении документа "узВводФактаПоЗадаче" - записываю примечание исполнителя из ТЧ "Данные"

Также в форме "ФормаДокументаВводСЗадачи" документа "узВводФактаПоЗадаче" воссоздал обработчики "При открытии" - автозаполнения ДатаНачала, ДатаОкончания и авторасчет "Факта" (также как было до 18-го релиза в форме узЗадачи).

В модуле проведения документа "узВводФактаПоЗадаче" - пришлось написать свой "велосипед" для записи спринта в регистр накопления (можно считать как дубль #127 ) - я реализовал оба метода: если исполнитель указал спринт - то он пишется в регистр накопления - в противном случае - пишется спринт из алгоритма автоподбора #104  от @capitoshko 
Мои доработки обрамлены:
// +++ 79Vlad  25.10.2018
// --- 79Vlad  25.10.2018

**Comment by 79vlad** [comment]
Может кому пригодится:
Также при переходе на 18-й релиз - примечания Исполнителей - не перенеслись в документы "узВводФактаПоЗадаче".
Написал внешнюю обработку - которая дозаполняет примечания в документах "узВводФактаПоЗадаче": [скачать](https://drive.google.com/open?id=12umFubkoXhBynMTKzKWFpwLTi9l5GceG)
PS При повторном использовании этой обработки - к уже существующим примечаниям - будут опять дописаны комментарии (я не делал проверки на то, что в документе уже есть заполненные примечания)

**Comment by BlizD** [comment]
Спасибо, обязательно посмотрю.

**Comment by capitoshko** [comment]
Существенные ошибки.....

**Comment by 79vlad** [comment]
> Существенные ошибки.....

О чем идет речь? Я не писал, что это ошибки - просто не удобно, т.к. не хватает привычной визуализации в учете времени. Мы в комментариях пишем информацию, которая потом выводится в отчете (внешний) о занятости программиста на протяжении отчетного периода. Также удобно видеть это и в форме задачи

**Comment by 7OH** [comment]
Поддержу - сегодня тоже об этом задумались. В отчете очень не хватает этого комментария.

**Comment by 7OH** [comment]
У себя сделал доработку -  добавил  реквизит "Примечание" в регистре "узФактПоЗадачам" и поправил проведение. Добавил вывод в список комментария. Поправил отчет по задачам, чтобы и итог показывало нормально и детально, если выбраны комментарии.

https://drive.google.com/open?id=1vE9qXsreWkcvMrHIJYxc7hUNYodJTy5o

**Comment by capitoshko** [comment]
эти изменения будут в перенесены в разработку?

**Comment by 7OH** [comment]
По хорошему бы ещё кто-то кроме меня проверил\обкатал. Все мы можем ошибаться.

**Comment by 79vlad** [comment]
> Поправил отчет по задачам, чтобы и итог показывало нормально и детально, если выбраны комментарии.
В свою рабочую базу перенес доработанный @7OH отчет, проверил: настроил нужный мне вариант отчета с комментариями - вроде работает корректно. (только в одном случае (еще не докопался до истинной причины) он не захотел выводить комментарий (хотя по другим задачам - вывел нормально) (PS учет времени перепроводил - в движениях есть).

**Comment by 79vlad** [comment]
> эти изменения будут в перенесены в разработку?

Тут уже пусть @BlizD решает какой из вариантов использовать.
Мой вариант (на базе 18-го релиза) отличается от 19-го и от @7OH  только тем, что при проведении документа, я оставил возможность автоподбора спринта, если исполнитель не указал (просто не разбирался в заложенной первоначальной идеи от @capitoshko ).

**Comment by BlizD** [comment]
На выходных посмотрю

**Comment by BlizD** [comment]
Залил изменения, смотреть в этом коммите 23f7048571447e75889aab060552556af3d33b51 
По изменениям:
* при проведении документа ВводФактаПоЗадачам - спринт берется из табличной части. При открытии формы нового факта по задаче текущий спринт заполняется автоматически.
* отчет по задачам не изменял, для просмотра деталей по факту задач (примечание, даты начала и окончания) нужен другой отчет. Чтобы в этом отчете не было дублей.
* сделал обработку заполнения примечаний, сработает на 20 релизе, проверяет заполненность примечания в документе, если не заполнен, тогда берез из задачи.

**Comment by 7OH** [comment]
Хм. А как Дубли то вышли? Я пробовал несколько дел в один документ и вроде не было

**Comment by BlizD** [comment]
@7OH 
> Хм. А как Дубли то вышли? Я пробовал несколько дел в один документ и вроде не было
Подскажи как реализован вывод примечаний в отчете по задачам? Не смотрел код, возможно там все ок.

**Comment by BlizD** [comment]
>Подскажи как реализован вывод примечаний в отчете по задачам? Не смотрел код, возможно там все ок.

Посмотрел, как реализовано, получается добавлен еще один набор и выбираются данные из регистра "узФактПоЗадачам" детальные записи. 
Получается если будет 2 разных примечания для одной задачи, то будет 2 записи для одной задачи в отчете.

**Comment by 7OH** [comment]
> 
> 
> @7OH
> 
> > Хм. А как Дубли то вышли? Я пробовал несколько дел в один документ и вроде не было
> 
> Подскажи как реализован вывод примечаний в отчете по задачам? Не смотрел код, возможно там все ок.

Всё через СКД. Там в СКД 2 набора данных. Из 2-го набора примечания тянутся. Если поля нет - скд ведь схлопывает сама часы. Возможно я не до конца протестил, но : вывожу без примечания - просто итоги выводит. Если выбираю примечание - выводит и примечание и часы корректные возле каждого.

**Comment by 7OH** [comment]
> 
> 
> > Подскажи как реализован вывод примечаний в отчете по задачам? Не смотрел код, возможно там все ок.
> 
> Посмотрел, как реализовано, получается добавлен еще один набор и выбираются данные из регистра "узФактПоЗадачам" детальные записи.
> Получается если будет 2 разных примечания для одной задачи, то будет 2 записи для одной задачи в отчете.

пару минут - сделаю набор скринов.

**Comment by 7OH** [comment]
![tasks_01](https://user-images.githubusercontent.com/3063507/47613958-000d4d00-daa9-11e8-82b3-3a9ae3cff7d9.png)
![tasks_02](https://user-images.githubusercontent.com/3063507/47613960-013e7a00-daa9-11e8-8322-440a0d792fcc.png)
![tasks_03](https://user-images.githubusercontent.com/3063507/47613961-03083d80-daa9-11e8-87b0-9394bf07d4ca.png)

**Comment by BlizD** [comment]
Как раз про вот этот и говорю (одна задача проходит в отчете несколькими строками):
![image](https://user-images.githubusercontent.com/10989306/47613989-8033b280-daa9-11e8-8e4f-3f80ee7a6f96.png)
В отчете есть еще показатель "КоличествоЗадач" - в этом случае будет показано для каждой из них будет указано 1

**Comment by 7OH** [comment]
Ну да - несколькими -а как ещё - задач же одна была, не разные.
Можно группировкой сделать - тут уже кто как данные хочет видеть.

**Comment by BlizD** [comment]
@7OH - ок, подумаем, может в твоем варианте и зальем. 
Смущает еще то, что данные из регистра узФактПоЗадачам - 2 раза выбирается.
Подскажите как ведет себя СКД если поле из второго набора не выбрано в отчете?
В этом случае 2 набор вообще не учитывается в результирующем запросе СКД?

**Comment by 7OH** [comment]
Из 2-го часы тоже тянутся, чтобы часы не дублировать. В общем его надо переделывать, но тоже с наборами, или одним, но с хитрыми полями итогов, или не "1 КАК КоличествоЗадач" а через Количество(Задача) в итогах скд. Единички он действительно считать с соединениями никак корректно не будет.
