### ISSUE TITLE
Работа в WEB-клиенте (браузере).

### ISSUE THREAD

**Issue by 7OH** [BlizD/Tasks#132]
Решили опубликовать базу , чтобы можно было работать прямо через браузер заказчикам (да и исполнителям иногда).
На стартовой странице таблица не очень выглядит.
А в канбан доске перетаскивание не работает - вот это хотелось бы поправить.

**Comment by BlizD** [comment]
Это было бы хорошо если получится исправить.

**Comment by 7OH** [comment]
https://drive.google.com/open?id=1knopPJwWNQArldVElYc0HAMUZRP5CgXw
Перетаскивание исправил, а вот с текстом беда: в клиенте 1С - текст как подсказка отображается, а в вёбе просто последние символы всегда видны. Добавил перенос строки в конце - в обычном не мешает вроде, а в вёбе точкой показывает.
