### ISSUE TITLE
Ограничение доступа через RLS

### ISSUE THREAD

**Issue by BlizD** [BlizD/Tasks#134]
№399 Ограничение доступа через RLS

[№399 Ограничение доступа через RLS.docx](https://github.com/BlizD/Tasks/files/2529658/399.RLS.docx)

**Comment by BlizD** [comment]
@capitoshko посмотри вариант реализации RLS в файле.

**Comment by 7OH** [comment]
Вполне - просто задачи разделить пойдёт.

**Comment by 79vlad** [comment]
Добрый день.
Я бы пошел по пути "Групп пользователей".
В регистре сведений хранить перечень доступных задач для каждой группы.
RLS настроить на этот регистр, если задача в перечне доступных - то задача доступна. Перечень групп пользователя, можно также хранить в регистре сведений. В RLS, пходящим параметром будет текущий пользователь. В запросе надо выбрать все группы пользователя и для этих групп получить доступные задачи.
Осталось определиться, в какой момент выполняется запись о том, что данная группа пользователей имеет право на задачу.
Чтобы не нагружать RLS подзапросами, в регистре доступа к задачам, записи должны быть на равенство (без "в иерархии")

**Comment by 7OH** [comment]
Ну и ещё ведь надо разделить на видимость и на возможность редактирования. Не ? То есть видеть - смотри, а редактировать зась.

**Comment by 79vlad** [comment]
Это тоже можно через RLS реализовать. Я написал общую концепцию, а там можно её и модифицировать (главное, чтобы был источник информации для RLS)

**Comment by capitoshko** [comment]
А можете это все дописать в файл Ворд, который выложил Антон в виде дополнений в ТЗ?

**Comment by capitoshko** [comment]
Группы пользователей это хороший вариант. Не надо будет для каждого пользователя писать свои ограничения, а добавит его в группу и права уже будут. Хотя если у пользователя отдельные крутые оправа, то для него группу нужно будет дублировать.

Для самих шаблонов я бы использовал параметры сеанса, задач может быть много, если ограничения написать в регистр, то может сильно тормозить работу. То есть при начале сеанса ограничения с регистра сведений писать в параметр сеанса и уже его юзать  при ограничении доступов.

**Comment by 7OH** [comment]
Параметр один , а задач много. Не выйдет. По группам: при добавлении человека в несколько групп - писать в регистр максимальный доступ по задаче

**Comment by 79vlad** [comment]
> Группы пользователей это хороший вариант. Не надо будет для каждого пользователя писать свои ограничения, а добавит его в группу и права уже будут. Хотя если у пользователя отдельные крутые оправа, то для него группу нужно будет дублировать.

Это решается или отдельной группой или отдельной ролью (без ограничений)

> Для самих шаблонов я бы использовал параметры сеанса, задач может быть много, если ограничения написать в регистр, то может сильно тормозить работу. То есть при начале сеанса ограничения с регистра сведений писать в параметр сеанса и уже его юзать при ограничении доступов.


В том и прелесть связки RLS  и регистра сведений, что входящим параметром, будет только один параметр сеанса "Пользователь", который передается на вход  запроса RLS. Запрос RLS получает выборку из регистров сведений, касательно только текущего пользователя. При этом в параметры сеанса нет необходимости протягивать массивы данных по доступным группам пользователя и доступным задачам (иначе положим систему по используемой памяти), а также, если эти данные хранить в параметрах сеанса - то при добавлении новых разрешений, необходимо всем текущим пользователям обновить эти параметры сеанса

>Ну и ещё ведь надо разделить на видимость и на возможность редактирования. Не ? То есть видеть - смотри, а редактировать зась.

Можно это предусмотреть в регистре как ресурсы (будево) "Полный доступ" и "Чтение". В запросе RLS для каждого события доступа (чтение/просмотр/изменение/...) установить необходимое условие на эти ресурсы

**Comment by 79vlad** [comment]
> А можете это все дописать в файл Ворд, который выложил Антон в виде дополнений в ТЗ?

Попробую вечером (по дороге домой) описать в файле.

**Comment by capitoshko** [comment]
При использовании регистров сведений права актуализируются налёту?

**Comment by capitoshko** [comment]
Если опишите, то я могу попробовать сделать

**Comment by 79vlad** [comment]
> При использовании регистров сведений права актуализируются налёту?

Да - данные из регистра RLS вычитывает регистры заново, при каждом запросе к БД (но при условии, что в запросе указанно "РАЗРЕШЕННЫЕ").

**Comment by capitoshko** [comment]
Давайте опишите, если можете, я с ограничениями плотно не работал, могу по вашему ТЗ, если Антон не против, попробовать сделать.

**Comment by BlizD** [comment]
Про группы у меня тоже свое мнение. Допишите в тз Ваще предложение там и обсудим

**Comment by 79vlad** [comment]
Дописал к существующему ТЗ, свое видение по реализации (на то, что это конечный вариант - не претендую). выложил на гуглдиске (удобно реализован многопользовательский режим редактирования документов): [ТЗ на RLS](https://docs.google.com/document/d/1pEZfuCTqf3axV7oBsQmBmhZT1zC47OFovnUi1_uAEAc/edit?usp=sharing)

**Comment by 7OH** [comment]
Я комментарий оставил. Я за группы и против лишних запросов в RLS.

**Comment by 79vlad** [comment]
> Я комментарий оставил. Я за группы и против лишних запросов в RLS.

Я тоже за то, чтобы в запросах RLS было минимум подзапросов и условий "ИЛИ" - это отрицательно сказывается на производительности

**Comment by BlizD** [comment]
Коллеги, добавил ответы, поправил ТЗ. Искать можно по "Антон 031118"

**Comment by BlizD** [comment]
> Для RLS, будет легче, если в регистре сведений будет указана конкретная задача, а не основная, т.к. в запросе RLS нельзя использовать "В ИЕРАРХИИ". (Свои примечания оставил по тексту ТЗ)

В ИЕРАРХИИ не требуется, в каждой задаче есть реквизит "Основная задача". Таким образом в ограничении необходимо использовать Ссылка.ОсновнаяЗадача ...

**Comment by 79vlad** [comment]
А если в задачах уровень иерархии более 2-х?
Тогда в запросе необходимо писать для каждого уровня проверку, (узЗадача.ОсновнаяЗадача.ОсновнаяЗадача.ОсновнаяЗадача....).
Это точно не правильно

**Comment by 79vlad** [comment]
При написании варианта 2, я об этом и подумал, поэтому и написал, что в регистре делается запись на конкретную задачу, а также предусмотрел команду наследования прав из основной задачи

**Comment by BlizD** [comment]
> А если в задачах уровень иерархии более 2-х?
> Тогда в запросе необходимо писать для каждого уровня проверку, (узЗадача.ОсновнаяЗадача.ОсновнаяЗадача.ОсновнаяЗадача....).
> Это точно не правильно

Это не требуется, доступ настраивается на конкретную основную задачу и необходимо сравнивать только узЗадача.ОсновнаяЗадача.

**Comment by BlizD** [comment]
> При написании варианта 2, я об этом и подумал, поэтому и написал, что в регистре делается запись на конкретную задачу, а также предусмотрел команду наследования прав из основной задачи

Наследование с одной стороны хорошо, но с другой стороны это усложнение, это необходимо держать в голове и знать об этом. 
В случае когда нет наследования все просто, есть запись в РС значит доступ есть, нет записи доступа нет.

Пока думаю не стоит реализовывать наследование.

**Comment by 79vlad** [comment]
<Это не требуется, доступ настраивается на конкретную основную задачу и необходимо сравнивать только узЗадача.ОсновнаяЗадача.

У меня сейчас 3-4 уровня: в задачах есть подзадачи. Первый уровень - это основные направления (автоматизация фин. деп; автоматизация склада; автоматизация бухгалтерского учёта и т.п.), второй уровень - детализация основного направления, далее идут задачи, которые могут быть разбиты на подзадачи и т.д.

**Comment by BlizD** [comment]
В этом случае необходимо проставить признак "ЭтоОсновнаяЗадача" = Истина для уровней:
* Первый уровень - Автоматизация Фин.Деп - "ЭтоОсновнаяЗадача" = Истина
    * Направление деятельности №1 - "ЭтоОсновнаяЗадача" = Истина
        * Подраздел №2 - "ЭтоОсновнаяЗадача" = Истина
            * Детальные задачи - в них - "ЭтоОсновнаяЗадача" = Ложь

в этом случае будут следующие значение основных задач:
* Первый уровень - Автоматизация Фин.Деп 
    * Направление деятельности №1 -  Основная задача  = Автоматизация Фин.Деп
        * Подраздел №2 - Основная задача  = Направление деятельности №1
            * Детальные задачи - Основная задача  = Подраздел №2

**Comment by BlizD** [comment]
Подскажите в Вашем случае для какого уровня необходимо сделать раздельный доступ?
Для направлений деятельности?

**Comment by 7OH** [comment]
Мои 5 копеек. Доступ должен быть на конкретную задачу. А учитывать основную (в том числе и рекурсивно)  можно при записи самой задачи, записывая в регистр наследование,Если надо.

**Comment by BlizD** [comment]
> Мои 5 копеек. Доступ должен быть на конкретную задачу. А учитывать основную (в том числе и рекурсивно) можно при записи самой задачи, записывая в регистр наследование,Если надо.

Возможно к этому и придем, что доступ в РС будем указывать на конкретную задачу. Пока достаточно "Основной задачи".

**Comment by 79vlad** [comment]
Так и есть.
Осталось определиться как определить доступ к задаче? 
Например, пользователям могут быть доступны не все задачи от уровня 1, а только подзадачи определенной ветки/подсветки.

**Comment by 7OH** [comment]
А если основной задачи нет?

**Comment by BlizD** [comment]
> Так и есть.
> Осталось определиться как определить доступ к задаче?
> Например, пользователям могут быть доступны не все задачи от уровня 1, а только подзадачи определенной ветки/подсветки.

В этом случае для нужной ветки/подветки устанавливаем признак "Это основная задача" = Истина
и настраиваем доступ для этой основной задачи.

**Comment by 79vlad** [comment]
Мое мнение, что первый вариант более сложный в реализации и обслуживании.
Но решать Вам.

**Comment by 7OH** [comment]
И всё таки. Давайте как с поведением делать. Сам рлс должен смотреть просто нам задачу. А вот значение для неё надо прописать в процедуре ,в которой из формы добавления доступа модно уже учесть как учитывать доступ к основной по иерархии.

**Comment by BlizD** [comment]
> А если основной задачи нет?

Это может быть только для самого верхнего уровня (первого уровня). 
Тут необходимо понять, для пустой основной задачи будем показывать список или нет. 
Придется в RLS добавлять ИЛИ

`узЗадачи.ОсновнаяЗадача = ЗаписьВРС.ОбъектБД
ИЛИ узЗадачи= ЗаписьВРС.ОбъектБД`

**Comment by BlizD** [comment]
> И всё таки. Давайте как с поведением делать. Сам рлс должен смотреть просто нам задачу. А вот значение для неё надо прописать в процедуре ,в которой из формы добавления доступа модно уже учесть как учитывать доступ к основной по иерархии.

Можете пояснить еще раз, не совсем понял, что предлагаете.

**Comment by BlizD** [comment]
> И так - в РЛС не должно быть ИЛИ - по максимуму просто. Отсюда требование (из п.1), чтобы доступ был обозначен для конкретной задачи. В регистре настроек определения доступа или как мы сделаем - будет задача, 2 значения доступа и например метод наследования (не наследовать, от основной, по иерархии). При изменении задачи или группы доступа - вычисляем заново необходимый уровень , который надо записать в регистр для РЛС. При записи задержка позволительна почти любая, а вот при использовании запросов - нам ведь нужно минимум ресурсов использовать.

Понял, пока идем на использование ИЛИ в RLS. 
Если будут проблемы с производительностью, тогда попробуем вариант через добавление записей в РС на конкретную задачу и исключение ИЛИ из RLS.

Думаю, что в варианте через "Основную задачу", особых проблем с ИЛИ не будет.

По поводу наследование, пока отложим этот вопрос, пока делаем без наследования.

**Comment by capitoshko** [comment]
Антон, вариант может уже быть проблематичным. У нашей команды уже 3500 задач. Боюсь, что тормоза начнутся сразу. Вариант доступ к конкретной задаче будет работать вполне пристойно. Использование условия ИЛИ может сильно снизить продуктивность

**Comment by 79vlad** [comment]
Также не надо забывать, что в работающей системе, необходимо заполнить новые регистры, необходимо предусмотреть обработку, в которой можно будет связать задачи и группы пользователей. А эта обработка уже запустит алгоритмы заполнения регистров прав. Потом эта обработка может выступать как рабочий инструмент администратора по правам

**Comment by 79vlad** [comment]
> Первоначальное заполнение лутче сделать вручную

Тут может только человек сделать, поэтому и пишу, что обработку (не обработчик) надо делать, которая позволит выполнить массовое заполнение (по настройкам). Например, выбранному списку групп пользователей, дать доступ в списку задач (точечный список или с учётом подчинённых)

**Comment by BlizD** [comment]
> Антон, твой вариант может уже быть проблематичным. У нашей команды уже 3500 задач. Боюсь, что тормоза начнутся сразу. Вариант доступ к конкретной задаче будет работать вполне пристойно. Использование условия ИЛИ может сильно снизить продуктивность

Чтобы избежать условие ИЛИ, необходимо сделать, чтобы на верхнем уровне тоже заполнялся реквизит "Основная задача". Это можно сделать. 
У нас тоже уже около 4000 задач.

**Comment by BlizD** [comment]
Меня останавливает в схеме доступа к конкретной задаче (а не через основную задачу) следующие моменты:
* записей в РС доступа будет много. 3000 задач * 10 пользователей = это уже 30000 записей и кол-во записей будет постоянно расти.
* надо постоянно следить за правильностью записей в этом РС;
* что делать если для подчиненной задачи есть доступ, а для ее родителя доступа нет, в этом случае RLS не покажет задачу, насколько понимаю.
* запись конкретной задачи удлиняется - так как надо проверять правильно ли указан доступ к ней, в случае необходимо добавлять/удалять записи из РС. 

Поэтому считаю, что доступ RLS через реквизит "ОсновнаяЗадача" будет проще реализовать, обслуживать и скорость будет сопоставимой с доступом к конкретной задаче.

**Comment by capitoshko** [comment]
А если нужно дать доступ к подпроекту конкретного проекта? Нужно давать доступ на чтение к проекту в целом и к подпроекту?

**Comment by 79vlad** [comment]
> записей в РС доступа будет много. 3000 задач * 10 пользователей = это уже 30000 записей и кол-во записей будет постоянно расти.


Идея в том, чтобы в регистр писались группы пользователей. В исключительных ситуациях (при острой необходимости), чтобы дать персональный доступ к задаче - указывать пользователя.
Тогда это будет 2-3 группы доступа (группа заказчика и группа исполнителей) (3000 задач * 2 (3) = 6000 (9000) записей. Для удобного администрирования, надо обработку писать. Для контроля - отчёт.

**Comment by BlizD** [comment]
>А если нужно дать доступ к подпроекту конкретного проекта? Нужно давать доступ на чтение к проекту в целом и к подпроекту?

Чтобы дать доступ к подпроекту, необходимо его пометить признаком "Это основная задача" = Истина. После этого настраивать доступ к подпроекту.

>Выпущена версия 1.0.3.027 (Обновление от 10.09.2017)

![thismaintask](https://user-images.githubusercontent.com/10989306/30246678-9cbc2828-9609-11e7-95ac-107ce4979c83.gif)

**Comment by BlizD** [comment]
>Идея в том, чтобы в регистр писались группы пользователей. В исключительных ситуациях (при острой необходимости), чтобы дать персональный доступ к задаче - указывать пользователя.
Тогда это будет 2-3 группы доступа (группа заказчика и группа исполнителей) (3000 задач * 2 (3) = 6000 (9000) записей. Для удобного администрирования, надо обработку писать. Для контроля - отчёт.

Вот тут против этого, в регистр должен указываться конкретный пользователь. Чтобы в RLS не раскручивать группы пользователей.

>Для удобного администрирования, надо обработку писать. 

Пока необходимо настраивать через отдельный справочник (в тз описан). Позже действительно придется сделать удобную обработку, которая будет этот справочник читать и обрабатывать.

**Comment by 7OH** [comment]
Я тоже за пользователя. Это в настройке указываем или группу или пользователя - и при записи смотрим кто в группе есть, если это группа.

**Comment by BlizD** [comment]
@79vlad все таки предлагаю, делать по моему ТЗ, в случае появление проблем. 
Будем обсуждать и искать выход.

**Comment by 7OH** [comment]
Так по чём всё таки предлагаете делать доступ ? Я с основной задачей немного не пойму. Допустим по основной задаче есть 9 задач и 3 вида работ по разным направлениям - как в итоге делать доступ ?

**Comment by BlizD** [comment]
@7OH 
создал пример в Excel напишите к какой ветке, Вы, хотите ограничить доступ?

[СхемаЗадач.xlsx](https://github.com/BlizD/Tasks/files/2545896/default.xlsx)

**Comment by 7OH** [comment]
> 
> 
> @7OH
> создал пример в Excel напишите к какой ветке, Вы, хотите ограничить доступ?
> 
> [СхемаЗадач.xlsx](https://github.com/BlizD/Tasks/files/2545896/default.xlsx)

[Пример_Права.xlsx](https://github.com/BlizD/Tasks/files/2545902/_.xlsx)

**Comment by BlizD** [comment]
@7OH 

[СхемаЗадач7OHОтвет.xlsx](https://github.com/BlizD/Tasks/files/2545912/7OH.xlsx)

**Comment by 7OH** [comment]
> 
> 
> @7OH
> 
> [СхемаЗадач7OHОтвет.xlsx](https://github.com/BlizD/Tasks/files/2545912/7OH.xlsx)

Я то могу так сделать, а вот топы вряд ли - надо проще. Мне будет сложно объяснять, что кроме еле поставленной задачи, ему надо ещё и подзадачи делать.

**Comment by 79vlad** [comment]
> Они будут видны всем тем у кого есть доступ к задаче «Задача« Запуск магазинов ». 
@Capitoshko @ 79vlad Это проблема?

Думаю, что это проблема, т.к. изначально хотелось бы, чтобы для пользователей, это работало по принципу "а мы даже и не подозревали, что в этой программе ведутся проекты, кроме нашего".

Также, опять внесу смуту по поводу кому прописывать доступ в регистре (пользователю или группе пользователей):
1) Если писать на конкретного пользователя, то при исключении/включении в группу пользователей: надо будет перебирать весь регистр и искать, к каким задачам запретить доступ, а к каким надо дать доступ.
2) При записи доступа на группу: RLS самостоятельно определит доступные задачи по группам текущего пользователя (без дополнительных перезаписей регистра доступа). 

(На одной из работ у нас на пользователя назначались права, и когда админу (ответственному за доступы) приходила задача предоставить или запретить доступ списку пользователей - он тихо матерился, но упорно работал с регистром прав (для этого у него было несколько обработок) но чем больший список пользователей ему приходил тем дольше он его обрабатывал. После того, как перешли на группы пользователей, права он назначал играючись (в процессе приема обращения по телефону - просто добавлял пользователя в необходимые группы)

**Comment by capitoshko** [comment]
Если я верно поняла с примера, то чтобы дать доступ на задачу 23 нужно дать доступ и на задачу 21. В логике системы все задачи, которые имеют подзадачи - это проекты. И чтобы дать доступ на конкретные задачи проекта нужно как минимум дать доступ на все уровни иерархии, в которых этот проект фигурирует. Если я не ошибаюсь, то в таком случае нужно писать доступы на чтение для всех уровней выше и на запись для всех задач проекта. Сам проект - только на чтение. Это оптимально можно сделать отдельным регистром из доступами к конкретной задаче.

Если не будет затруднительным, то может сделаем небольшую Скайп конференцию, обсудим и уже будем думать вместе в едином русле.

**Comment by 79vlad** [comment]
To @capitoshko В Скайпе мой логин vagrigoryev
(я просто опираюсь на ошибки с которыми приходилось сталкиваться ранее) :-)

**Comment by capitoshko** [comment]
Мой скайп capitoshko.

У меня также есть небольшой опыт настройки доступов. Мне бы хотелось, чтобы мы вышли на общий наменатель, а то переписка уж очень затянулась. у меня завтра с 11.00 до 12.00 по Киеву есть время. Как у вас?

**Comment by 79vlad** [comment]
To @capitoshko  завтра у меня время будет во второй половине дня (после 14.00 (по Киеву). До обеда буду занят.

**Comment by capitoshko** [comment]
на 15.00 будет удобно?

**Comment by 79vlad** [comment]
> на 15.00 будет удобно?

Удобно (а любое после 14:00)

**Comment by BlizD** [comment]
> > Они будут видны всем тем у кого есть доступ к задаче «Задача« Запуск магазинов ».
> > @capitoshko @ 79vlad Это проблема?
> 
> Думаю, что это проблема, т.к. изначально хотелось бы, чтобы для пользователей, это работало по принципу "а мы даже и не подозревали, что в этой программе ведутся проекты, кроме нашего".
> 
> Также, опять внесу смуту по поводу кому прописывать доступ в регистре (пользователю или группе пользователей):
> 
> 1. Если писать на конкретного пользователя, то при исключении/включении в группу пользователей: надо будет перебирать весь регистр и искать, к каким задачам запретить доступ, а к каким надо дать доступ.
> 2. При записи доступа на группу: RLS самостоятельно определит доступные задачи по группам текущего пользователя (без дополнительных перезаписей регистра доступа).
> 
> (На одной из работ у нас на пользователя назначались права, и когда админу (ответственному за доступы) приходила задача предоставить или запретить доступ списку пользователей - он тихо матерился, но упорно работал с регистром прав (для этого у него было несколько обработок) но чем больший список пользователей ему приходил тем дольше он его обрабатывал. После того, как перешли на группы пользователей, права он назначал играючись (в процессе приема обращения по телефону - просто добавлял пользователя в необходимые группы)

@79vlad пусть Админ также обрабатывает группы доступа, но запись пишется на конкретного пользователя. По идее для админа в этом случае ничего не должно меняться.

**Comment by 7OH** [comment]
Всем доброе время суток. Что-то никого давно не слышно ничего. Есть какие-то подвижки ? А то тут нажимает народ, чую на днях начну делать сам. И будет потом не удобно, если уже есть и так и так сделанное.

**Comment by capitoshko** [comment]
У меня на работе завал. Если сделаете быстрее - выложите, Антон подтянется изменения.

**Comment by BlizD** [comment]
>У меня на работе завал.
+1 у меня тоже завал

Хочу предупредить, что для данной задачи будут повышенные требования к проверке кода.
Поэтому необходимо соблюдать стиль кодирования и стандарты 1с.

**Comment by capitoshko** [comment]
Если доберусь, то буду проверять стандартной автоматизированной проверкой, если вы не против

**Comment by capitoshko** [comment]
Может кто-то сделал? Или ждут добровольца?

**Comment by 7OH** [comment]
Я на полпути остановился (с наследованием прав). Не отпустили ещё новогодние праздники.

**Comment by capitoshko** [comment]
Я тогда не буду начинать?

**Comment by capitoshko** [comment]
Или давай Антон зальет изменения, я доработаю.

**Comment by BlizD** [comment]
Я не делал, хотя руки чешутся.

**Comment by BlizD** [comment]
Всем привет.
Наш выработанный подход не совсем верный.
Вот видео на эту тему:
[https://its.1c.ru/video/erp_train2018_d1_17_30](https://its.1c.ru/video/erp_train2018_d1_17_30)
Если руки доберутся до этой задачи, то необходимо делать как описано в видео.
![image](https://user-images.githubusercontent.com/10989306/58397938-b7783b00-805b-11e9-839f-18c436c39085.png)

**Comment by BlizD** [comment]
![image](https://user-images.githubusercontent.com/10989306/58398009-07570200-805c-11e9-9d91-6c74103a6444.png)

**Comment by BlizD** [comment]
![image](https://user-images.githubusercontent.com/10989306/58398045-2fdefc00-805c-11e9-9b9a-00987b426e18.png)

**Comment by BlizD** [comment]
![image](https://user-images.githubusercontent.com/10989306/58398148-ada30780-805c-11e9-825e-65a40ec81fa4.png)

**Comment by BlizD** [comment]
![image](https://user-images.githubusercontent.com/10989306/58398209-f5299380-805c-11e9-9e25-bca8018ad152.png)

**Comment by BlizD** [comment]
Продублирую на всякий случай. @capitoshko @79vlad @7OH
>Всем привет.
Наш выработанный подход не совсем верный.
Вот видео на эту тему:
https://its.1c.ru/video/erp_train2018_d1_17_30
Если руки доберутся до этой задачи, то необходимо делать как описано в видео.

**Comment by 7OH** [comment]
https://drive.google.com/open?id=1HKnSDd6goXwmfOKPje_0el7AWuTYosYX
На базе последнего 038 билда с обновленным БСП.
2 роли, на чтение и на запись, так как на один вид объекта БСП не даёт разные виды доступа делать.
Куда достал - поправил в запросах РАЗРЕШЕННЫЕ.
Видимость реквизита по функциональной опции включения ограничения.
При вводе новой задачи - просто беру группу доступа у родителя. 
Нужно обыграть момент записи задачи с изменением группы как-то красиво.
---
В общем - не судите строго.

**Comment by BlizD** [comment]
@7OH Семен спасибо.

**Comment by BlizD** [comment]
@7OH Семен залил изменения. Еще раз спасибо.
Обновил файл CF в дев ветке #123

**Comment by 7OH** [comment]
За некоторое время тестирования нашел небольшое упущение в правах.
В ролях "узПользовательОграничениеДоступаЧтение" и "узПользовательОграничениеДоступаИзменение" не хватает ограничения на чтение справочника "узГруппыДоступаЗадач":
`#Если &ОграничениеДоступаНаУровнеЗаписейУниверсально #Тогда
#ДляОбъекта("")
#Иначе
#ПоЗначениям("Справочник.узГруппыДоступаЗадач", "", "",
"ГруппыДоступаЗадач", "Ссылка",
"", "",
"", "",
"","",
"","","","","","","","",
"","","","","","","","",
"","","","","","","",""
)
#КонецЕсли`

**Comment by BlizD** [comment]
Хорошо, добавлю.

**Comment by BlizD** [comment]
@7OH Семен, добавил изменения. 1664c43c9e74698b2effec3d72e4d4ce0f10b6ac
