### ISSUE TITLE
Обновление БСП до 2.3.2.205

### ISSUE THREAD

**Issue by BlizD** [BlizD/Tasks#138]
**Обновление БСП до 2.3.2.205**

План обновления:
* сначала перенесу все подсистемы из 2.3.2.76 в текущую конфигурацию;
*  попробую сделать CFU файл обновления БСП с 2.3.2.76 до 2.3.2.205;
* обновить нашу конфигурацию с использованием CFU, чтобы обновилась поддержка.

**Comment by capitoshko** [comment]
накатить обновления просто не получиться?

**Comment by BlizD** [comment]
Обновление чего? файлов cfu для обновления БСП нет.
Если про обновления потом tasks, то там в итоге будет простое обновление.

**Comment by capitoshko** [comment]
Может проще взять сф и накатить обновления? Но я так понимаю тогда версия БСП будет старая.

**Comment by BlizD** [comment]
>Может проще взять сф и накатить обновления?
Да, вот не получается проще, слишком много расхождений показывает из за того, что часть подсистем не включена. 

>Но я так понимаю тогда версия БСП будет старая.
Да, в этом случае конфа поставщика не обновится.

**Comment by BlizD** [comment]
Выполнена
