### ISSUE TITLE
Добавить реквизиты "ВКакойСпринтПришла" и "ВКакойСпринтСделали"

### ISSUE THREAD

**Issue by capitoshko** [BlizD/Tasks#140]
Для запуска механизмов планирования проектов за Максимом Дорофеевым

https://www.youtube.com/watch?v=ZbuC2h-Lya4&t=23s

Для этого нужно добавить реквизитв задачу "СпринтРегистрации" со ссылкой на спринт, в течении которого была получена хзадача по проекту от пользователей

**Comment by BlizD** [comment]
Спасибо, чуть позже посмотрю видео и отпишусь по названию

**Comment by BlizD** [comment]
Изменение необходимо для задачи #141

**Comment by BlizD** [comment]
@capitoshko 
Думаю лучше назвать "ВКакойСпринтПришла", ровно так же как и проходит в видео.

**Comment by BlizD** [comment]
* Также нужна обработка, которая заполнит данные реквизиты в существующих задача;
* необходимо сделать, чтобы данные реквизиты если не заполнены то заполнялись данными по умолчанию (для новой задачи, при переводе в вид статуса "Выполнено").

**Comment by capitoshko** [comment]
Согласен, если задача будет переходить со спринта в спринт то именно это будет идентификатором когда была выполнена.
