### ISSUE TITLE
Ошибка при отправке уведомления на телеграмм

### ISSUE THREAD

**Issue by 79vlad** [BlizD/Tasks#143]
Если в отправляемом тексте присутствуют зарезервированные символы - то при выполнении http-запроса, возникает ошибка.
Исправления в [Tasks111018_vlad_12122018_1704.cf](https://drive.google.com/open?id=1-4sP34ZMVw-R16j4LxvNYvlEQXdTW18z)
"ОбщийМодуль.узТелеграммСервер" по коментариям "// +++ Григорьев":

Добавлена функция "ЗаменитьЗарезервированныеСимволы" (на всякий случай - экспортная), которая перекодирует зарезервированные символы, для того, чтобы корректно выполнялся http-запрос
PS Источник кодировки символов: [Кодирование URL](https://ru.wikipedia.org/wiki/URL)

**Comment by BlizD** [comment]
Спасибо добавлю

**Comment by 7OH** [comment]
Добрый день.
Не проверял - смотрю изменения в релизе.
Но если я верно помню - в режиме markdown знак * используется для придания тексту жирности,  а мы его заменяем на код html.

**Comment by 79vlad** [comment]
> Добрый день.
> Не проверял - смотрю изменения в релизе.
> Но если я верно помню - в режиме markdown знак * используется для придания тексту жирности, а мы его заменяем на код html.

Добрый день.
Абсолютно согласен с особенностями markdown , но при формировании строки httpЗапрос - используются правила кодирования URL (справка в 1С говорит, что зарезервированные символы перекодируются самостоятельно, а по факту видим, что нет). Только что перепроверил - в теме письма зарезервированные символы:
1)  `"%^:;[***]{}?,."@|#`  - уведомление на телеграмм пришло
2) `*** "%^:;[***]{}?,."@|#`  - уведомление мне не пришло, в ЖР запись о том, что сообщение не отправлено :( 

PS Надо искать пути решения, чтобы в любом случае уведомления могли быть доставлены

**Comment by 79vlad** [comment]
>  а мы его заменяем на код html.

Маленькая ремарка - мы не заменяем, а перекодируем символ, чтобы в строке URL - они не воспринимались как обычные символы.
Тоже самое, но автоматически происходит для символов кириллицы.
