### ISSUE TITLE
В справочнике "узКонфигурации" не отображается реквизит "РазрешеныКомментарииБезЗадач"

### ISSUE THREAD

**Issue by 79vlad** [BlizD/Tasks#144]
Добрый день.
В файле [dev_Tasks191218_1141_79vlad.cf](https://drive.google.com/open?id=1wvoU3WSfzhl2kYDx0iQT8bzv0unLucgi) изменены формы элемента и формы списка для справочника "узКонфигурации":
1) В форме элемента выведен реквизит "РазрешеныКомментарииБезЗадач". Изменено расположение реквизитов. Переименованы названия групп. В модуле формы изменена процедура  "УстановитьВидимостьДоступность";
2) В форме списка оставлены только основные (на мой взгляд нужные) реквизиты.

PS приложенный cf - создан на базе крайнего "dev_Tasks161218_1450.cf"

**Comment by BlizD** [comment]
Отлично, спасибо.
Как закину отпишусь.

**Comment by BlizD** [comment]
Залил изменения, 
обновил последний файл CF из дев ветки.
