### ISSUE TITLE
При создании уведомления, важность для уведомления подбирать по "ИмяПредопределенногоЭлемента"

### ISSUE THREAD

**Issue by BlizD** [BlizD/Tasks#148]
>Alexei Snitkovski:
Доброе утро, коллеги!
Ошибка вываливается при попытке проведения новой Задачи, если перед этим переименовать существующие "Важности" в соответствующем Справочнике (например, "Обычная" на "Normal") или - тем более - создать там новый элемент (например, "Very High")

**Comment by BlizD** [comment]
При создании уведомления, важность для уведомления подбирать по "ИмяПредопределенногоЭлемента", чтобы обойти следующую ошибку.

![image](https://user-images.githubusercontent.com/10989306/50763908-3ffb6800-1282-11e9-80a7-7c1ee95836fb.png)

**Comment by BlizD** [comment]
Необходимо создать функцию в которой делать сопоставление элементов из справочника
* узВариантыВажностиЗадачи
в перечисление
* ВариантыВажностиВзаимодействия

**Comment by 1C-Romania** [comment]
Предлагаю в Справочник "узВариантыВажностиЗадачи" добавить ссылочное поле в котором Пользователь сможет самостоятельно настроить сопоставление элементов из справочника с элементами БСПшного перечисления "ВариантыВажностиВзаимодействия"

**Comment by 79vlad** [comment]
> Предлагаю в Справочник "узВариантыВажностиЗадачи" добавить ссылочное поле в котором Пользователь сможет самостоятельно настроить сопоставление элементов из справочника с элементами БСПшного перечисления "ВариантыВажностиВзаимодействия"

Поддержу, так как, в таком варианте, администратор сможет самостоятельно установить важность исходящего письма для различных состояний задачи

**Comment by BlizD** [comment]
Согласен.

**Comment by BlizD** [comment]
Добавил реквизит в справочник Важности.
Выпустил промежуточный релиз 1.0.4.023 (см.  промежуточные релизы #129)
