### ISSUE TITLE
Реализовать возможность вводить описание задачи с помощью стиля Markdown

### ISSUE THREAD

**Issue by BlizD** [BlizD/Tasks#15]
Реализовать возможность вводить описание задачи с помощью стиля Markdown.

Что необходимо:
*  для описания задачи должен быть просмотр с учетом стиля Markdown;
*  для того, чтобы показать описание задачи в стиле Markodwn, не должен требоваться интернет;

**Comment by BUDIVAL** [comment]
Весь код преобразования должен быть на 1С или использовать локальное приложение?

**Comment by BlizD** [comment]
> Весь код преобразования должен быть на 1С

Нет, на 1с код преобразования писать не надо.
> или использовать локальное приложение?

Надо сделать анализ различных вариантов реализаций. 
Было бы круто, когда есть какая то внешняя компонента или библиотека (обще принятая). 
Этой компоненте передаешь текст, а на выходе получаешь HTML текст, который уже и надо показывать в задаче.

**Comment by BlizD** [comment]
https://github.com/evilstreak/markdown-js/blob/master/README.md
Вот есть парсер на javascript

**Comment by nixel2007** [comment]
@kuntashov начинал пилить маркдаун парсер на односкрипте. не знаю, закончил ли

**Comment by kuntashov** [comment]
@nixel2007 к сожалению, пока не удалось найти время доделать
