### ISSUE TITLE
При создании группы в справочнике "Спринты" ошибка "Реквизит недоступен для группы"

### ISSUE THREAD

**Issue by BlizD** [BlizD/Tasks#150]
При создании группы в справочнике "Спринты" ошибка "Реквизит недоступен для группы"
![image](https://user-images.githubusercontent.com/10989306/51308346-f6193b80-1a52-11e9-8fd7-d80684d124a7.png)

**Comment by 79vlad** [comment]
Добрый день.
Исправление в [cf](https://drive.google.com/open?id=1VIrveXfAAiSInZHnkSFWEAoc22m9ZFnh)

**Comment by BlizD** [comment]
Спасибо. Перенесу
