### ISSUE TITLE
Доработка: Если разработчик отправил письмо (для регистрации новой задачи) - то он автоматически становится исполнителем

### ISSUE THREAD

**Issue by 79vlad** [BlizD/Tasks#156]
Добрый день.
Возникла необходимость доработать свою программу, т.к. исполнители часто пересылаю входящие письма в задачник, чтобы зарегистрировать новую задачу, которой они будут заниматься. 

В [cf](https://drive.google.com/open?id=1aKzeLFwuRaNF5F7RVURFuJ2lE1TSBpdT) реализован механизм, который позволяет автоматически назначать исполнителем новой задачи, если заказчик (отправитель письма) является одновременно и пользователем ИБ.

Для того, чтобы механизм сработал - необходимо, чтобы у пользователя была включена настройка "Автоматически становиться исполнителем новой задачи, если автор входящего письма"

![image](https://user-images.githubusercontent.com/38312005/52472841-04afca00-2b9d-11e9-9397-fd3e999d133b.png)

**Также в данной доработке присутствует исправление по отправке писем** (Документ.ЭлектронноеПисьмоИсходящее.МодульОбъекта) : при программном формировании исходящего письма не было проверки на то, что в учетной записи почты установлен запрет на отправку писем и соответственно письма пытались отправиться через эту учетную запись.

**Comment by BlizD** [comment]
Спасибо добавлю

**Comment by BlizD** [comment]
А как связывается заказчик и пользователь?

**Comment by 79vlad** [comment]
Сопоставление заказчика с пользователем происходит по e-mail (написал экспортную функцию поиска пользователя по e-mail (аналог функции поиска заказчика при парсинг нового письма)

**Comment by BlizD** [comment]
:+1:

**Comment by BlizD** [comment]
Закинул изменения. 
Присваивание статуса убрал на бэклог. 
Это необходимо делать через отдельную настройку.

**Comment by 79vlad** [comment]
Спасибо. (Забыл про присваивание статуса сказать - это сугубо наша доработка была)
