### ISSUE TITLE
Ошибка при создании задачи из канбан доски если отбор групповой

### ISSUE THREAD

**Issue by BlizD** [BlizD/Tasks#157]
>Ksu Seenka:
добрый день)
если для канбан доски установить отбор в группе, то при попытке добавить задачу на самой доске через правую кнопку мыши "Добавить" вываливается ошибка

**Comment by BlizD** [comment]
![image](https://user-images.githubusercontent.com/10989306/52531005-bf67d580-2d1f-11e9-9e12-7d4ba57103af.png)
![image](https://user-images.githubusercontent.com/10989306/52531007-c393f300-2d1f-11e9-86d3-776f417f9e97.png)

**Comment by BlizD** [comment]
Ошибочно указал коммит к этой задаче

**Comment by 7OH** [comment]
Решение простое - сорри, что не конфой и не через гит - никак не вникну.
В форме обработки добавить 3 строки, групповые условия лучше не разбирать вообще.
`&НаКлиенте
Процедура ДобавитьНовуюЗадачу(Элемент)
	пСтатус = Элемент.ОтборСтрок.Статус;
	ПараметрыНовойЗадачи = Новый Структура();
	ПараметрыНовойЗадачи.Вставить("Статус",пСтатус);
	ЭлементыОтбора = КомпоновщикНастроекКомпоновкиДанных.Настройки.Отбор.Элементы;
	Для каждого ЭлементОтбора из ЭлементыОтбора цикл
		Если НЕ ЭлементОтбора.Использование Тогда
			Продолжить;
		Конецесли;
		//Павлюков - решение
		Если Не ТипЗнч(ЭлементОтбора) =  Тип("ЭлементОтбораКомпоновкиДанных") Тогда
			Продолжить;
		КонецЕсли;`

**Comment by BlizD** [comment]
@7OH Семен все таки можно хотя бы cf файл
