### ISSUE TITLE
Работа телеграмм уведомлений через прокси

### ISSUE THREAD

**Issue by BlizD** [BlizD/Tasks#158]
>@LakhnovAlexander Работа телеграмм уведомлений через Прокси

>1.	+РС узПроксиСерверы
>2.	+Обработка узРаботаСТелеграмм
>3.	Спр. узКонстанты 
>3.1.	+Элемент ТелеграмMaxMessangeID

>На форме списка РС Прокси серверы заполнить настройки по умолчанию:

**Comment by capitoshko** [comment]
Если перетаскиваю задачу на канбан доске, то при отправке в телеграмм без использования прокси, возникает ошибка

![default](https://user-images.githubusercontent.com/25638430/52593299-45d00480-2e51-11e9-8b35-49a7ac29eef6.png)

**Comment by 79vlad** [comment]
> Если перетаскиваю задачу на канбан доске, то при отправке в телеграмм без использования прокси, возникает ошибка. Нет в струкутре такого свойства в структуре - МассивПользователейКому


Добрый день.
Проверьте актуальность версии и корректность установки обновлений: в версии 1.0.4.22 - данный модуль выглядит иначе:
![image](https://user-images.githubusercontent.com/38312005/52659468-01527080-2f06-11e9-9c0f-d9a5691777a2.png)

**Comment by BlizD** [comment]
@capitoshko @79vlad Поправил ошибку.
