### ISSUE TITLE
Отправка через телеграмм доработка

### ISSUE THREAD

**Issue by BlizD** [BlizD/Tasks#174]
>Крапивин Илья Для отправки сообщений в тегеграмм. Сама обработка узРаботаСТелеграм работает (когда настроишь прокси-серверы). Кстати, если обработка запускается вручную, было бы неплохо после кнопки отправки сообщений сделать вывод информации – отправилось, не отправилось.. в чем проблема. А то жмешь на кнопку – и тишина. Что то пишется в журнал регистрации, но туда тоже надо догадаться посмотреть.
Так вот, для того, чтобы отправка работала из задач, пришлось в процедуре ОтправитьСообщениеTelegram заменить строку 
ИДПользователяТелеграм = Пользователь.узИДПользователяТелеграмм;
На
Попытка
ИДПользователяТелеграм = Пользователь.узИДПользователяТелеграмм;
Исключение
ИДПользователяТелеграм = Пользователь.Пользователь.узИДПользователяТелеграмм;
КонецПопытки;

**Comment by BlizD** [comment]
>Антон, Забыл еще написать.
Вот как выглядят сообщения в Телеграме:
Добрый%20день.
Вам%20была%20назначена%20задача%3A%20Тестовая%20задача%201
Номер%20задачи%3A%20%233
Реквизиты%20задачи%3A
-%20Исполнитель%20%5BКрапивин%5D
-%20Статус%20%5BЗарегистрирована%5D
-%20Важность%20%5BОбычная%5D
-%20ОсновнаяЗадача%20%5BСопровождение%20БП%5D
Видимо, что то не то с пробелами
Илья

**Comment by CptAFK** [comment]
Там структура, забыл поменять разработчик, там правильнее наверно
Попытка
ИДПользователяТелеграм = Пользователь.узИДПользователяТелеграмм;
Исключение
ИДПользователяТелеграм = Пользователь.ИД;
КонецПопытки;

**Comment by CptAFK** [comment]
узРаботаСТелеграм.Форма

**Comment by CptAFK** [comment]
Обработка.узРаботаСТлеграм.Форма
Обработка.узРаботаСТлеграм.Модуль
ОбщийМодуль.узРаботаСТелеграммСервер

[CF (Яндекс.Диск)](https://yadi.sk/d/wdgrI4RuPmkyag)

**Comment by BlizD** [comment]
@CptAFK 

Залил изменения.

Добавил константу "ТелеграммИспользоватьЗаменуСимволовВДругуюКодировку", т.к. для пользователей Украины, это работает корректно. По умолчанию она будет заполнена как Истина.

**Comment by BlizD** [comment]
Обновил cf файл с дев ветки https://github.com/BlizD/Tasks/issues/123

**Comment by 79vlad** [comment]
Я не смотрел в цф-нике, но могу предположить, что проблема "%" связана с тем, что при отправке сообщений через подписку - явно указано, что передаваемый текст является форматированным , а не просто текст, тогда телега самостоятельно его переабразовывает. Также, если не заменить зарезервированные символы, то при передаче их строке http-запроса будет ошибка.
В обработке отправки сообщений на телегу, пропущен параметр, который отвечает за признак форматированного текста и сообщение отображается "как есть" без доп обработки на стороне телеги.
На следующей неделе гляну более подробно в самой конфигурации и отпишусь

**Comment by BlizD** [comment]
@79vlad спасибо. Буду ждать.

**Comment by 79vlad** [comment]
@CptAFK 

> > Антон, Забыл еще написать.
> > Вот как выглядят сообщения в Телеграме:
> > Добрый%20день.
> > Вам%20была%20назначена%20задача%3A%20Тестовая%20задача%201
> > Номер%20задачи%3A%20%233
> > Реквизиты%20задачи%3A
> > -%20Исполнитель%20%5BКрапивин%5D
> > -%20Статус%20%5BЗарегистрирована%5D
> > -%20Важность%20%5BОбычная%5D
> > -%20ОсновнаяЗадача%20%5BСопровождение%20БП%5D
> > Видимо, что то не то с пробелами
> > Илья

Посмотрел код в релизе **1.0.4.030** - и я оказался прав: в обработке "узРаботаСТелеграм", в процедуре модуля объекта "ОтправитьСообщениеTelegram", не заданы доп. параметры. 
В этой процедуре, **необходимо добавить две строчки и все должно заработать** без изменения других модулей  (правда проверить не могу, т.к. не использую прокси - **проверьте кто использует прокси**).
Было:
```
Структура = Новый Соответствие;
Структура.Вставить("chat_id",Формат(ИДПользователяТелеграм, "ЧГ="));
Структура.Вставить("text", ТекстСообщения);
Массив_reply_markup = Новый Массив;
```


Должно быть:
```
Структура = Новый Соответствие;
Структура.Вставить("chat_id",Формат(ИДПользователяТелеграм, "ЧГ="));
Структура.Вставить("text", ТекстСообщения);		

// ++ 79Vlad 20.06.2019 #174  \\
Структура.Вставить("parse_mode","Markdown");
Структура.Вставить("disable_web_page_preview","true");
// -- 79Vlad 20.06.2019 #174		

Массив_reply_markup = Новый Массив;
```

PS @BlizD  пока оформить этот патч в виде dev.cf - не могу, т.к. работаю над задачей по RLS :)

**Comment by 79vlad** [comment]
> > Крапивин Илья  
....
Кстати, если обработка запускается вручную, было бы неплохо после кнопки отправки сообщений сделать вывод информации – отправилось, не отправилось.. в чем проблема. А то жмешь на кнопку – и тишина. Что то пишется в журнал регистрации, но туда тоже надо догадаться посмотреть.

Внес изменения:
1) в процедуру обработки (добавил входной параметр и добавил вывод сообщения о результате отправки):

```
Процедура ОтправитьСообщениеTelegram(ТекстСообщения, МассивПользователейДляОтправки, УведомлятьОРезультате = Ложь) Экспорт
	
	Если МассивПользователейДляОтправки.Количество() = 0 Тогда
		
		// ++ 79Vlad 20.06.2019 #174  \\
		Если УведомлятьОРезультате Тогда
			Сообщение = Новый СообщениеПользователю;
			Сообщение.Текст = "Сообщение не отправлено, т.к. не указан получатель.";
			Сообщение.Сообщить();
		КонецЕсли; 
		// -- 79Vlad 20.06.2019 #174
		
		
		Возврат;
	КонецЕсли;
	
	НастройкиДляРаботыСТелеграм = ПолучитьНастройкиДляРаботыСТелеграм();
	Если НастройкиДляРаботыСТелеграм.ВсеНастройкиПолучены = Ложь Тогда
		// ++ 79Vlad 20.06.2019 #174  \\
		Если УведомлятьОРезультате Тогда
			Сообщение = Новый СообщениеПользователю;
			Сообщение.Текст = "Сообщение не отправлено, т.к. не смогли получить настройки телеграм.";
			Сообщение.Сообщить();
		КонецЕсли; 
		// -- 79Vlad 20.06.2019 #174
		Возврат;
	КонецЕсли;	

	Для Каждого Пользователь Из МассивПользователейДляОтправки Цикл
		
		ИДПользователяТелеграм = Пользователь.узИДПользователяТелеграмм;
		Если Не ЗначениеЗаполнено(ИДПользователяТелеграм) Тогда
			Продолжить;
		КонецЕсли;
		
		//ТекстСообщения = СтрЗаменить(ТекстСообщения, "#", "");
	    СообщениеОтправлено = Ложь;

		//		Данные = 
		//		"{
		//|""chat_id"":"""+Формат(Выборка.ИДПользователяТелеграмм, "ЧГ=")+""",
		//|""text"":""Текст"",
		//|""reply_markup"": {
		//|    ""inline_keyboard"": [
		//|    [{
		//|  ""text"": ""ОбъектСогласования"",
		//|  ""url"":""http://192.168.13.130/BPS/ru_RU/#e1cib/data/Справочник.бпсПредметыСогласований?ref=838318dbf213445c11e8e41681645d42""
		//|     }]
		//|]
		//|}
		//|} ";

		Структура = Новый Соответствие;
		Структура.Вставить("chat_id",Формат(ИДПользователяТелеграм, "ЧГ="));
		Структура.Вставить("text", ТекстСообщения);
		
		// ++ 79Vlad 20.06.2019 #174  \\
		Структура.Вставить("parse_mode","Markdown");
		Структура.Вставить("disable_web_page_preview","true");
		// -- 79Vlad 20.06.2019 #174
		
		Массив_reply_markup = Новый Массив;
		
		//Пример создания конпки в телеграм
		//Если ЗначениеЗаполнено(Выборка.ОбъектБД)
		//	И ЗначениеЗаполнено(АдресПубликации) Тогда
		//	
		//	Структура_inline_keyboard = Новый Структура;
		//	Структура_inline_keyboard.Вставить("text", Строка(Выборка.ОбъектБД));
		//	Структура_inline_keyboard.Вставить("url", АдресПубликации + "#" + ПолучитьНавигационнуюСсылку(Выборка.ОбъектБД));
		//                      
		//	Массив_reply_markup.Добавить(Структура_inline_keyboard);
		//КонецЕсли;	
		//Массив_inline_keyboard = Новый Массив;
		//Массив_inline_keyboard.Добавить(Массив_reply_markup);
		//
		//Структура_reply_markup = Новый Структура;
		//Структура_reply_markup.Вставить("inline_keyboard",Массив_inline_keyboard);
		//
		//Структура.Вставить("reply_markup", Структура_reply_markup);
		
		ПараметрыЗаписиJSON = Новый ПараметрыЗаписиJSON;
		ЗаписьJSON = Новый ЗаписьJSON;
		ЗаписьJSON.УстановитьСтроку(ПараметрыЗаписиJSON);
		ЗаписатьJSON(ЗаписьJSON, Структура);
		Данные = ЗаписьJSON.Закрыть();
					
		Ресурс = "bot" + НастройкиДляРаботыСТелеграм.ТокенТелеграмБота + "/sendMessage";
		ЗапросHTTP = Новый HTTPЗапрос(Ресурс);
		ЗапросHTTP.Заголовки.Вставить("Content-type", "application/json");
		ЗапросHTTP.УстановитьТелоИзСтроки(Данные);

		Ответ = Неопределено;
		ВыполнитьЗапросHTTP_Telegram(Ответ, 
									ЗапросHTTP, 
									НастройкиДляРаботыСТелеграм.МассивНастроекПроксиСерверов, 
									НастройкиДляРаботыСТелеграм.НомерТекущейНастройкиПрокси);
		Если Ответ = Неопределено 
			Или Ответ.КодСостояния < 200 
			Или Ответ.КодСостояния >= 300 Тогда
		
			ЗаписьЖурналаРегистрации("Телеграм.ОтправкаСообщений", УровеньЖурналаРегистрации.Ошибка,,
				, "Не смогли отправить сообщение телеграм пользователю [" + Пользователь.узИДПользователяТелеграмм+"]");
		Иначе
			СообщениеОтправлено = Истина;		
		КонецЕсли;
		
		// ++ 79Vlad 20.06.2019 #174  \\
		Если УведомлятьОРезультате Тогда
			ТекстУведомления = "Сообщение удачно отправлено" ;
			Если НЕ СообщениеОтправлено Тогда
				ТекстУведомления = "Не смогли отправить сообщение телеграм пользователю [" + Пользователь.узИДПользователяТелеграмм+"]. Подробнее смотрите в журнале регистрации."
			КонецЕсли; 
			Сообщение = Новый СообщениеПользователю;
			Сообщение.Текст = ТекстУведомления;
			Сообщение.Сообщить();
		КонецЕсли; 
		// -- 79Vlad 20.06.2019 #174
		
		
	КонецЦикла;

КонецПроцедуры

```
2) В модуле форме:
```

&НаСервере
Процедура ОтправитьСообщениеНаСервере()
	
	МассивПользователейДляОтправки = Новый Массив;
	МассивПользователейДляОтправки.Добавить(ЭтотОбъект.ПользовательДляОтправки);
	пОбъект = РеквизитФормыВЗначение("Объект");
	
	// ++ 79Vlad 20.06.2019 #174  \\
	//пОбъект.ОтправитьСообщениеTelegram(ЭтотОбъект.ТескстСообщенияДляОтправки, МассивПользователейДляОтправки);
	пОбъект.ОтправитьСообщениеTelegram(ЭтотОбъект.ТескстСообщенияДляОтправки, МассивПользователейДляОтправки,Истина);
	// -- 79Vlad 20.06.2019 #174
	
	
	
КонецПроцедуры

```
PS @BlizD  опять извини, что текстом патч выкладываю

**Comment by BlizD** [comment]
@79vlad спасибо залил твои изменения.

**Comment by RomanUpworksTeam** [comment]
Всем привет. Сталкнулся с проблемой:
В конфигурации жестко зашито использование proxy  (обработка "работа с телеграм")
Прилагаю исправленный CF
https://drive.google.com/file/d/1hMuu2F4bSdAUi-t9rWbvKfhiI0vUKYOj/view?usp=drivesdk
