### ISSUE TITLE
Подключить вопросы-ответы к уведомлению 

### ISSUE THREAD

**Issue by BlizD** [BlizD/Tasks#179]
>Виктория Шевченко: Добрый день, @xBlizD  Антон! Скажите, пожалуйста, можно ли подключить справочник Вопросы-Ответы к уведомлению, чтобы другой пользователь мог видеть, что ему пришёл вопрос. Чтобы не заходить на вкладку, а получать уведомление сразу на "колокольчик".

**Comment by 7OH** [comment]
Тоже уже месяц интересовал этот вопрос.
Если ещё нет наработок - могу взять в работу.

**Comment by BlizD** [comment]
Семен, нет нету.

**Comment by BlizD** [comment]
>@Serg 050720: 2. Есть в задачах отличный сервис Вопросы-Ответы. Но как я понял при создания вопроса никаких уведомлений никому не формируется. И как тот кому задан вопрос узнает об этом? Аналогично с ответом. Когда появляется ответ никаких уведомлений не формируется. Это я что-то не так настроил или так и задумано?

**Comment by serg33rus** [comment]
Я так понял аж с 19 года так никто и не сделал? Если нет, то готов попробовать реализовать уведомления о вопросах и ответах.

**Comment by BlizD** [comment]
Да, никто не сделал.

На всякий случай напомню алгоритм доработки описан в задаче #215

**Comment by BlizD** [comment]
Потом надо добавить еще в вики новую информацию 
https://github.com/BlizD/Tasks/wiki/Уведомления

**Comment by serg33rus** [comment]
Сделал отправку уведомлений на почту двух событий "Создан вопрос" и "Вопрос закрыт".
В модуле объекта узВопросыОтветы изменилась процедура ПриЗаписи. И добавилось три новых процедуры; ОтправитьУведомлениеНаПочту, ОтправитьУведомлениеНаПочтуВопрос, ОтправитьУведомлениеНаПочтуОтвет.

Уведомления о создании вопроса отправляются Исполнителю и Кому вопрос направлен.
Уведомления о Закрытии вопроса отправляются Исполнителю и Автору вопроса.
При формировании уведомлений проверяются настройки пользователей.

Наблюдателям уведомления о Вопросах не отправляются. Чего-то я подумал, что им это не надо. Если надо, доделаю.

Уведомления отправляются только на мыло. В Телеграмм делать не стал. По мне так рассылку в Телеграмм надо вообще в расширение вытащить. Если надо, доделаю. 

Изменения делал в конфе dev_Tasks050720_1513.

Ссылка на .cf https://drive.google.com/file/d/1Y4gaw63RhADMSbMBfvzLeEDgPkhI8vu2/view?usp=sharing

**Comment by BlizD** [comment]
Спасибо. Залью на выходных

**Comment by serg33rus** [comment]
Себе сделал уже и наткнулся на один момент. Есть два события: Добавлен вопрос, Закрыт вопрос. События Дан ответ нет. На самом деле не очень хорошо. Когда тот кто отвечает формулирует ответ, он не всегда может решить закрыт вопрос или нет. А если даже и может, то ему надо сделать два движения, написать ответ, а потом дернуть флажок. Некритично конечно, но ... Немного неровно получилось, как мне кажется.

**Comment by serg33rus** [comment]
И еще момент. Абсолютно некритичный, но лучше поправить. При добавлении комментария в теме письма пишет "Добален комментарий". И в теле письма тоже. Мелочь, но глаз режет :-).

**Comment by BlizD** [comment]
@serg33rus Залил изменения. Спасибо.
Выполнил рефакторинг кода, чтобы убрать дублирование.
Плюс добавил новое событие "Изменен ответ".

Поправил вики https://github.com/BlizD/Tasks/wiki/Уведомления

Сейчас отправляется вот так:

| Вид события| Отправка исполнителю| Отправка наблюдателям | Отправка старому исполнителю|  Отправка заказчику| Автор вопроса| Кто может решить вопрос|  
| ------------- |:-------------:| :-------------:|:-------------:|:-------------:|:-------------:|:-------------:|
| Добавлен вопрос| V | X |X|X|V|V|
| Изменен ответ| V | X |X|X|V|V|
| Вопрос закрыт| V | X |X|X|V|V|

**Comment by BlizD** [comment]
По хорошему еще необходимо событие "Изменен вопрос"

**Comment by serg33rus** [comment]
Красотища стала. Еще чуток функционала прибавилось.

**Comment by BlizD** [comment]
Добавил еще событие "Изменен вопрос".
Добавил отправку наблюдателям по задаче.
Теперь вот так уведомления отправляются:

| Вид события| Отправка исполнителю| Отправка наблюдателям | Отправка старому исполнителю|  Отправка заказчику| Автор вопроса| Кто может решить вопрос|  
| ------------- |:-------------:| :-------------:|:-------------:|:-------------:|:-------------:|:-------------:|
| Добавлен вопрос| V | V |X|X|V|V|
| Изменен вопрос| V | V |X|X|V|V|
| Изменен ответ| V | V |X|X|V|V|
| Вопрос закрыт| V | V |X|X|V|V|
