### ISSUE TITLE
Открытие форм при начале работы

### ISSUE THREAD

**Issue by 7OH** [BlizD/Tasks#183]
Релиз 1.0.4.030
Версия платформы - не важна.
---
Если при старте системы открывается модальное окно (например при запуске базы на другом компе) - открываемые окна открываются так же отдельными. Независимо от настройки режима окна самой формы или указания параметра при программном открытии формы.
--
Сейчас формы открываются только с учетом возможного обновления.
Необходимо адаптировать код открытия форм на стандарты БСП.

**Comment by 7OH** [comment]
В фиксе для 038, что скидывал, исправлено не до конца.
Переделал полностью - убрал код из модуля приложения и перенёс в узОбщийМодульКлиент.
Также в "ОбщегоНазначенияКлиентПереопределяемый.ПослеНачалаРаботыСистемы" добавлен вызов такой же функции из узОбщийМодульКлиент, которая и запустит формы.
И запустит только после вызова всех других стартовых процедур, аля обновление или вопрос о блокировке базы.
В файле исправления сразу по 2-м задачам (196 и 183).
[https://drive.google.com/open?id=1s0lkeVoNxcisgu7lLyE_Y1s3NlqGi5uX](url)

**Comment by BlizD** [comment]
Спасибо. Залью

**Comment by BlizD** [comment]
@7OH 
Семен, спасибо, залил изменения.

Пару моментов.
1. Пожалуйста при доработке бери всегда последний CF из задачи #123 т.к. доработки не только от тебя приходят и уже много расхождений показывает.
1. Указывай пожалуйста комментарий в формате, т.е. любое изменение в любом модуле необходимо вот так комментировать.
```
//+ #1014 Иванов А.Б. 2016-04-06
//Старый код
....НовыйКод....
//- #1014 Иванов А.Б. 2016-04-06
```

**Comment by 7OH** [comment]
хорошо. за 123 запомню. комментарии старался, видимо не до конца.
