### ISSUE TITLE
Проблемы с отправкой почты

### ISSUE THREAD

**Issue by serg33rus** [BlizD/Tasks#186]
Есть проблема. При создании письма оно отказывается отправляться с формулировкой "Выбранная учетная запись недоступна для отправки писем". Это системная учетная запись. Но если это письмо сохранить и потом войти в него из Взаимодействия, то оно отправляется.
[Скрин ошибки](https://drive.google.com/open?id=1gDOn9ZdR7tmDew7doXQHM4iDeVlSWCbM)

**Comment by BlizD** [comment]
Пришлите скрин с настройками этой учетной записи. Возможно там не указан признак "при отправке"

**Comment by serg33rus** [comment]
Высылаю [скрин](https://drive.google.com/open?id=1ZOt7tbXqAQFF_BNsWnt6SOOqNx4w8pvl) с настройками. Проверка настроек [проходит](https://drive.google.com/open?id=1daiq_ZfbdkXCUYp7FI371ZrWuo1xThZI). 
Проблема у меня повторяется. Пробовал сначала записать письмо, а потом отправлять, не помогает. А вот если потом из Взаимодействия войти в письмо и нажать отправить, отправляется. Сначала предупреждает, что письмо не сохраниться, но потом по кнопке Отправить в окне с предупреждением отправляет.

**Comment by serg33rus** [comment]
Разобрался. Если крыжик не стоит "Использовать для отправки уведомлений заказчикам", то возникает такой эффект. Если крыжик поставить, то почта отправляется без вопросов.  Видимо ручное создание письма считается письмом контрагенту. Что в общем-то резонно, поскольку там можно любое мыло прописать. Вопрос снят. Спасибо.
