### ISSUE TITLE
??? Вывод на доску задач помеченных на удаление

### ISSUE THREAD

**Issue by serg33rus** [BlizD/Tasks#189]
В списке задач эту пометку видно. а вот на доске задача выводится как обычно. Конечно же потом она физически удалиться и все будет хорошо. Но если задачу создали ошибочно, то она еще какое-то время болтается на доске. И в настройках отбора не нашел пометку на удаление. Это так и задумано или не там искал?

**Comment by BlizD** [comment]
В настройках отбора канбан доски должно быть.
Чуть позже посмотрю сам.

**Comment by BlizD** [comment]
В канбан доске есть отбор по пометке удаления.
Задача.ПометкаУдаления = Нет

![image](https://user-images.githubusercontent.com/10989306/75606571-1db84f80-5aff-11ea-92a4-a60b3c2609aa.png)

**Comment by serg33rus** [comment]
Да, такой вариант срабатывает. Спасибо.
