### ISSUE TITLE
Нумерация релиза

### ISSUE THREAD

**Issue by BUDIVAL** [BlizD/Tasks#19]
Насколько я понимаю четвертый порядок цифр в номере релиза х.х.х.ххх должен увеличиваться при незначительных изменениях и исправлениях ошибок текущего. При добавлении нового функционала правильней увеличивать третий порядок цифр.

Если есть кто знает лучше, подскажите.

**Comment by BlizD** [comment]
Да ты прав. Но все же пока буду нумеровать последнюю цифру. Вторую цифру менял когда сделал загрузку изменений из хранилища. Вот когда будет динамическая канбан доска тоже поменяю.

**Comment by BUDIVAL** [comment]
Тебе видней.
