### ISSUE TITLE
Отправка уведомления

### ISSUE THREAD

**Issue by serg33rus** [BlizD/Tasks#190]
Сейчас при рассылке уведомлений проверяется условие узНеОтправлятьУведомленияНаПочту.
И если оно истино, то Возврат. 
И получается что рассылка в телеграмм или, в дальнейшем, в другие мессенджеры возможна только параллельно рассылке в почту. 
Было бы здорово иметь возможность явно указывать куда рассылать сообщения. Кому-то в почту, кому-то в телеграмм, кому-то и туда и туда. 
Там исправление элементарное. Надо узОбщийМодульСервер.ОтправитьПисьмо выполнять по условию НЕ узНеОтправлятьУведомленияНаПочту.
и тогда на почту не пойдет, а на телеграмм своя проверка есть. 
Там исправлений на три копейки. Я просто если честно никогда с гитхабом дела не имел, поэтому боюсь налажать.

**Comment by d-hurricane** [comment]
Вы можете отправить автору cf-файл с исправлением.

**Comment by serg33rus** [comment]
Тогда хотелось бы в рамках этого исправления добавить еще одно. У меня некоторые пользователи просят отправлять им уведомления и об их действиях. Один из них просто параноик и предпочитает хранить свой архив. А вот второй работает на несколько проектов и у него есть свой задачник. И ему удобнее получать письма, чтобы вести его. 
Там тоже исправления несложные, но требуется залезть в метаданные. В справочнике пользователи надо будет внести еще одно поле "РассылатьУведомлениеСебе". Для большинства пользователей не измениться ничего. Но некоторые этот признак установят и буду получать уведомления и о своих действиях. 
Хотелось бы услышать мнение Антона. Если он даст добро, то я готов взяться это сделать. Если нет, то нет и суда нет.

**Comment by BlizD** [comment]
Отвечу на выходных

**Comment by BlizD** [comment]
@serg33rus 
Привет.
Да, можете добавить. 
При этом для новых реквизитов ставим префикс "уз", таким образом будет реквизит "узОтправлятьУведомленияОДействияхПользователяЕмуНаПочту" Булево

И используйте следующий алгоритм:

## Вариант доработки через CF файл (самое простое)

**Алгоритм:**

1. Создайте [задачу](https://github.com/BlizD/Tasks/issues) и опишите, Вашу, доработку;
1. Если по задаче необходимы новые метаданные, то необходимо написать ТЗ на это и отправить в задачу ([пример ТЗ](https://github.com/BlizD/Tasks/files/2544687/117_._031118.docx))
1. Возьмите последний CF из дев ветки в задаче [#123](https://github.com/BlizD/Tasks/issues/123)
1. Выполните доработку в этом CF;
1. Укажите в задаче список измененных объектов метаданных;
1. Прикрепите к созданной задачи Ваш CF.
1. Спасибо за Ваш, вклад в разработку;

Код необходимо обрамлять в следующем формате: 
```
//+ #1014 Иванов А.Б. 2016-04-06
//Старый код
....НовыйКод....
//- #1014 Иванов А.Б. 2016-04-06
```

**Comment by BlizD** [comment]
В данном случае тз отдельно писать не надо. Так как имя реквизита обсудили как будет называться.

**Comment by serg33rus** [comment]
Изменена функциональность.
Было: при установленном флаге "Не получать уведомления на почту" уведомления не посылалось вообще.
Стало: Флаг "Не получать уведомление на почту" действует только на почту. На телеграмм действие флага не распространяется.
Было: уведомления о своих действиях не рассылались.
Стало: уведомления о своих действиях рассылаются или нет в зависимости от флага "Отправлять уведомления о собственных действиях" в настройках пользователя.

В конфигурации:
-Добавлен реквизит справочника Пользователи узОтправлятьУведомленияОДействияхПользователяЕмуНаПочту, тип Булево.
-в модуле ОбщийМодуль.узОбщийМодульСервер.Модуль добавлен вывод на форму реквизита узОтправлятьУведомленияОДействияхПользователяЕмуНаПочту
-в модуле объекта Справочник.узЗадачи исправлены процедуры ОтправитьУведомлениеНаПочтуИсполнителю, ОтправитьУведомлениеНаПочтуСтаромуИсполнителю, ПолучитьМассивНаблюдателей.

Исправления помечены комментарием //+ #190 SZ 16.03.2020

Протестировал. Вроде глюков не вылезло, все работает как должно.

Файл прицепить к сообщению не сумел :-(. Ругается что cf нельзя и не больше 10 мегабайт. Выкладываю файл конфигурации на диск google https://drive.google.com/open?id=1x-cOo8AYwUDRw5tdnIA3gSZ4QZB2DIcP

**Comment by BlizD** [comment]
Спасибо. Посмотрю на выходных

**Comment by BlizD** [comment]
@serg33rus - Спасибо. Залил изменения. Немного скорректировал код можно посмотреть как стало в [f9a9c75a](https://github.com/BlizD/Tasks/commit/f9a9c75aad5d3a421bc41a1c8656543580f1db3f)
Обновил CF файл в дев ветке https://github.com/BlizD/Tasks/issues/123
