### ISSUE TITLE
Рассылка уведомлений по аське.

### ISSUE THREAD

**Issue by serg33rus** [BlizD/Tasks#193]
В процессе работы выяснилось, что бухгалтер читает почту утром и вечером. Но исторически так сложилось, что на работе почти у всех стоит аська. Сделал расширение для 38 релиза для рассылки уведомлений в аську. В реальном времени так сказать. Надо чтобы 1С сервер мог достучаться до инета. Этого для работы достаточно. 
Расширение цепляется стандартными средствами из меню "Печатные формы, отчеты и обработки". 
У меня используется в полный рост. Может еще кому надо?

**Comment by serg33rus** [comment]
Ссылка на расширение https://drive.google.com/open?id=1urSPKB7kdda6Mcz-NF14wGgdxmDLIE_Q
Сюда не лезет.

**Comment by BlizD** [comment]
Спасибо.

**Comment by BlizD** [comment]
@serg33rus 
Создай пожалуйста новую задачу назови ее "Расширение: Рассылка уведомлений по ISQ"

В первом сообщении вставь краткое описание. Для какого релиза будет действовать. 

Краткую инструкцию во втором сообщении. 

Позже когда выпущу релиз сделаю ссылку на эту новую задачу. Также выпущу это отдельное расширение.

**Comment by serg33rus** [comment]
@BlizD 
Сделаю. Но вообще там изначально был полноценный бот который крутился фоновым заданием. Умел выполнять команды /tasklist, /task #task, set ИмяПользователя, /notify on, /notify off
Уже из этого бота я выдрал для расширения только уведомления. Бот в расширение не засунуть. Там напряжно с фоновыми заданиями.
