### ISSUE TITLE
Вставка изображения из буфера обмена в описание задач

### ISSUE THREAD

**Issue by BlizD** [BlizD/Tasks#199]
Вставка изображения из буфера обмена в описание задач
Похоже перестала работать.
Релиз 1.0.5.001

Необходимо понять, можно ли это обойти.

**Comment by fishca** [comment]
На 8.3.17 работает в клиент-серверной архитектуре
![image](https://user-images.githubusercontent.com/1484649/80993842-77613100-8e44-11ea-99ea-a8efcba9919f.png)

**Comment by BlizD** [comment]
Спасибо. Проверю у себя

**Comment by BlizD** [comment]
На платформе: 8.3.17.1386 в файловом режиме проблемы нет.
Пока проблема себя проявляет только при использовании платформы: 8.3.16.1063

![image](https://user-images.githubusercontent.com/10989306/81060425-189ac680-8edb-11ea-8f19-b364be88c8b3.png)

**Comment by milanse** [comment]
Работа с буфером обмена 

https://github.com/cpr1c/clipboard_1c

**Comment by BlizD** [comment]
Пример кода вставки картинки из буфер обмена в Поле форматированного документа

https://gist.github.com/BlizD/bb396a4ba64cbc1f18aef4e8fd86c48c

Цель, чтобы было вот так:

![image](https://user-images.githubusercontent.com/10989306/82114764-51eaf600-9767-11ea-847a-9622e2d2c486.png)

**Comment by milanse** [comment]
Может дернуть товарища из публикации, захочет вложиться в проект ?

**Comment by BlizD** [comment]
Маркдаун и сейчас реализован. По остальному отвечу завтра

**Comment by milanse** [comment]
На 8.3.17 работает, подтверждаю. И в форматированный и в HTML документ вставляет все как положено.

**Comment by milanse** [comment]
Добавил компоненту, общий модуль взял [тут](https://github.com/cpr1c/clipboard_1c) и кнопку на форме полноэкранного редактирования документа:

![image](https://user-images.githubusercontent.com/15941393/83955422-78c6b480-a85b-11ea-9006-a31d667cb147.png)

Добавил работу с полноэкранной формой в вопросы и ответы.

cf:
https://drive.google.com/file/d/1X2UvIPc58Ug2Lv1V4l7aMYJkfG7icPhD/view?usp=sharing

**Comment by BlizD** [comment]
Отлично. Спасибо залью на след выходных

**Comment by BlizD** [comment]
@milanse Привет, спасибо залил изменения.

Плюс добавил кнопку в задачи, работа в обычном режиме (не полноэкранном)

![BufferImg](https://user-images.githubusercontent.com/10989306/84590126-81f7e880-ae3c-11ea-88cf-65c7b7094e75.gif)
