### ISSUE TITLE
Переделать канбан доску, чтобы форма генерировалась динамически

### ISSUE THREAD

**Issue by BlizD** [BlizD/Tasks#2]
№5 Переделать канбан доску, чтобы форма генерировалась динамически

**Comment by BUDIVAL** [comment]
Антон, я так понимаю номер задачи "5" - это из вашей базы задач так, что предлагаю их не указывать здесь, ну или изменить формат например все внешние номера задач писать "№5".

**Comment by BUDIVAL** [comment]
Хочу взять эту задачу! Ты уже начинал ее?

**Comment by BlizD** [comment]
> Антон, я так понимаю номер задачи "5" - это из вашей базы задач так, что предлагаю их не указывать здесь, ну или изменить формат например все внешние номера задач писать "№5".

Ок, согласен.

> Хочу взять эту задачу! Ты уже начинал ее?

Нет не начинал.
