### ISSUE TITLE
Убрать блокировку окна владельца при открытии задачи

### ISSUE THREAD

**Issue by BlizD** [BlizD/Tasks#200]
>Некоторые окна элементов открываются в режиме блокировать окно владельца. Особенно для задач это не удобно. Всех устраивает такое поведение?

**Comment by milanse** [comment]
> > Некоторые окна элементов открываются в режиме блокировать окно владельца. Особенно для задач это не удобно. Всех устраивает такое поведение?

Поправил свойства форм элементов, добавил невидимый реквизит Ссылка в формы списков где не было.

https://drive.google.com/file/d/1s1qFxDdFqfiPHdrwGn62gXsCGqRjjY7A/view?usp=sharing

**Comment by BlizD** [comment]
Спасибо. Посмотрю на выходных

**Comment by BlizD** [comment]
@milanse 
Спасибо за доработки, залил изменения.
