### ISSUE TITLE
Реализация RLS 2.0

### ISSUE THREAD

**Issue by d-hurricane** [BlizD/Tasks#201]
Выполнен ряд доработок в рамках подсистемы управления доступом.
- Реализовано ограничение доступа на уровне записей для варианта работы "Производительный" (RLS 2.0). Ранее работал только стандартный вариант ограничений.
- Ограничение по группам доступа задач выполнено по методологии фирмы 1С.
- Исправлены мелкие ошибки.

За основу взята конфигурация dev-ветки версии 1.0.5.001 (dev_Tasks020520_1044.cf). [Скачать](https://yadi.sk/d/EPNHOsCgtijRCQ)

**Comment by d-hurricane** [comment]
### Список изменений

1. Общий модуль **УправлениеДоступомПереопределяемый**
	* ПриЗаполненииВидовДоступа (исправлено описание вида доступа)
	* ПриЗаполненииВидовОграниченийПравОбъектовМетаданных
	* ПриЗаполненииСписковСОграничениемДоступа

1. Переработаны роли **узПользовательОграничениеДоступаЧтение** и **узПользовательОграничениеДоступаИзменение**:
	* Исправлены все ограничения доступа к записям
	* Обновлены шаблоны ограничений

1. Включены новые объекты в **определяемые типы**:
	* ВладелецЗначенийКлючейДоступа
	* ВладелецЗначенийКлючейДоступаДокумент
	* ВладелецЗначенийКлючейДоступаНаборЗаписей
	* ПолеРегистраКлючейДоступаКРегистрам
	
1. В определяемом типе **ЗначениеДоступаОбъект**:
	* удален СправочникОбъект.узГруппыДоступаЗадач
	* добавлен СправочникОбъект.узЗадачи

1. Справочник **ИдентификаторыОбъектовМетаданных**
	* новые предопределенные элементы, ассоциированные с регистрами
	
1. В модули менеджеров следующих объектов добавлена экспортная процедура **ПриЗаполненииОграниченияДоступа**, а также в некоторых случаях добавлены директивы компиляции и области модуля:
	* Справочник.узВопросыОтветы
	* Справочник.узЗадачи
	* Справочник.узЗадачиПрисоединенныеФайлы
	* Документ.узВводФактаПоЗадаче
	* РегистрСведений.узАктивностиПользователей
	* РегистрСведений.узНаблюдателиЗаЗадачами
	* РегистрСведений.узСвязанныеЗадачи
	* РегистрСведений.узСпринтыЗадач
	* РегистрСведений.узСтатусыЗадач
	* РегистрНакопления.узФактПоЗадачам
	
1. В формы объектов внесены изменения, касающиеся обработчиков **ПриЧтенииНаСервере** и **ПослеЗаписиНаСервере**. Если не было обработчиков, они были добавлены. В обработчиках появились вставки для стандартной подсистемы УправлениеДоступом (выделены комментарием). Формы:
	* Справочник.узВопросыОтветы.ФормаЭлемента
	* Справочник.узЗадачи.ФормаЭлемента
	* Документ.узВводФактаПоЗадаче.ФормаДокумента
	* Документ.узВводФактаПоЗадаче.ФормаДокументаВводСЗадачи
	
1. Переработан справочник **узГруппыДоступаЗадач**.

1. Переименован реквизит **ГруппаДоступаЗадач** справочника **узЗадачи**. Новое имя: ГруппаДоступа. В соответствии с новым именем реквизита исправлена процедура "ЗаполнитьЗначенияИзРодителя" формы элемента задачи,
а также запрос формы списка задач.

**Comment by milanse** [comment]
А по каким критериям как вы раздаете пользователям группы доступа задач ? Вот на мой взгляд тут должен использоваться реквизит Проект, от которого почему-то все открещиваются ?

**Comment by d-hurricane** [comment]
Проектировал не я. Ограничения на уровне записей уже были реализованы @7OH. Я своего ничего не привносил, новые ограничения не вводил, а лишь доделал второй вариант работы RLS.

Отвечая на Ваш вопрос могу предположить, что группа доступа задачи по задумке автора конфигурации - это универсальный разрез. Кто-то в качестве групп будет использовать проекты, кто-то команды, кто-то еще что-нибудь.

> Проект, от которого почему-то все открещиваются
Я - нет. :-) Мне также комфортнее оперировать термином "проект", нежели основной задачей на верхнем уровне иерархии. Но тут воля автора конфигурации.

**Comment by BlizD** [comment]
Денис привет. Спасибо за доработки. Посмотрю на выходных и отвечу на вопросы.

**Comment by BlizD** [comment]
Денис, еще раз спасибо за изменения.

Залил их конфигурацию.

Некоторые моменты на будущее:
1. Код необходимо обрамлять в формате. Это требуется по 2 причинам: 
* в типовых модулях необходимо обрамлять код, для облегчения будущего обновления БСП;
* изменения приходят по CF поэтому не всегда ясно, надо ли переносить измененный код или нет.

```
//+ #1014 Иванов А.Б. 2016-04-06
//Старый код
....НовыйКод....
//- #1014 Иванов А.Б. 2016-04-06
```

Добавил обрамление в коде при переносе.

2. Не совсем понял зачем добавлены предопределенные элементы в справочник ИдентификаторыОбъектовМетаданных
На будущее, в типовые объекты не стоит добавлять предопределенные элементы, вместо этого необходимо использовать справочник "узКонстанты" и в него добавлять предопределенные элементы. Для получения значения использовать метод 

`Справочники.узКонстанты.ПолучитьЗначениеКонстанты(....)`

![image](https://user-images.githubusercontent.com/10989306/82724752-11e4bf80-9ce1-11ea-8dea-eac32af2d3d4.png)

3. Подскажи зачем добавлен реквизит "ГруппаДоступа" (тип Справочник.узГруппаДоступаЗадач) в справочник Справочник.узГруппаДоступаЗадач?

Увидел, что он заполняется программно, перед записью ссылкой самого на себя.
Предполагаю, что это требуется для ограничений RLS.

![image](https://user-images.githubusercontent.com/10989306/82724931-22496a00-9ce2-11ea-966c-e43d3a3b75df.png)

**Comment by BlizD** [comment]
@milanse 
>А по каким критериям как вы раздаете пользователям группы доступа задач ? 
>Отвечая на Ваш вопрос могу предположить, что группа доступа задачи по задумке автора конфигурации - это универсальный разрез. Кто-то в качестве групп будет использовать проекты, кто-то команды, кто-то еще что-нибудь.

Да, все верно, так и задумывалось.

>Вот на мой взгляд тут должен использоваться реквизит Проект, от которого почему-то все открещиваются ?
>Я - нет. :-) Мне также комфортнее оперировать термином "проект", нежели основной задачей на верхнем уровне иерархии. Но тут воля автора конфигурации.

Предлагаю добавить новый справочник "узПроекты" и новый реквизит "Проект" в справочник "узЗадачи". Создам на это задачу.

**Comment by BlizD** [comment]
Обновил файл CF #123

**Comment by d-hurricane** [comment]
Комментариями код не обрамлял потому, как половина изменений были сделаны вне текстов модулей. Посчитал, что тебе будет удобнее описание изменений смотреть в одном месте, в задаче. К тому же все изменения - это либо новые, либо полностью переработанные процедуры/функции.

Предопределенные элементы в справочнике идентификаторов объектов метаданных необходимы для RLS. Также, как и реквизит в группе доступа.

**Comment by BlizD** [comment]
Понял, спасибо
