### ISSUE TITLE
Добавить в вопросы и ответы форматированный документ

### ISSUE THREAD

**Issue by BlizD** [BlizD/Tasks#206]
>Вообще хотелось бы все формы с редактированием текста реализовать на форматированном документе или MD разметке. т.е. какой-то общий модуль с возможностью встраивать в описание задачи, вопросы ответы, какие-то. По типу [https://infostart.ru/public/1226053/](https://infostart.ru/public/1226053/) было бы супер

_Originally posted by @milanse in https://github.com/BlizD/Tasks/issues/199#issuecomment-635938974_

**Comment by milanse** [comment]
cf https://drive.google.com/file/d/1PGN0OTupBN-XI4cpMFTGpRe2lBh2eGId/view?usp=sharing

Сделал редактирование через форматированный документ + вставка и открытие номера задачи из текста. Если выключить редактирование, то можно открывать задачу по клику (собственно не только задачу). Возможно можно вставлять и ссылки на объекты в других базах.

![image](https://user-images.githubusercontent.com/15941393/83360919-97c1d400-a38d-11ea-866a-0c06b8733139.png)

Правда даже в 8.3.17 несмотря на установку на реквизит формы форматированного документа "Только просмотр" - редактировать все еще можно... 

Можно так же перепилить общую форму редактирования форматированного документа и запретить редактировать тексты напрямую в форме вопросов, задач и т.д.

**Comment by BlizD** [comment]
Спасибо. Посмотрю на выходных

**Comment by BlizD** [comment]
@milanse Залил изменения, спасибо.

**Comment by BlizD** [comment]
@milanse кстати в для существующих вопросов и ответов как будет показываться? Нужна ли обработка дополнительная?

**Comment by milanse** [comment]
Отдельный реквизит форматировнный текст хранилище значения, если не заполнен при открытии устанавливается старый реквизит с обычным текстом. При записи обычный текст также заполняется, по нему идёт полнотекстовый поиск.

**Comment by BlizD** [comment]
Отлично, спасибо

**Comment by serg33rus** [comment]
Красиво. А когда появится в релизе?

**Comment by BlizD** [comment]
Могу выпустить промежуточный релиз тестовый.

**Comment by serg33rus** [comment]
Наверно неплохо было бы. Изменений уже много накопилось вроде.

**Comment by BlizD** [comment]
> Наверно неплохо было бы. Изменений уже много накопилось вроде.

Выпустил промежуточный релиз добавил в задачу #129
Релиз 1.0.5.004

[1.0.5.004.cf](https://drive.google.com/file/d/1RvH69Bwi8ixNB24J5lUlewTGAKjDG3AG/view?usp=sharing)
[1.0.5.004.cfu](https://drive.google.com/file/d/1UQ-wpE1wTJCwF9nCc-aXlay3DP5xayL9/view?usp=sharing)
