### ISSUE TITLE
При создании письма на основании задачи не заполняется поле кому.

### ISSUE THREAD

**Issue by milanse** [BlizD/Tasks#208]
![image](https://user-images.githubusercontent.com/15941393/83339991-ed3da880-a2db-11ea-8f19-567fcb158ce1.png)

При попытке подобрать адреса нельзя выбрать из справочника контрагентов.

Понятно как поправить, жду cf чтобы накатить изменения.

**Comment by BlizD** [comment]
Поправил CF #123

**Comment by milanse** [comment]
cf в задачке #206

**Comment by BlizD** [comment]
Залил изменения, спасибо.
