### ISSUE TITLE
Кэширование информации о задачах

### ISSUE THREAD

**Issue by d-hurricane** [BlizD/Tasks#212]
Коллеги, в продолжении темы #210 предлагаю ввести служебный регистр сведений, хранящий в разрезе задач следующую информацию в актуальном состоянии:
- количество присоединенных фалов;
- количество связанных входящих писем;
- количество связанных исходящих писем;
- количество файлов, прикрепленных к связанным письмам;
- количество подзадач чек-листа;
- количество выполненных подзадач чек-листа;
- спринт;
- количество задача "вниз" по иерархии (если кому потребуется).

Регистр непериодический. Поля вычисляются в момент записи задачи и связанных с задачами объектов, как то:
- документы электронных писем;
- справочников присоединенных файлов как самих задач, так и электронных писем;
- справочника спринтов.

Основное назначение регистра: использование в списках задач.

**Comment by milanse** [comment]
Придется поприседать, обновление при записи задачи не подходит, надо при записи связанных объектов обновлять.

**Comment by d-hurricane** [comment]
> Придется поприседать, обновление при записи задачи не подходит, надо при записи связанных объектов обновлять.

Поправил описание.

**Comment by BlizD** [comment]
Не против. 
Вопрос только есть ли потребность в такой статистической информации. 
 Возможно цель регистра улучшить производительность канбан доски, да?

**Comment by BlizD** [comment]
Еще можно в этот регистр доплатить поля: 
* ДатаПоследнегоВходящегоПисьма (ДатаВремя)
* ДатаПоследнегоИсходящегоПисьма (ДатаВремя)

**Comment by BlizD** [comment]
Правильно ли понимаю что будет одно измерение "Задача"?

**Comment by BlizD** [comment]
Поидее еще нужен регламент, который обновляет сведения в регистре.

**Comment by BlizD** [comment]
Предлагаю назвать регистр "узДополнительныеСведенияПоЗадачам"

**Comment by d-hurricane** [comment]
Да, для канбан-доски. Только предалагаю таки обновлять информацию сразу, а не регламентным заданием. И если нужно больше информации, касающейся почты, то лучше тогда разбить поля на 2 различных регистра сведений.
Да, измерение одно.

**Comment by milanse** [comment]
> Да, для канбан-доски. Только предалагаю таки обновлять информацию сразу, а не регламентным заданием. И если нужно больше информации, касающейся почты, то лучше тогда разбить поля на 2 различных регистра сведений.
> Да, измерение одно.

Я так понимаю регистр насилие заметок по предмету не входит в состав типовой бсп, это уже рекомендация по внедрению, можно туда все поля добавь , ну или посмотреть рекомендации по его разработке, в нашем случае заметка - это и письма и вопросы и пометки. Можно сразу сделать с картинками

**Comment by d-hurricane** [comment]
Да, кстати, можно и туда. Только хорошо бы таки переименовать его, дабы название суть отражала.

**Comment by milanse** [comment]
> Да, кстати, можно и туда. Только хорошо бы таки переименовать его, дабы название суть отражала.

Это да.

**Comment by BlizD** [comment]
@d-hurricane можно ли сделать и регламентом и сразу? Просто хочется чтобы обновление информации не влияло на стабильность и производительность работы. Если будет регистр узОбновлениеДопИнформацииПоЗадаче то сделать запись в него легко и просто. А обновлять уже по этому регистру или сразу или регламентом.

**Comment by d-hurricane** [comment]
@BlizD, а зачем регламент таки? Правильно ли я понимаю, что ты не хочешь, дабы ошибки сбора статистики влияли на транзакцию записи задач, писем, файлов и прочего?

**Comment by milanse** [comment]
> @d-hurricane можно ли сделать и регламентом и сразу? Просто хочется чтобы обновление информации не влияло на стабильность и производительность работы. Если будет регистр узОбновлениеДопИнформацииПоЗадаче то сделать запись в него легко и просто. А обновлять уже по этому регистру или сразу или регламентом. 
> 
> 

Если делать 1 регистр, то он будет слабым звеном в транзакциях записи, но с другой стороны блокировка будет накладываться по измерению задача, одновременно запись по одной задаче и вопросов и писем и файлов и связанных задач - велика ли вероятность? В принципе можно не морочиться и на первое время реализовать все запросом в списке к нужным объектам - вопросы, подзадачи и т.д.

**Comment by BlizD** [comment]
> @BlizD, Правильно ли я понимаю, что ты не хочешь, дабы ошибки сбора статистики влияли на транзакцию записи задач, писем, файлов и прочего?

Да, верно. Плюс есть вероятность того, что если обновлять сразу, то обновится неправильно, из за того что обновление параметра №3 может затянутся, а в это время другой параметр №8 уже обновится и тогда по данные по №8 параметру запишутся старые и неверные.

> Я просто переживаю, что обновление регламентным заданием приведет к задержке отображения корректных данных в формах списка задач.

Это не проблема, что будет задержка, это нормально.

Сделать регистр узОбновлениеДопИнформацииПоЗадаче в котором
Измерения: 
Задача
ДатаИзменения (ДатаВремя)

В этом случае запись не будет блокировать.
Далее регл. задание сортирует по "ДатеИзменения" и последовательно обновляет дополнительную информацию по каждой задаче.

**Comment by BlizD** [comment]
> > @d-hurricane можно ли сделать и регламентом и сразу? Просто хочется чтобы обновление информации не влияло на стабильность и производительность работы. Если будет регистр узОбновлениеДопИнформацииПоЗадаче то сделать запись в него легко и просто. А обновлять уже по этому регистру или сразу или регламентом.
> 
> Если делать 1 регистр, то он будет слабым звеном в транзакциях записи, но с другой стороны блокировка будет накладываться по измерению задача, одновременно запись по одной задаче и вопросов и писем и файлов и связанных задач - велика ли вероятность? В принципе можно не морочиться и на первое время реализовать все запросом в списке к нужным объектам - вопросы, подзадачи и т.д.

Сейчас как минимум есть 3 потребителя этой информации:
* узОтчетПоЗадачам
* Форма списка задачи
* Канбан доска.

Поэтому отдельные регистр узДополнительныеСведенияПоЗадачам все же нужен.

**Comment by d-hurricane** [comment]
> Это не проблема, что будет задержка, это нормально.
Не уверен. Особенно в списке задач. Может получится так: мы создали задачу с чек-листом, записали ее, она появилась в списке, но без признака наличия подзадач. Ждем 60 секунд и вуаля, признак появился. Вряд ли кто-то это оценит. :)
> Плюс есть вероятность того, что если обновлять сразу, то обновится неправильно, из за того что обновление параметра №3 может затянутся, а в это время другой параметр №8 уже обновится и тогда по данные по №8 параметру запишутся старые и неверные.
Повесим исключительную блокировку на регистр по задаче при записи. Тогда запись №8 подождет запись №3, после чего обновит информацию целиком.
Не думаю, что это может стать узким местом. Но тут хорошо бы посмотреть на реальную нагрузку. В конце концов можно разбить статистику на различные регистры: регистр для писем, регистр для подзадач и т.д.

**Comment by BlizD** [comment]
>Не уверен. Особенно в списке задач. Может получится так: мы создали задачу с чек-листом, записали ее, она появилась в списке, но без признака наличия подзадач. Ждем 60 секунд и вуаля, признак появился. Вряд ли кто-то это оценит. :)

Пусть обновляется сразу, но если была какая то проблема, то пишем в РС: узОбновлениеДопИнформацииПоЗадаче и обновляем через регламент.

Мне кажется если накладывать исключительную блокировку то это может блокировать работу . Может случится, что не загрузится письмо по 1 заблокированной задаче или нельзя будет записать задачу пока обновляется информация по письмам. 

Плюс обновление доп.информации может быть не таким уж быстрым, судя по перечисленным показателям, возможно потом еще будут какие то добавляться.

Предлагаю следующие параметры добавить в задачу:
* Параметр "количество выполненных подзадач чек-листа;" - добавить реквизит в задачу "КоличествоВыполненныхПодзадачЧеклиста" и не выносить его в доп. регистр. Обновлять значение сразу же при записи задачи.
* Параметр "количество подзадач чек-листа;" - добавить реквизит в задачу "КоличествоПодзадачЧеклиста" и не выносить его в доп. регистр. Обновлять значение сразу же при записи задачи.

Следующие параметры вынести в доп.регистр и обновлять регламентом:
* количество присоединенных фалов;
* количество связанных входящих писем;
* количество связанных исходящих писем;
* Дата последнего исходящего письма
* Дата последнего входящего письма
* количество файлов, прикрепленных к связанным письмам;

Следующие параметры не добавлять пока::
* спринт - одна задача может быть указана сразу в нескольких спринтах.
* количество задача "вниз" по иерархии (если кому потребуется) - если кто то запросит это, тогда сделаем позже.

**Comment by d-hurricane** [comment]
> Пусть обновляется сразу, но если была какая то проблема, то пишем в РС: узОбновлениеДопИнформацииПоЗадаче и обновляем через регламент.

Если транзакция сломана, мы ее уже никакими силами не спасем. Чуть позже гляну повнимательнее, как реализован регистр состояний заказов в ERP. Знаю, что в нем фиксируются оплаты и отгрузки, стало быть нагрузка тоже должна быть немалой.

**Comment by d-hurricane** [comment]
Посмотрел УТ 11.4.6.188. Все максимально просто: в обработчике проведения запросом вычисляется состояние и записывается в регистр. Ни блокировок, ни очередей, все в рамках транзакции проведения. Единственное, есть перепроверка, изменилось ли состояние. И если нет, запись в регистр не осуществляется. Т.о., видимо, исключаются избыточные блокировки записей регистра.

Полагаю, мы начали мудрить. Формально запись в регистр состояний ничем не отличается от записи в регистр очереди. Риски те же. Так что лучше сразу писать состояние. Вычисление также незамысловатое. По большому счету, оно уже используется сейчас - в запросе для канбан-доски. А посему давайте уже решимся, не будем слишком перестраховываться. :-)

И еще один момент. Раз у нас почти вся информация касается почты, предлагаю тогда назвать регистр "узСостояниеВзаимодействийПоЗадачам".

**Comment by BlizD** [comment]
Ок. Согласен

**Comment by BlizD** [comment]
Денис, поправил 2 проблемы оставшиеся.
Теперь позеленело=)
