### ISSUE TITLE
Нужно доработать кнопки для добавления md разметки. 

### ISSUE THREAD

**Issue by milanse** [BlizD/Tasks#216]
Нужно доработать кнопки для добавления md разметки. Добавить кнопку вставки картинки из буфера обмена. 

Так же хотелось бы видеть отображение в тексте номеров задач в виде ссылок

**Comment by milanse** [comment]
Назначай, может на неделе поковыряю.

**Comment by milanse** [comment]
Со вставкой картинок в MD пока не понятно, допилил существующие кнопки + добавил кнопку вставки кода 

https://drive.google.com/file/d/1ZoB4DaxLOd73r3XUJ-dXfuX1v2Q7lJ5m/view?usp=sharing

**Comment by BlizD** [comment]
Ок. Залью на выходных

**Comment by BlizD** [comment]
@milanse Спасибо, залил изменения.
