### ISSUE TITLE
Уведомления о новой задаче

### ISSUE THREAD

**Issue by elpst** [BlizD/Tasks#218]
Доброго дня.
Включили в настройках использование почты в качестве service desk.
Когда приходит новая задача, то в ней не указан исполнитель.  Хотим сделать, чтобы в новых задачах указывался сразу исполнитель (будет дальше распределять задачи).
Также хотим сделать уведомление исполнителя, если его указали в задаче.
Подскажите - что-то из указанного уже есть в конфигурации (возможно, где-то настройку не включил)?

**Comment by BlizD** [comment]
Отвечу на выходных

**Comment by 79vlad** [comment]
@elpst 
Добрый день.
Мы у себя успешно используем следующие настройки:
I. Для разбирающего входящую почту (для назначения исполнителя):
1) В настройках почтовой записи (которая принимает почту) - указать с каким статусом создавать задачу.
![image](https://user-images.githubusercontent.com/38312005/84122441-1af3c180-aa41-11ea-812c-86cb2358a706.png)

2) Для этого статуса (в карточке статуса) назначить наблюдателей (пользователь) , кому отправлять уведомления при смене статуса задачи в этот статус (сори за тавтологию).
![image](https://user-images.githubusercontent.com/38312005/84122558-48d90600-aa41-11ea-81d2-aef6adc93ac0.png)


3) точно не уверен, но будет не лишним, в настройках "Управление задачами" (это отдельно меню), для "Список пользователей кому отправлять системные уведомления" - указать статус с которым регистрируется новая задача, добавить необходимых пользователей (кто должен быть оповещен о такой задаче):
![image](https://user-images.githubusercontent.com/38312005/84120829-0a424c00-aa3f-11ea-939a-69cc16585583.png)

Таким образом - программа автоматически уведомит наблюдателей за статусом - о регистрации новой задачи.

II. Также, в программе, в карточке пользователя, есть настройки для новых задач:
1) "Автоматически становиться исполнителем новой задачи, если автор входящего письма"
2) Использовать персональный статус новой задачи и сам статус новой задачи.
![image](https://user-images.githubusercontent.com/38312005/84121900-5e016500-aa40-11ea-9112-6a30d7e9b74e.png)

Суть этих настроек: программист может самостоятельно сформировать описание задачи и отправить на почту "Tasks" При получении письма, программа проверяет, есть ли пользователь с таким e-mail и если такой пользователь есть, и у него установлена такая настройка - то он автоматически становится исполнителем по этой задаче.

Чтобы уменьшить поток оповещений (по первой настройке) для "разбирающего входящие письма", необходимо, чтобы персональные статусы задачи не совпадали со статусами, которые указаны в настройках "Почтовой учетной записи"

По вопросу уведомление исполнителя о назначении ему задачи - это "вшито" в программу:
Если у задачи изменился исполнитель - то автоматически формируется письмо новому исполнителю. Письмо не будет отправлено, если новый исполнитель сам себе назначил задачу (т.е. является текущим пользователем). Это заглушка, чтобы сам себе не спамил.

PS На скринах - чуть доработанная программа (есть подсистемы, которых нет в оф. релизе, они (подсистемы) еще не готовы для включения в релиз)

**Comment by elpst** [comment]
Добрый день. Спасибо за пояснения.
Разобрался из-за чего не уходили уведомления исполнителю: при заведении учетной записи создали новую учетную запись, а не заполнили системную (которая является предопределенной). При отправке письма исполнителю используется как раз системная учетная запись, соответственно письма не отправлялись.

Касательно ответственного при поступлении новой задачи хотим сделать следующее: когда заказчик отправляет заявку на почту, то она попадает сразу в нужный статус, а также задается исполнитель. 
Для чего нужно:  сначала задача попадает на консультанта. Если для решения нужно дорабатывать конфигурацию, то консультант будет указывать другого исполнителя.

**Comment by 79vlad** [comment]
@elpst 
Мы у себя сейчас обкатывает подсистему регистрации обращений: все входящие письма регистрируются как обращения. Их обрабатывает консультант. Если необходимо привлекать программистов - то на основании обращения, создаются задачи на программистов (т.е. идёт обычный учёт задач). Как только все задачи выполнены - обращение считается закрытым и отправляется уведомление пользователю, что его обращение полностью обработано.
Также сделали ws, по которому можно создавать обращения из других программ (минуя почту).

Но это все в стадии бэта и ещё вылизывается. Потом планируем выложить для включения в релиз

**Comment by BlizD** [comment]
@79vlad 

Добавил твою настройку как кейс в вики
* [Кейс: как можно настроить уведомления о задаче пришедшей из почты](https://github.com/BlizD/Tasks/wiki/Кейс:-как-можно-настроить-уведомления-о-задаче-пришедшей-из-почты.)
