### ISSUE TITLE
Работа с Telegram

### ISSUE THREAD

**Issue by serg33rus** [BlizD/Tasks#221]
Сняли блокировку с телеги. Но сейчас смотрю код и не понимаю. Такое впечатление что работа через прокси строго обязательна. и вроде бы в Справочнике Константы есть установка работы телеграмм без прокси, но где оно используется я так и не нашел. Это глюк или я что-то не так делаю? Версия 1.0.5.001

**Comment by BlizD** [comment]
Не знаю надо кому то проверить

**Comment by serg33rus** [comment]
Я проверил. Не проверяется константа "Не использовать прокси". Сделать чтобы проверялась?

**Comment by BlizD** [comment]
Да, сделай, пожалуйста.

**Comment by serg33rus** [comment]
На самом деле криво прописано только в обработке Работа с телеграмм. В общем модуле все ОК и все работает. Так что наверно вопрос можно снять. Эта обработка, я так понял, тестовая. Там просто полностью прописаны свои функции, аналоги функций из общего модуля узТелеграммСервер. Вот я в раздумьях, эта обработка вообще нужна кому? Если нет, то можно не заморачиваться.
