### ISSUE TITLE
Оптимизация заполнения канбан-доски, мелкие дополнения

### ISSUE THREAD

**Issue by d-hurricane** [BlizD/Tasks#225]
Текущий запрос задач для заполнения доски не использует возможности СКД для оптимизации запросов. В частности, всегда выполняется запрос к регистру наблюдателей при том вне зависимости от того, используется ли отбор по наблюдателям или нет. Хочется поправить этот момент.

С точки зрения пользователя возможны два нововведения.

1. Сейчас поля "Есть файлы" и "Есть письма" являются односимвольными строками. Предлагаю исправить это, т.к. такой тип полей в некоторых ситуациях может быть неудобен. Пусть будут булево типа, а отображаемый символ настроим форматом поля. В качестве примера, это позволит настраивать понятный отбор по наличию файлов как "Да/Нет".

2. Если будет принят PR #223, появится возможность отображать не только признак наличия письма или файла, но и их количество. Т.о. можно предусмотреть настройку третьей строки, где на выбор будут уже 3 значения опции:
   - не отображать
   - отображать только признак
   - отображать количество и признак

Выглядеть количество и признак будут примерно так:
![2020-06-23_10-21-20](https://user-images.githubusercontent.com/59051827/85363857-5c08cd00-b53b-11ea-8d6f-601820530161.png)

**Comment by BlizD** [comment]
Согласен

**Comment by Dimanchik00** [comment]
А нет возможности показать количество  задач в колонках (столбцах) доски ?

**Comment by d-hurricane** [comment]
@Dimanchik00 есть конечно, но эта доработка не вписывается немного в предложенные здесь доработки. Создайте, пожалуйста, отдельную задачу, я чуть позже вернусь к ней.

**Comment by d-hurricane** [comment]
Подойдет такой внешний вид для настроек третьей строки?
![2020-07-06_19-09-40](https://user-images.githubusercontent.com/59051827/86602731-86876b00-bfbc-11ea-884e-18c201de6302.png)

**Comment by BlizD** [comment]
Да. Подойдет. Только Х предлагаю заменить на Нет

**Comment by BlizD** [comment]
@d-hurricane Денис, привет. 
Почему то при попытке загрузить изменения из файлов в пустую тестовую базу выдает ошибку

![image](https://user-images.githubusercontent.com/10989306/87217868-a4efbc80-c356-11ea-9216-6bfd2cb27c5d.png)

Подскажи ты какую версию платформы используешь?
Возможно с этим связана проблема. Необходимо использовать 8.3.16.1063?

**Comment by BlizD** [comment]
@d-hurricane Привет, может пришлешь просто cf?

**Comment by BlizD** [comment]
@d-hurricane 
Денис, привет.

Залил изменения. 
Добавил подсказку для 3 строки.

![image](https://user-images.githubusercontent.com/10989306/88449581-a1792c80-ce50-11ea-8eb0-379cb285724f.png)
![image](https://user-images.githubusercontent.com/10989306/88449567-94f4d400-ce50-11ea-8b8f-ee366a396086.png)


Есть проблема, не показывается дробь 0/2, не показывается процент 0% для задач, в которых есть пункты чеклиста.

И еще такой момент, есть ощущение, что пользователи захотят и дробь и процент сразу видеть.

**Comment by BlizD** [comment]
Возможно, выло бы классно еще сделать.

Если включена ФО: "Использовать вопросы и ответы".
Тогда показывается еще пункт в настройках 3 строки канбан доски

Отображение вопросов по задаче
ЧОВ? - число открытых вопросов. Пример: 4?
ЧОВ?/ЧЗВ? - число открытых вопросов/число закрытых вопросов. Пример 3/6?

**Comment by d-hurricane** [comment]
> Есть проблема, не показывается дробь 0/2, не показывается процент 0% для задач, в которых есть пункты чеклиста.
Ок, чуть позже перепроверю и исправлю.

> И еще такой момент, есть ощущение, что пользователи захотят и дробь и процент сразу видеть.
Я на самом деле долго думал над этим. С одной стороны на мой взгляд очень редкая ситуация, с другой - нет идей, как показать все эти настройки красиво. Потому и убрал такую возможность. Технических препятствий нет. Если кто подскажет, как нарисовать такие настройки на форме, тут же все исправлю.

**Comment by BlizD** [comment]
>Я на самом деле долго думал над этим. С одной стороны на мой взгляд очень редкая ситуация, с другой - нет идей, как показать все эти настройки красиво.

 Думаю оставим как есть. Если захотят обе, тогда вынесем в отдельную настройку.

**Comment by d-hurricane** [comment]
> Есть проблема, не показывается дробь 0/2, не показывается процент 0% для задач, в которых есть пункты чеклиста.

Антон, тут исправление небольшое. Предлагаю тебе самому внести правки, дабы было быстрее, чем я будут готовить PR.
В модуле менеджера обработки "узКанбанДоска" есть две функции:
* ЧекЛистВыполнение
* ЧекЛистВыполнениеПроцент
В них обеих в начале тела функции есть проверка заполненности параметров "Выполнено" и "Всего". Нужно убрать проверку параметра "Выполнено", оставить только проверку "Всего".

**Comment by BlizD** [comment]
Денис, сделал.

![image](https://user-images.githubusercontent.com/10989306/88453288-3b9b9d80-ce6e-11ea-94f0-3ada0eb0a591.png)

Кстати на будущее лучше не использовать модуль менеджера обработки и отчетов.
Лучше выносить в другие объекты ОбщиеМодули, Модули менеджеров справочников и документов и пр.

Против обработок и отчетов, потому что при сохранении в файл модуль менеджера обработки/отчетов не сохраняется и может быть потеря данных.

**Comment by d-hurricane** [comment]
Хорошо, учту.
