### ISSUE TITLE
Предложение: Группировка статусов в колонке

### ISSUE THREAD

**Issue by GenVP** [BlizD/Tasks#228]
Делал раньше для себя группировку статусов в одной колонке для канбан доски. Удобно, если сразу выводится много статусов и в некоторых статусах мало задач.
![Снимок1](https://user-images.githubusercontent.com/34754769/86134688-9ac9f480-baf2-11ea-9658-0e95c03851ee.PNG)
Группировка настраивается на закладке настройки по номерам групп и сохраняется для каждого пользователя. Относительная высота групп сохраняется. При выводе сортируется по номеру группы (начиная с пустой - 0).
![Снимок2](https://user-images.githubusercontent.com/34754769/86134719-a1f10280-baf2-11ea-8834-e087f1b2ae56.PNG)

Если другим то же подойдет, то могу добавить.

**Comment by BlizD** [comment]
Отвечу на выходных

**Comment by d-hurricane** [comment]
А почему не стали такую задачу решать стандартными средствами - через меню "Изменить форму..."?

**Comment by GenVP** [comment]
> А почему не стали такую задачу решать стандартными средствами - через меню "Изменить форму..."?

Мне через группы было удобней. Ненужные статусы то же можно отключить через изменить форму, но удобнее это делать через настройки.

**Comment by BlizD** [comment]
@GenVP 
Добрый день.
Не против доработки, мне кажется она будет полезна.
Как доработать описано в задаче #215 если будете делать через CF файл.

**Comment by GenVP** [comment]
Изменения:
Обработка.узКанбанДоска.ТабличнаяЧасть.ТЧНастройкиКолонок.Группа
Обработка.узКанбанДоска.ФормаДинамическая

[020720_228.cf](https://yadi.sk/d/twK4A6YS15LeNw)

**Comment by BlizD** [comment]
@GenVP спасибо. Залью на выходных

**Comment by BlizD** [comment]
@GenVP Спасибо. Залил изменения.
