### ISSUE TITLE
При создании новой задачи заголовок окна остается пустой.

### ISSUE THREAD

**Issue by milanse** [BlizD/Tasks#237]
Если отключен типовой механизм отображения заголовков, наверное надо довести до ума кастомный.

![image](https://user-images.githubusercontent.com/15941393/89612170-d1302780-d887-11ea-8e2f-4b1e8619e8f9.png)

**Comment by BlizD** [comment]
Это для новой задачи? Для существующей нормально?

**Comment by milanse** [comment]
> Это для новой задачи? Для существующей нормально?

Да, для новой. А зачем переделывали типовой заголовок, вывести номер задачи ?

**Comment by BlizD** [comment]
@milanse 
>Да, для новой. А зачем переделывали типовой заголовок, вывести номер задачи ?

Да, верно, чтобы вначале был номер задачи.
Внес изменения, теперь для новой задачи будет заголовок "Новая задача", если изменят наименование, то будет указано наименование, если запишут задачу, тогда вначале будет номер задачи.
