### ISSUE TITLE
Подключение механизма шаблонов к рассылке уведомлений.

### ISSUE THREAD

**Issue by milanse** [BlizD/Tasks#238]
В подсистеме взаимодействия есть механизм настройки шаблонов, хорошо бы было подключить данный механизм к механизму рассылок. Получается что-то типа этого:

![image](https://user-images.githubusercontent.com/15941393/89612489-937fce80-d888-11ea-8656-b53f33a38604.png)

Если включить рассылку в формате html можно заодно решить задачу #34

**Comment by d-hurricane** [comment]
Кто-то же вроде говорил, что у него разработка шаблонов в процессе. Кажется, в телеге такое звучало.

**Comment by milanse** [comment]
Пока не видно PR на эту тему

**Comment by BlizD** [comment]
Важно, чтобы если шаблоны не настроены то отправлялось как сейчас.

**Comment by 7OH** [comment]
Письмо с выбором шаблона сделать получается.
Но дальше фантазия закончилась, может после отпуска попробую со свежей головой.
Там тема письма из регистра собирается - получается от этого надо отказаться ?
А что вместо ? Получается надо создать шаблоны для каждого вида события (для разных языков тоже?).
Плюс - руками сразу, чтобы начальное наполнение их создало ?

**Comment by 7OH** [comment]
Предложение пока рождается - в регистр словаря добавить поле шаблона, и если там по коду и языку есть шаблон - генерить письмо по шаблону, иначе - как было раньше оставить.
Так нормально будет ? Могу пока выложить, что есть на последнем релизе

**Comment by BlizD** [comment]
Выложи пока то что есть. Дальше посмотрим

**Comment by GenVP** [comment]
Можно сделать так:
1. Доп параметры в реквизитах шаблона:
- Словарь со словами, которые используются в письмах. Как и сейчас значения слов будут заменяться в письме из словаря.
- Динамические параметры - номер задачи, тема, список комментариев или что-то еще.
2. Регистр сведений текущих шаблонов, непериодический. Измерение вид шаблона (заказчик, общий), ресурс шаблон.

Текущий шаблон при отправке получается из РС текущих шаблонов.

Только с письмами HTML проблема, если вдруг в середине параметра форматирование измениться.
Я еще делал  другой конфигурации для шаблонов редактирование кк текста письма, так и результата в HTML для таких случаев.

**Comment by GenVP** [comment]
Типа такого: [Пример шаблона](https://prnt.sc/u1qnom)

**Comment by 7OH** [comment]
GenVP, судя по скрину со словарём, Вы зашли дальше. 
Выложите наработку шаблона ?

**Comment by GenVP** [comment]
Пока не доделал HTML ради которого все и делалось. Как доделаю - выложу. Наверное, через 2-3 дня.

**Comment by GenVP** [comment]
Два варианта, которые получились. Конфигурации по стандарту не оформлены, так как планировал попробовать поместить через git. [Вариант cf 1](https://yadi.sk/d/Nhxr_h2KfuJ-6w) [Вариант cf 2](https://yadi.sk/d/GZuWSFhPG_XRmw):

1. В базе нужно отправлять письма на разных языках разным пользователям/заказчикам. Сам не использую, но вполне рабочий:
- Язык сообщений может быть задан у пользователя и заказчика в реквизите "Язык сообщений на почту". Если не задан - язык отправителя как и сейчас.
- Шаблон сообщения определяется по регистру сведений "Текущие шаблоны" (Администрирование - органайзер, рядом с шаблонами) в разрезе "вид шаблона", "язык". Можно задавать шаблон для конкретного языка, можно для всех (если пустой). Вид шаблона - для заказчика и пользователя. Если шаблоны не заданы, то используется типовой вариант подготовки сообщения.

2. Как и сейчас рассчитано, что все пользователи работают на одном языке:
- Шаблон сообщения определяется по регистру сведений "Текущие шаблоны" (Администрирование - органайзер, рядом с шаблонами) в разрезе "вид шаблона". Можно задавать шаблон для пользователей и для заказчиков. Если шаблоны не заданы, то используется типовой вариант подготовки сообщения.
- Для заказчика можно задать свой шаблон в реквизите "Шаблон сообщений"

3. Общее:
- Шаблон может быть как в HTML так и в простом тексте. При получении сообщения текст HTML сохраняется в коде как отдельный параметр и не должен помешать другим рассылкам в коде (телеграмм и т.п.).
- В шаблоне ест доп. поля словаря "# Словарь транслируемых слов". Они транслируются при отправке шаблона в язык сообщения. При редактировании шаблона слова отображаются на текущем языке. Все слова те же, что используются сейчас.
- В шаблоне есть доп. параметры "# Динамические параметры" - параметры которые сейчас формируются в коде задачи и их нет в реквизитах. Туда же можно добавить свои параметры - веб-ссылку и т.п.

Шаблон пользователя:
```
Тема:
#[узЗадачи.узНомер_задачи] [узЗадачи.узТема_письма_событие][узЗадачи.Наименование] 
Сообщение:
[узЗадачи.узСловарь_Добрый_день].

[узЗадачи.узТема_письма_событие] [узЗадачи.Наименование]
[узЗадачи.узСловарь_Номер_задачи]: [узЗадачи.узНомер_задачи]

[узЗадачи.узСловарь_Комментарии]:[узЗадачи.узИзменения_по_комментариям]

[узЗадачи.узСловарь_Реквизиты_задачи]:
- [узЗадачи.узСловарь_Исполнитель]: [узЗадачи.Исполнитель]
- [узЗадачи.узСловарь_Статус]: [узЗадачи.Статус]
- [узЗадачи.узСловарь_Важность]: [узЗадачи.Важность]
- [узЗадачи.узСловарь_Основная_задача]: [узЗадачи.ОсновнаяЗадача]
```

Шаблон заказчика:
```
Тема:
#[узЗадачи.узНомер_задачи] [узЗадачи.узТема_письма_событие] [узЗадачи.Наименование] 
Сообщение:
[узЗадачи.узСловарь_Добрый_день].

[узЗадачи.узТема_письма_событие]

[узЗадачи.узСловарь_Номер_задачи]: [узЗадачи.узНомер_задачи]
#[узЗадачи.узНомер_задачи] [узЗадачи.узТема_письма_событие] [узЗадачи.Наименование] 

[узЗадачи.узСловарь_Описание_задачи]:
[узЗадачи.ТекстСодержания]
```

**Comment by BlizD** [comment]
Спасибо. Скоро залью в основную ветку

**Comment by 79vlad** [comment]
В прикрепленной к задаче #241 есть рабочий пример использования справочника "Шаблоны сообщений" при формировании рассылки по событиям в справочнике "Обращение". Посмотрите, может что-либо готовое можно позаимствовать

**Comment by milanse** [comment]
Для уведомлений о вопросах ответах не работает, нужен отдельный шаблон.

**Comment by milanse** [comment]
Если надо могу выложить свой форк, там уведомление контрагента выглядит по-человечески:

![image](https://user-images.githubusercontent.com/15941393/93341235-82868d80-f836-11ea-913d-88fd9d59dfac.png)

Правда не цепляются картинки, пока не обрабатывается вариант когда описание задачи в  MD.

+ добавлены реквизиты для отображения ссылки на задачу и номера в формате [#НомерЗадачи]

**Comment by GenVP** [comment]
> Для уведомлений о вопросах ответах не работает, нужен отдельный шаблон.
Получается не только новый шаблон, но и новый параметр(-ры), так как тест и тема по другим данным формируется

**Comment by GenVP** [comment]
> Если надо могу выложить свой форк, там уведомление контрагента выглядит по-человечески:
> 
> ![image](https://user-images.githubusercontent.com/15941393/93341235-82868d80-f836-11ea-913d-88fd9d59dfac.png)
> 
> Правда не цепляются картинки, пока не обрабатывается вариант когда описание задачи в MD.
> 
> * добавлены реквизиты для отображения ссылки на задачу и номера в формате [#НомерЗадачи]

Я за. Как минимум ссылки добавим в шаблоны.
