### ISSUE TITLE
Не во всех колонках Канбан доски указывается специальный цвет оформления для задач 

### ISSUE THREAD

**Issue by BlizD** [BlizD/Tasks#24]
Не во всех колонках Канбан доски указывается специальный цвет оформления для задач.

* Если указать цвет для Важности, Основной задачи, то допустим в колонке "На тестирование / показ пользователям" цвет не изменяется, остается тот, что указан по умолчанию.
* Также при перетаскивании задачи из колонки в колонку, цвет для задачи становится тот, что указан по умолчанию. Пока не обновишь канбан доску.

**Comment by BlizD** [comment]
@BUDIVAL Дима вдруг будет время поправить.
Если нет, тогда сам.

**Comment by BUDIVAL** [comment]
Гляну

**Comment by BlizD** [comment]
@BUDIVAL Дима, спасибо! Все работает=)
