### ISSUE TITLE
Добавление текущего дела, вопроса, задачи через телеграмм

### ISSUE THREAD

**Issue by BlizD** [BlizD/Tasks#240]
Добавление текущего дела, вопроса, задачи через телеграмм.

Сейчас в обработке узРаботаСТелеграм уже есть реализации добавление текущего дела, если боту в телеграмм отправляется сообщение: /addwork "Текст" то создается текущее дело в УправлениеЗадачами для пользователя отправившего сообщение.

Необходимо внести изменения:
1. вместо ключа "/addwork" сделать ключ "!". То есть если написано !Текст тогда должно создаться текущее дело в УправлениеЗадачами.
2. добавить ключ "?". Если написано ?Текст, тогда создается вопрос с текстом вопроса, автор вопроса указывается пользователь отправивший сообщение.
3. добавить ключ "#". Если написано #Текст, тогда создается задача с текстом. 

Дополнительно:
* скорее всего потребуется создать настройки по умолчанию, для задачи пришедшей из телеграмма: ОсновнаяЗадача, СтатусЗадачи.
* было бы хорошо еще реализовать, если написано ?Текст #НомерЗадачи, тогда вопрос создается с привязкой к задаче.

Обработка узРаботаСТелеграм
Процедура ПрочитатьСообщенияTelegram

![image](https://user-images.githubusercontent.com/10989306/90727791-832a1380-e2cc-11ea-9a53-0a8126c4dfcf.png)

**Comment by GenVP** [comment]
Разбирался с телеграмм ботом. Предлагаю такие команды, которые удобно анализировать:
Новое дело - "!ТекстОписания"
Новая задача - "#ТекстОписания"
Новый вопрос - "?ТекстВопроса"
Комментарий к задаче - "#НомерЗадачи ТекстКомментария"
Вопрос к задаче - "#НомерЗадачи ?ТекстВопроса"
Файл к задаче - "#НомерЗадачи" в заголовке файла

Пример: [пример команд](https://prnt.sc/uafap4)

**Comment by BlizD** [comment]
Согласен

**Comment by 79vlad** [comment]
@GenVP Добрый день.
Где-то видел конфигурацию по работе с телеграм-ботом. Там все клавиатуры (команды) реализованы через справочник. В команде сразу прописано имя команды и как его обработать текст алгоритма). При разборе входящей команды, выполняется поиск по справочнику и если нашли команду и она отмечена как активная - то алгоритм запускается через "Выполнить".  Таким образом, любой программист сможет самостоятельно писать свои команды без изменения конфигурации. Для релиза, можно в обновление прописать заполнение базовых (стартовых) команд. 
Вы такой вариант реализации не рассматривали?
PS могу поискать ту демо с примером работы с телегой (но там демо и модули закрыты).

**Comment by GenVP** [comment]
@79vlad Думаю универсальный справочник команд делать не стоит по причинам:
1. Его выполнение не удобно отлаживать, так как обработка будет через "Выполнить". 
2. С помощью расширения проще переопределить и написать свой пул команд. Тем более что сейчас обработка команд будет в отдельном модуле и достаточно дополнить/заменить в расширении одну процедуры. Для примера новая обработка и пример команды: [Пример](https://prnt.sc/uao4op)

**Comment by BlizD** [comment]
Пока против универсальности.

**Comment by BlizD** [comment]
@GenVP наверно нужна еще команда /help при получении такой команды отправлять список доступных команд с комментариями - это можно выделить в отдельную задачу

**Comment by GenVP** [comment]
@BlizD хорошо, сделаю

**Comment by 79vlad** [comment]
На будущее (как развитие функционала бота), можно ещё добавить команду /ShowMyTasks по этой команде возвращается перечень не завершенных задач с их текущими статусами. Остаётся только идентифицировать кто запросил: заказчик или исполнитель (соответственно и список формировать для запрашивающего)

**Comment by BlizD** [comment]
@79vlad тоже об этом думал, но это точно уже в рамках другой новой задачи. 

Правда думал сделать как в сотовых операторах. 
*100# - текущие задачи и их статус

**Comment by GenVP** [comment]
@BlizD в процессе тестирования работы с командами выяснилось, что сейчас есть два варианта отправки сообщений в телеграмм:
1. GET-запросом при выполнении рассылки из задачи. С преобразованием текста в строку URL. Вызывается только, если не указаны прокси.
2. POST-запросом из обработки узРаботаСТелеграм. Вызывается во всех остальных случаях.

Не в курсе, это legasy или GET запрос работает гораздо быстрее чем POST?

**Comment by BlizD** [comment]
@GenVP думаю это легаси.

**Comment by BlizD** [comment]
@GenVP 
Еще раз спасибо за доработки.
Дополнительно внес следующие изменения:
* реализовал отправку сообщений пользователю после отработки полученной команды
* добавил константу "ТелеграммРодительДляНовойЗадачиПоУмолчанию"
* убрал команду из списка доступных `#НомерЗадачи #ТекстОписания - новая подзадача к задаче`

Еще прошу на будущее, любые изменения метаданных, сначала обсуждаем, а потом вносим изменения.
В данном случае изменение/удаление модуля узТелеграммСервер не стоило делать, но принял как есть.

**Comment by BlizD** [comment]
А еще сделал регл. задание "Предопределенным"

**Comment by GenVP** [comment]
@BlizD, хорошо. В этот раз я похоже "немного" увлекся реализацией

**Comment by capitoshko** [comment]
задача еще актуальна?

**Comment by BlizD** [comment]
> задача еще актуальна?

Игорь, она уже реализована будет в следующем релизе.
Реализована через РЗ узПолучениеИОбработкаСообщенийТелеграммБота
![TelegramBot](https://user-images.githubusercontent.com/10989306/93013388-bf415300-f5b0-11ea-9556-3b0c665216a6.gif)
[Как добавлять через телеграмм текущие дела, задачи, вопросы](https://github.com/BlizD/Tasks/wiki/Как-добавлять-через-телеграмм-текущие-дела,-задачи,-вопросы)
