### ISSUE TITLE
Добавить права на чтение для Константа "узТелеграмм_ТокенБота"

### ISSUE THREAD

**Issue by sldubinsky** [BlizD/Tasks#261]
Константа "узТелеграмм_ТокенБота" не добавлена в права, и при получении параметров бота падает с ошибкой.

**Comment by BlizD** [comment]
Добрый день. В данном случае лучше добавить право чтение для ролей узПользователь узПользовательОграничениеДоступаЧтение и еще 1

**Comment by BlizD** [comment]
Добавил права на чтение.
