### ISSUE TITLE
Не срабатывают ссылки в Содержание

### ISSUE THREAD

**Issue by serg33rus** [BlizD/Tasks#277]
Заметил один мелкий, но неприятный глючок. 
В содержании в поле Форматированный текст можно вставить ссылку. Но вот перейти по ней нельзя.
Чтобы срабатывал переход надо чтобы это поле было в режиме "Только чтение". 
В расширении База Знаний тест открывается так же форматированным документом, но по умолчанию в режиме "Только чтение". Чтобы что-то подправить надо нажать на кнопочку "Редактирование". Лишнее движение, зато можно в текст навтыкать ссылок и по ним переходить.
Даже не знаю как лучше. Но то, что ссылки не работают - несколько огорчает.

**Comment by BlizD** [comment]
Возможно стоить добавить кнопку "Только просмотр / редактирование" с подсказкой "Устанавливает/снимает режим только просмотр. Режим только просмотр позволяет переходить по ссылкам указанным в содержании". Кнопка показывается только на закладке с форматированным содержанием. 

Думаю еще нужно сохранять установленный режим для каждой задачи отдельно. То есть нужен реквизит " ТолькоПросмотрФорматированногоСодержания"(Булево)

**Comment by serg33rus** [comment]
Я бы пожалуй попробовал сделать. На каком .CF? Если будет на 1.0.5.010, нормально будет?

**Comment by BlizD** [comment]
Нужно на дев последней https://github.com/BlizD/Tasks/issues/123

**Comment by serg33rus** [comment]
Принято.

**Comment by milanse** [comment]
Вообще просмотр в виде форматированного документа работает не очень , часто шлют таблицы в письмах, они не отображаются, если делать только просмотр, то показывать его в html, при начале редактирования переводить в форматированный документ

**Comment by BlizD** [comment]
@milanse это пока не нужно делать. Лучше выделить в отдельную задачу и там обсудим

**Comment by serg33rus** [comment]
Воткнул кнопочку "Редактирование". Реквизит делать не стал. Ну не нужен он. Содержание, как правило, заполняется при создании задачи. Бывает, что его нужно подредактировать, но это не значит, что и потом открывая эту задачу ты будешь ее редактировать. в общем сделано примерно как в Вопросах.
И еще. Добавил три строчки по #236. Теперь при создании Вопроса поле Задача заполняется автоматом. 
https://drive.google.com/file/d/19WyAspf2avAqerqvLwLoUwl7uByeAwQG/view?usp=sharing

**Comment by BlizD** [comment]
Сейчас при открытии задачи можно сразу изменять содержание задачи? или необходимо нажимать на кнопку?

Если надо нажимать на кнопку, то нужно изменить поведение, что при открытии задачи редактирование сразу доступно.

Поэтому и нужен реквизит, чтобы только для некоторых задач, где есть ссылка включать "Просмотр", а для всех остальных редактирование сразу доступно.

**Comment by serg33rus** [comment]
При создании Задачи редактирование включено.
При просмотре уже созданной, выключено и включается по кнопке.
Я понимаю о чем ты. Но возлагать на пользователя переключение режима отображения ... как-то не очень.
Не было ссылок и пользователь поставил "Редактировать". Потом воткнул и ему надо поставить "Просмотр"? А если потом ее удалил? В обратку? Как-то неаккуратно. Реквизит сделать нетрудно. Вот только он сделает поведение не совсем понятным. Сейчас сделано тупо, но всегда одинаково. Созданная задача открывается в режиме просмотра. Надо исправить Содержимое, нажми на кнопочку. У меня в задачах и Базе знаний ссылки часто используются. И на http и на объекты конфигурации. Очень удобно.

**Comment by BlizD** [comment]
Получается, что сейчас для всех пользователей изменится поведение, теперь им надо будет нажимать на кнопку для существующих задач. Вот это и не хотелось бы менять.

**Comment by serg33rus** [comment]
Хммм. Ну так-то да. Но сейчас у ВСЕХ ссылки не срабатывают, а нынче будут. В общем-то тоже измениться и поведение и функционал. Просто понять бы насколько часто требуется исправлять Содержимое задачи. Если нечасто, то одна песня, Если постоянно, то другая. Я Содержимое не так часто правлю. У кого-то может быть и иначе. 
Скажи как сделать. Воткнуть реквизит? И чему он должен быть равен по умолчанию? Если Истина, то для пользователя ничего не измениться, но и ссылки работать не будут, пока не нажмет на кнопочку. И ведь не нажмут и так и будут без ссылок жить.

**Comment by serg33rus** [comment]
Может в телеге в группе мини-опрос провести? И уж тогда танцевать?

**Comment by 79vlad** [comment]
Я тоже за то, чтобы в записанных задачах режим редактирования включался по кнопке осознанно пользователем, т.к. содержание очень редко правится и эта кнопка исключит случайную правку содержания в уже записанных задачах

**Comment by serg33rus** [comment]
> Я тоже за то, чтобы в записанных задачах режим редактирования включался по кнопке осознанно пользователем, т.к. содержание очень редко правится и эта кнопка исключит случайную правку содержания в уже записанных задачах

**Comment by serg33rus** [comment]
Я покурил и сформулировал вариаты.
1. При создании режим Редактирования. При открытии существующей режим "просмотр", ссылки работают, для редактирования нажать кнопочку "Редактировать". Визуально видно по серой или активной панели Редактирование.
2. По умолчанию включен режим "Редактирования". Для того чтобы перейти по ссылке надо по кнопочке перейти в режим "просмотр". Визуальные эффекты как в п.1.
3. Сделать глобальную константу режима просмотра. Каждый сам себе ее устанавливает. Для всех задач.
4. При записи задачи запоминать последний режим. Отредактировал, установил режим, записал. Универсально, но не очень прозрачно. Ну и как правило, либо нормой является редактирование Содержимого, либо оно формируется при создании, а все остальное либо подзадачами, либо Комментариями, либо Вопросами. Потому как редактирование Содержимого в оповещения не падают.

**Comment by serg33rus** [comment]
Хммм. Смотрю закрыто уже. А я надрываюсь :-). А какое хоть решение принято?

**Comment by 79vlad** [comment]
> Я покурил и сформулировал вариаты.
> 
> 1. При создании режим "Редактирование". При открытии существующей режим "Просмотр", ссылки работают, для редактирования нажать кнопочку "Редактировать". Визуально видно по серой или активной панели Редактирование.
> 2. По умолчанию включен режим "Редактирование". Для того чтобы перейти по ссылке надо по кнопочке перейти в режим "просмотр". Визуальные эффекты как в п.1.
> 3. Сделать глобальную константу режима просмотра. Каждый сам себе ее устанавливает. Для всех задач.
> 4. При записи задачи запоминать последний режим. Отредактировал, установил режим, записал. Универсально, но не очень прозрачно. Ну и как правило, либо нормой является редактирование Содержимого, либо оно формируется при создании, а все остальное либо подзадачами, либо Комментариями, либо Вопросами. Потому как редактирование Содержимого в оповещения не падают.

Кстати, переход в режим редактирования - это доп триггер, на который можно навесить уведомления "Изменилось описание задачи"

PS видать случайно @serg33rus  закрыл текущую ветку , надо бы повторно открыть

**Comment by serg33rus** [comment]
> 
> Кстати, переход в режим редактирования - это доп триггер, на который можно навесить уведомления "Изменилось описание задачи"
Ну сейчас изменение Содержания в уведомления не падает. По кнопке "Редактировать" нельзя делать уведомления. Нажал, ничего не изменил, обратно отжал. И о чем тут уведомлять?
> 
> PS видать случайно @serg33rus закрыл текущую ветку , надо бы повторно открыть
Это не я. Это Антон вероятно принял какое-то решение и закрыл.

**Comment by 79vlad** [comment]
> Ну сейчас изменение Содержания в уведомления не падает. По кнопке "Редактировать" нельзя делать уведомления. Нажал, ничего не изменил, обратно отжал. И о чем тут уведомлять?

Можем придумать что угодно, например, можем используя измерение режима перед записью задачи, спросить о необходимости отправить уведомление. Главное, что есть событие изменения режима и можем по нему ориентироваться и если надо - то или спрашивать (чтобы не сравнивать было/стало)  о необходимости уведомления (это лучше) или сразу отправлять уведомления (это хуже)

**Comment by BlizD** [comment]
Я не закрывал. Это ты serg33rus:smile:

**Comment by BlizD** [comment]
@serg33rus 
>3. Сделать глобальную константу режима просмотра. Каждый сам себе ее устанавливает. Для всех задач.

Мне нравится вот этот вариант, только константу создать в справочнике узКонстанты.
Константу предлагаю назвать "УстанавливатьТолькоПросмотрДляСодержанияЗадач" (Булево) синоним "Устанавливать только просмотр для содержания у существующих задач".
Если указано УстанавливатьТолькоПросмотрДляСодержданияЗадач = ДА, тогда для существующих задач ставить только просмотр для содержания.

Обеспечить автозаполенение при смене релиза, по умолчанию выставить УстанавливатьТолькоПросмотрДляСодержданияЗадач = ДА

**Comment by BlizD** [comment]
>Ну сейчас изменение Содержания в уведомления не падает. По кнопке "Редактировать" нельзя делать уведомления. Нажал, ничего не изменил, обратно отжал. И о чем тут уведомлять?

Согласен, считаю, что уведомление не стоит делать по нажатию на кнопку "Редактировать".

**Comment by serg33rus** [comment]
> 
> Обеспечить автозаполенение при смене релиза, по умолчанию выставить УстанавливатьТолькоПросмотрДляСодержанияЗадач = ДА

Следующий релиз считать 1.0.5.011? 
Я могу сделать тупо. При первом входе в Задачу проверять и устанавливать если еще не установлено. 
Тогда релиз будет пофиг. 
Как скажешь, так и сделаю.

**Comment by serg33rus** [comment]
Сделал при обновлении релиза заполнение константы. Воткнул в обновление до 11.0.5.11. 
https://drive.google.com/file/d/1ui_c02BUkw0NaYo4qONH1ca9skfCUmc3/view?usp=sharing

**Comment by BlizD** [comment]
Спасибо.

**Comment by BlizD** [comment]
@serg33rus залил изменения, немного скорректировал код.
Управление формой (видимость, доступность) необходимо выполнять в процедуре "УстановитьВидимостьДоступность".

**Comment by serg33rus** [comment]
Супер. Сейчас себе накачу. А то прямо неудобно работать. 
Спасибо.

**Comment by serg33rus** [comment]
Как мне кажется строка 465 в модуле формы элемента Задачи лишняя.
Поскольку ниже идет код который устанавливает значение Элементы.Содержание.ТолькоПросмотр
Хотя на ход поршней не влияет :-)

**Comment by BlizD** [comment]
@serg33rus 
>Как мне кажется строка 465 в модуле формы элемента Задачи лишняя.
Поскольку ниже идет код который устанавливает значение Элементы.Содержание.ТолькоПросмотр
Хотя на ход поршней не влияет :-)


Привет. Это просто такой подход, что сначала все запрещаем, а потом ниже что то разрешаем или показываем.

**Comment by serg33rus** [comment]
>
> Привет. Это просто такой подход, что сначала все запрещаем, а потом ниже что то разрешаем или показываем.

Понял. 
Тогда вроде все, закрываю?

**Comment by BlizD** [comment]
Да можешь закрыть
