### ISSUE TITLE
Ошибка при вводе текста на закладке Содержание

### ISSUE THREAD

**Issue by dsv180** [BlizD/Tasks#28]
При создании задачи на закладке Содержание, в окно "Форматированный текст" скопировал текст. После переключения варианта на "Текст" и назад в "Форматированный текст" содержимое окна было очищено. Сама задача еще не была сохранена.

**Comment by BlizD** [comment]
Спасибо информацию. 
Постараюсь исправить в следующих релизах.

**Comment by BlizD** [comment]
Если есть желание можете сами исправить и я залью в основную ветку. 

Только если будете делать то см. инструкцию в readme.md

**Comment by dsv180** [comment]
я к сожалению не писатель, я читатель :-)
