### ISSUE TITLE
Добавить возможность изменения статуса задачи из контекстного меню  в канабан

### ISSUE THREAD

**Issue by UpworksTeam** [BlizD/Tasks#280]
Очень нужная вещь,  при работе через браузер

**Comment by RomanUpworksTeam** [comment]
https://drive.google.com/file/d/1pG2597IlDGmW3jq-pdTi2huBQBM_fwkS/view?usp=drivesdk

**Comment by BlizD** [comment]
Спасибо. Посмотрю на след выходных
