### ISSUE TITLE
Добавить возможность сохранять настройки канбан доски как отдельный вариант

### ISSUE THREAD

**Issue by BlizD** [BlizD/Tasks#283]
Добавить возможность сохранять настройки канбан доски как отдельный вариант.
Необходимо сохранять настройки отборов и настройки видимости колонок канбан доски.

![image](https://user-images.githubusercontent.com/10989306/109395791-57ed4480-793f-11eb-8b79-39924abe4350.png)

Идеально использовать подсистему вариантов отчета.
Это позволит передавать сохраненные настройки между пользователями.
![image](https://user-images.githubusercontent.com/10989306/109395712-da293900-793e-11eb-9ae2-b26fd1182b88.png)

**Comment by hawkxtreme** [comment]
Считаю, что сделать через типовой функционал сохранение вариантов невозможно т.к. требует много правок в типовом коде, который в свою очередь требует дальнейшего сопровождение при обновлении БСП.
Типовой код заточен только на ОТЧЕТ и реквизит "СхемаКомпоновкиДанных".

Сделал через "ХранилищеОбщихНастроек"

**Comment by BlizD** [comment]
Спасибо. Перенесу на выходных

**Comment by BlizD** [comment]
@hawkxtreme Изменения залил, немного подкорректировал код, отображение на форме (кнопки), а также сделал, чтобы текущий вариант настроек сохранялся автоматически при закрытии канбан доски.
Еще раз спасибо, за доработку.
![image](https://user-images.githubusercontent.com/10989306/216755711-ffb2b9c3-ff0d-46ad-826b-ecc7f3b66ed8.png)

**Comment by 7OH** [comment]
Возможно после обновления платформы или БСП в версии 2024.04.07.0 - сломалось.
Обработка.узКанбанДоска.МодульМенеджера строка 111
"ТекущийПользовательСтрока 	= "" + СтандартныеПодсистемыСервер.ТекущийПользователь();"
тут возвращает странные имена в виде "ФамилияИ; Полное имя"
Если заменить на
ТекущийПользовательСтрока 	= "" + СтандартныеПодсистемыСервер.ТекущийПользователь().Имя;
то появляется список ранее сохраненных вариантов - как при сохранении, так и при восстановлении
