### ISSUE TITLE
Табличное описание задачи

### ISSUE THREAD

**Issue by pihy86** [BlizD/Tasks#287]
Хоть в описании задачи и присутствует добавление таблицы, нахожу его не очень удобным. 
Предлагаю (и планирую) добавить добавить описание в виде табличного документа с возможностью форматирования.
![2021-06-02_0-15-37](https://user-images.githubusercontent.com/85196119/120391683-11412900-c338-11eb-9551-6be5589afefc.jpg)
[287_._01062021.docx](https://github.com/BlizD/Tasks/files/6580627/287_._01062021.docx)
[287.zip](https://github.com/BlizD/Tasks/files/6580633/287.zip)

**Comment by BlizD** [comment]
Добрый день.

**Comment by BlizD** [comment]
А можете сделать чтобы таблица была доступна для всех вариантов форматирования. И ее можно было скрывать и открывать. Скорее всего таблица нужна как доп пояснение к описанию задачи

**Comment by BlizD** [comment]
Саму доработку посмотрю на выходных

**Comment by BlizD** [comment]
Как вариант можно: код и таблица убрать из вариантов форматирования. Вынести их как галочки Да/Нет и чтобы можно было и код добавить и таблицу и описание.

**Comment by BlizD** [comment]
@pihy86 Юрий, добрый день.
Залил доработки. Спасибо.
На будущее 
* последний CF необходимо брать из задачи #123, т.к. там указан поставщик "Библиотека стандартных подсистем";
* номер релиза увеличивать не стоит, это выполняю самостоятельно.
* еще скорректирую форму, чтобы блок с кнопками можно было сворачивать.

**Comment by BlizD** [comment]
@pihy86 
Скорректировал форму, блок форматирование:
![image](https://user-images.githubusercontent.com/10989306/120882387-322ba780-c5e0-11eb-89e4-90cf75f64a0b.png)

**Comment by pihy86** [comment]
Спасибо. Я хотел сам переделать, но завалили работой и пока руки не дошли.
Получилось компактно (сворачиваемые настройки форматирование и меньше
строк).

сб, 5 июн. 2021 г. в 09:29, Anton Ivanov ***@***.***>:
