### ISSUE TITLE
Уведомление об ошибке `ТолькоПросмотрДляСодержанияЗадач`

### ISSUE THREAD

**Issue by bopoh13** [BlizD/Tasks#290]
| **Конфигурация:** | **Платформа:** | **Система:**
| :--- | :--- | :--- 
| Управление задачами (1.0.5.012) | 1С:Предприятие 8.3 (8.3.17.1851) | Microsoft Windows (6.1.7601)

**Последовательность действий:**
1. Щелкнуть на любую задачу
2. Изменить задачу (горячая клавиша в списке F2)

**Результат:**
* Сообщение
  > Ошибка! Не указано значение элемента "ТолькоПросмотрДляСодержанияЗадач", в константах
  
  ![Screenshort](https://user-images.githubusercontent.com/6163937/121370474-6f2bcd00-c945-11eb-9e16-d28da0722859.png)

**Дополнительные сведения:**
При создании новой задачи ошибок нет.

**Comment by BlizD** [comment]
@bopoh13 Спасибо, за информацию.

Да, это проблема решена в коммите 20dd9e78ea36f7b7fff445cfa8188dbc6b07f986 будет выпущена в следующих релизах.
Можете вручную установить Сервис - Настройки
![image](https://user-images.githubusercontent.com/10989306/121403167-53cfba80-c963-11eb-8368-6169fbb82220.png)
Далее "Устанавливать только просмотр для содержания у существующих задач" указать = НЕТ
![image](https://user-images.githubusercontent.com/10989306/121403305-706bf280-c963-11eb-98b4-60aca7b1f617.png)
