### ISSUE TITLE
При записи задачи в которой есть закладка код выдается ошибка 8.3.20.1549

### ISSUE THREAD

**Issue by BlizD** [BlizD/Tasks#295]
>FractonKireyev 21.10.21 12:03
Проблема в версии 1.0.5.015 при работе с ядром 8.3.20.1549
В задаче (не важно - новой или существовавшей ранее) на закладке "Содержание" включаю "Код". При этом появляется соответствующая закладка. Захожу на неё и что-то записываю либо оставляю пустой (для проявления ошибки это не важно). Нажимаю "Сохранить и закрыть" - всё закрывается нормально.
Открываю эту-же задачу, что-то изменяю (или не изменяю - не важно) но НЕ захожу на закладку "Код", нажимаю "Сохранить и закрыть" - получаю ошибку:
Метод объекта не обнаружен (getText)
{Справочник.узЗадачи.Форма.ФормаЭлемента.Форма(333)}:Объект.ТекстСодержанияКод = Элементы.КонсольКода_ПолеHTML.Документ.defaultView.getText();
Если открыть эту-же задачу, но зайти на закладку "Код" (не важно - изменять текст кода или нет) и нажать на "Сохранить и закрыть" - то ошибки не возникает.

> FractonKireyev 29.10.21 17:20 Добрый день!
Как исправить через изменения внешнего объекта - не анализировал.
Но есть такая идея для исправления: Существует всего 2 варианта поведения пользователя:
>1. Пользователь зашёл на закладку "Код" и, возможно, что-то изменил (или просто посмотрел) - в этой ситуации данная ошибка не происходит и всё корректно отрабатывает, нужное значение записывается в нужный реквизит.
>2. Пользователь не зашел на закладку "Код". Значит в нужном реквизите совершенно точно ничего не поменялось и перезаписывать его содержимое не надо. Это можно легко отследить через реквизит формы (добавить реквизит формы типа "Булево", устанавливать его в "Истина" только при активизации закладки "Код", а строку, где происходит ошибка, разрешать к выполнению только при значении "Истина" этого реквизита (через Если ... Тогда ... КонецЕсли)).

**Comment by Badya67** [comment]
В обработчике ПередЗаписью формы элемента справочника узЗадачи добавлена проверка заполнения реквизита формы "КонсольКода_АдресМакета" при заполнении реквизита объекта "ТекстСодержанияКод". Если вкладка "Код" не открывалась пользователем, то "КонсольКода_АдресМакета" будет пустой строкой.

Изменённые объекты:
1. Справочники.узЗадачи.Формы.ФормаЭлемента

https://disk.yandex.ru/d/vlQTxTOAjHQFhQ

**Comment by BlizD** [comment]
Спасибо. Залью в конфигурацию

**Comment by BlizD** [comment]
@Badya67 - код залил в основную ветку.
Еще раз спасибо за код.
Добавил Вас на основную страницу проекта.

![image](https://user-images.githubusercontent.com/10989306/189487894-fd33e183-ec49-4c29-83af-f240c95f7384.png)
