### ISSUE TITLE
Ошибка при получении письма без создания задачи

### ISSUE THREAD

**Issue by barnikZ** [BlizD/Tasks#296]
Добавил в базу учетную запись, по которой при получении письма не формируются автоматом задачи. При получении некоторых прошлых писем регламентным заданием письма не загружаются и возникает ошибка. Прочем возникает не на всех письмах 80% писем загрузилось без проблем, а 20% с ошибкой не загружались. 

Информация из в журнала регистрации: 

Ошибка при выполнении обработчика - 'ПередЗаписью'
по причине:
Поле объекта не обнаружено (Исполнитель)
{ОбщийМодуль.узОбщийМодульСервер.Модуль(877)}:	СобытияВИстории.Вставить("СтарыйИсполнитель",пЗадача.Исполнитель);
{ОбщийМодуль.узОбщийМодульСервер.Модуль(1309)}:	ОтправитьУведомлениеПередЗаписьюВходящегоПисьма(Источник);
{ОбщийМодуль.УправлениеЭлектроннойПочтой.Модуль(1541)}:		Письмо.Записать();
{ОбщийМодуль.УправлениеЭлектроннойПочтой.Модуль(902)}:					СозданноеПисьмо = ЗаписатьЭлектронноеПисьмо(ДанныеУчетнойЗаписи,
{ОбщийМодуль.УправлениеЭлектроннойПочтой.Модуль(1141)}:	ПолучитьПисьмаПоМассивуИдентификаторов(Почта,
{ОбщийМодуль.УправлениеЭлектроннойПочтой.Модуль(840)}:		ПолучитьПочтуПоПроколуPOP3(ДанныеУчетнойЗаписи, Почта, Получено, СтруктураМассивовСозданныхПисем);
{ОбщийМодуль.УправлениеЭлектроннойПочтой.Модуль(85)}:		ПолучитьПисьма(Выборка, Ложь, Получено, СтруктураМассивовПисем);

Решение:
в общем модуле "узОбщийМодульСервер" в процедуре "ОтправитьУведомлениеПередЗаписьюВходящегоПисьма" исправить код 

Если НЕ ЗначениеЗаполнено(пЗадача) Тогда
	Возврат;
Конецесли;

на 

Если ТипЗнч(пЗадача) <> Тип("СправочникСсылка.узЗадачи") тогда
	Возврат;
Конецесли;

**Comment by BlizD** [comment]
А что там сейчас приходит в пЗадача?

**Comment by barnikZ** [comment]
в фукнции "ЗаписатьЭлектронноеПисьмо" модуля "УправлениеЭлектроннойПочтой" вызывается процедура "ЗаполнитьПредметИКонтакты" она заполняет переменную "Предмет", которая через Доп. Свойства "узПредмет" передается  в записываемый объект письмо. 

![изображение](https://user-images.githubusercontent.com/93152302/141135106-61851dba-a787-4fc5-ad3c-bc8803c2cdfb.png)

в общем модуле "узОбщийМодульСервер" в процедуре "ОтправитьУведомлениеПередЗаписьюВходящегоПисьма" есть код присвоения пЗадачи, как раз перед предлагаемым исправлением.

![изображение](https://user-images.githubusercontent.com/93152302/141135473-d7e8278c-0137-4ef2-a6b8-ecc2544d3855.png)


Дальше не погружался...

**Comment by BlizD** [comment]
Добавил дополнительную проверку на тип предмета https://github.com/BlizD/Tasks/commit/ed2a8b5da38bf2bb92b54121d9c52814927c7c27
