### ISSUE TITLE
ошибка при включении RLS+обработка активности пользователя

### ISSUE THREAD

**Issue by barnikZ** [BlizD/Tasks#297]
если включить настройку ограничения RLS по "группам доступа задач" + включить "показывать активность пользователя на рабочем столе", то при входе пользователя с ограниченными правами возникает ошибка запуска обработка активности:

![изображение](https://user-images.githubusercontent.com/93152302/141176924-7ea88325-e20e-4d37-8d14-e7fc56276227.png)

**данные из журнала регистрации:**
{(93, 30)}: Поле не найдено "Т.СсылкаНаОбъект."
ЕСТЬNULL(Т.СсылкаНаОбъект.<<?>>, НЕОПРЕДЕЛЕНО) <> НЕОПРЕДЕЛЕНО
{Обработка.узАктивностьПользователя.Форма.Форма.Форма(117)}:	РезультатЗапроса = Запрос.Выполнить();
{Обработка.узАктивностьПользователя.Форма.Форма.Форма(73)}:	ЗаполнитьТаблицуАктивностей();	
{Обработка.узАктивностьПользователя.Форма.Форма.Форма(429)}:	ЗаполнитьНаСервере();

по причине:
Ошибка выполнения запроса
по причине:
Ошибка в ограничении доступа к данным.
объект: 'РегистрСведений.узАктивностиПользователей', поле: 'ДеньАктивности'; право: 'Чтение'
{(93, 30)}: Поле не найдено "Т.СсылкаНаОбъект."
ЕСТЬNULL(Т.СсылкаНаОбъект.<<?>>, НЕОПРЕДЕЛЕНО) <> НЕОПРЕДЕЛЕНО
по причине:
{(93, 30)}: Поле не найдено "Т.СсылкаНаОбъект."
ЕСТЬNULL(Т.СсылкаНаОбъект.<<?>>, НЕОПРЕДЕЛЕНО) <> НЕОПРЕДЕЛЕНО

**Профиль пользователя:**
![изображение](https://user-images.githubusercontent.com/93152302/141177145-01eb3359-c8f2-465b-ad91-281d0582c497.png)

**Comment by BlizD** [comment]
Принято. Спасибо

**Comment by BlizD** [comment]
Добрый день.
Не удается повторить проблему.

1С:Предприятие 8.3 (8.3.19.1150)
Управление задачами (1.0.5.015)

**Как тестировал**
1. Вариант работы "Стандартный" (при производительном, также ошибки нет) (рис. 1);
2. Включил отображение активности на рабочем столе (рис. 5) 
2. Создал пользователя "ТестРЛСИзменение" указал для него профиль "(УЗ) Пользователь с ограничениями доступа (Изменение)" (рис. 2 и рис .3 и рис. 4)
3. Зашел под пользователем "ТестРЛСИзменение" ошибки нет (рис. 6).
4. В списке задач только ограниченный список (рис. 7)

Рис. 1 
![image](https://user-images.githubusercontent.com/10989306/143670245-e550b8ec-7736-451d-927a-34c0151e3e0e.png)
Рис. 2 
![image](https://user-images.githubusercontent.com/10989306/143670274-59bf7663-c4a6-4167-a109-724ff314fd4e.png)
Рис. 3 
![image](https://user-images.githubusercontent.com/10989306/143670293-5d2390b0-9cf7-4207-b05f-275443af1412.png)
Рис. 4
![image](https://user-images.githubusercontent.com/10989306/143670318-9b3c421a-5d98-4f35-9b26-b214c6583237.png)
Рис. 5
![image](https://user-images.githubusercontent.com/10989306/143670341-d31fce70-3f09-408a-80ee-7f46051b776b.png)
Рис. 6 
![image](https://user-images.githubusercontent.com/10989306/143670366-eef6dcb2-0ab8-429b-bf4e-08915677352f.png)
Рис. 7
![image](https://user-images.githubusercontent.com/10989306/143670387-6579351f-1047-40b0-94bd-7eb5b248b920.png)

**Comment by BlizD** [comment]
>Николай Баранов: ошибка возникает если включить роль "(УЗ) Пользователь с ограничениями доступа (Чтение)".
в тексте ограничения доступа лишняя точка

![image](https://github.com/BlizD/Tasks/assets/10989306/0e0ef811-3bfb-4e1c-b21c-74697d07ea84)

**Comment by BlizD** [comment]
@barnikZ внес изменения, спасибо за информацию.
