### ISSUE TITLE
ошибка при включении RLS вариант "Производительный"+ регистрация новой задачи 

### ISSUE THREAD

**Issue by sartinsky** [BlizD/Tasks#298]
Суть проблемы: нельзя создать задачу(менять существующую дает). Выдает ошибку RLS
![image](https://user-images.githubusercontent.com/50014041/143248053-d4ede95f-0cd5-483f-8fae-e22949b7b0aa.png)

Пока писал, сам нашел причину. Вызов процедур создания записей РС "узАктивностиПользователей" происходит ранее запуска процедуры обновления доступов, вызываемой из формы задачи
![image](https://user-images.githubusercontent.com/50014041/143248397-effe30fb-dd36-464b-9c3b-c165429852d4.png)

**Comment by BlizD** [comment]
Спасибо. Если знаете как подправить пришлите измененный CF волью в основную поставку.

**Comment by sartinsky** [comment]
Дело в том, что тут вопрос концепции. Согласно ее, использование RLS  в производительном режиме требует выполнения операции обновления прав доступ "ПослеЗАписиНАСервере". А логика создания Задачи, предполагает создание наборов записей РС ДО указанного события. Я для себя просто ограничил такие события установкой привилегированного режима. А вот с точки зрения поставки даже не знаю.... Правильно было бы наполнение зависимых объектов перенести.... Исходя из того, что раз Задача записалась, то и контроль РЛС не нужен

**Comment by sartinsky** [comment]
Согласен. Я тогда еще обкатку проведу(внедряем) и правки закину сюда

**Comment by BlizD** [comment]
Отлично. Спасибо
