### ISSUE TITLE
Исправить ошибку функции "ОбновитьИсторию" релиз 1.0.1.005

### ISSUE THREAD

**Issue by BUDIVAL** [BlizD/Tasks#3]
Функция ошибочно возвращает таблицу значений ТЗСобытияВИстории, а ожидается структура СобытияВИстории.
Справочник -> узЗадачи -> Модуль объекта -> Функция ОбновитьИсторию() -> строка 86

**Comment by BlizD** [comment]
В релизе 1.0.1.006 ошибка должна уйти, пожалуйста проверьте.

**Comment by BlizD** [comment]
Забыл выгрузить в Git, ща выгружу

**Comment by BlizD** [comment]
Выгрузил в Git, можно смотреть.

**Comment by BUDIVAL** [comment]
Работает.

**Comment by BUDIVAL** [comment]
Хотел сам исправить, но еще не знаю как это делать в Git

**Comment by BlizD** [comment]
Хорошо, что работает. Закрываю задачу.
По поводу того как исправить в Git. В целом вроде как такая схема:
1) делаешь Fork (т.е. копия проекта уходит к тебе) 
2) далее ты вносишь изменения у себя
3) делаешь PullRequest чтобы перенести изменения из твоей копии в основную ветку проекта
4) я на своей стороне смотрю изменения которые сделали, если все ОК, принимаю их и заливаю их.

Возможно, в чем то ошибся, т.к. реально сам этого не пробовал как работает.
