### ISSUE TITLE
Привязать к задачам KPI

### ISSUE THREAD

**Issue by vbuoc** [BlizD/Tasks#30]
Есть мысль создать список показателей KPI с привязкой зарплаты сотрудников к KPI. Кому интересно?

**Comment by BlizD** [comment]
Хочется чтобы конфигурация помогала выполнять задачи. 
А KPI это как какая то "палка" которая должна подгонять/наказывать.
В моем понимание сотрудники должны быть сами заинтересованы работать, иначе задачи двигаться (выполняться) у них не будут, а это и так видно без KPI.

Если подытожить, то на данном этапе не хотелось бы встраивать какие то расчеты KPI в конфигурацию.
Если у Вас есть такое желание, то не против, только это должно быть реализовано опционально (допустим через функциональные опции).

**Comment by capitoshko** [comment]
KPI слодно автоматизировать.  У каждого свой подход к огрганизации  работы

**Comment by BlizD** [comment]
Мне нравится выражение "Для любой системы KPI существует такая стратегия b, что находится в зеленой зоне, но при этом сам проект через жопу идет в неизвестность." услышал у Максима Дорофеева
