### ISSUE TITLE
Включить историю изменений (платформенную) для задач, спринтов, вопросы ответы, спринты, выпуск релиза

### ISSUE THREAD

**Issue by BlizD** [BlizD/Tasks#305]
Включить историю изменений (платформенную) для задач, спринтов, вопросы ответы, спринты, выпуск релиза

**Comment by 7OH** [comment]
Включена история (с записью сразу) для: 
Справочники:
узЗадачи, узЗадачиПрисоединенныеФайлы, узСпринты, узВопросыОтветы, узВыпускРелизаПрисоединенныеФайлы, узПроекты
Документы: узВыпускРелиза, узВводФактаПоЗадаче
файл на яндексе - https://disk.yandex.ru/d/vQJM432w5_jqSg

**Comment by BlizD** [comment]
Залил изменения.
Отключил платформенную историю для реквизитов с типом ХранилищеЗначения, их не нужно версионировать.
