### ISSUE TITLE
Открытие задачи по ссылке

### ISSUE THREAD

**Issue by pallid** [BlizD/Tasks#31]
Если в содержании задачи есть ссылка на другую задачу - "#10220", что бы такой тег выделялся как ссылка на эту задачу. Либо в командной панели редактирования markdown добавить кнопку установки ссылки [#10220](e1cib/data/Справочник.узЗадачи?ref=b64ebc5ff475646111e7115cdf9a57e7), либо парсить текст содержания и программно преобразовывать #NNNNN в такую ссылку

**Comment by pallid** [comment]
```bsl
Процедура ЗаменитьТекстПоШаблону(Текст)
	
	сч = СтрЧислоВхождений(Текст, "#");
	
	Для й=0 По сч Цикл
		
		ПозицияТега = Найти(Текст, "#");
		ЕстьТегЗадачи = ПозицияТега > 0;
		ЗнакиПослеТега = Сред(Текст,ПозицияТега+1,9);
		
		ЗадачаСсылка = Справочники.Задачи.НайтиПоКоду(ЗнакиПослеТега, истина);
		СсылкаНаЗадачу = ПолучитьНавигационнуюСсылку(ЗадачаСсылка);
		
		ТекстСсылка = "<a href=v8tasks:"+СсылкаНаЗадачу+" style='text-decoration: underline'>"+"[]"+ЗнакиПослеТега+"</a>";
		
		Текст = СтрЗаменить(Текст, "#"+ЗнакиПослеТега, ТекстСсылка);
			
	КонецЦикла;
	
	Текст = СтрЗаменить(Текст, "[]", "#");
КонецПроцедуры
```

**Comment by BlizD** [comment]
Спасибо, постараюсь в ближайшее время добавить это. 
Может есть желание у Вас самому это реализовать?

**Comment by pallid** [comment]
Хорошо. Если начну делать, сообщу, что приступил.

**Comment by BlizD** [comment]
@pallid 
Не удалось такое провернуть, как только заменил на навигационные ссылки. При нажатии на них, 1с открывает explorer и пытается там открыть.

![image](https://cloud.githubusercontent.com/assets/10989306/25268663/3c1323b0-2682-11e7-9809-2dbd534e368f.png)

**Comment by BlizD** [comment]
@stepa86 @nixel2007 
Не знаете как это можно побороть?

**Comment by Stepa86** [comment]
@BlizD http://infostart.ru/public/586481/ в конце оно? И у тебя начало у ссылки странное

**Comment by pallid** [comment]
@BlizD Поле в котором надо нажимать должно быть ПолеHTMLДокумента, в переключатели Markdown попробуйте нажать, там вроде как раз ПолеHTMLДокумента.
И вроде бы переход работает при опции ТолькоПросмотр = Истина

**Comment by Stepa86** [comment]
@BlizD Попробуй без префикса "v8tasks:" . 1Ска сама должна понять, что это ссылка на внутренний объект и перейти на него

**Comment by pallid** [comment]
@Stepa86 @BlizD 
кусок из ДО
```bsl
&НаКлиенте
Процедура ПолеHTMLПриНажатии(Элемент, ДанныеСобытия, СтандартнаяОбработка)
	
	СтандартнаяОбработка = Ложь;
	Если Не ЗначениеЗаполнено(ДанныеСобытия.Href) Тогда 
		Возврат;
	КонецЕсли;	
	
	Если Найти(ДанныеСобытия.Href, "goods") Тогда
		Элементы.ГруппаСтраницы.ТекущаяСтраница = Элементы.СтраницаТовары;
		Возврат;
	ИначеЕсли Лев(ДанныеСобытия.Href, 6) <> "v8doc:" Тогда 
		Возврат;
	КонецЕсли;
	
	НавигационнаяСсылкаПоля = Сред(ДанныеСобытия.Href, 7);

````
"v8tasks:" - это как роутер где потом получаем НавигационнаяСсылкаПоля

**Comment by Stepa86** [comment]
@pallid В твоем примере явно стоит вырезка навигационной ссылки и дальше по коду наверняка идет ПерейтиПоНавигационнойСсылке( НавигационнаяСсылкаПоля ) , а @BlizD у себя не переопределяет ссылку, судя по открывшемуся ИЕ с префиксом в ссылке

**Comment by pallid** [comment]
@Stepa86 кусок с "goods" глянь. т.е для задачи это может быть переход в раздел "Вопросы и ответы"

**Comment by pallid** [comment]
@Stepa86 так и есть, потом переход, но не во всех случаях
```bsl
Если Найти(НавигационнаяСсылкаПоля, "releases") > 0 Тогда 	
				ПараметрыФормы = Новый Структура("Ключ", Объект.Релиз);
		ОткрытьФорму("Справочник.Релизы.ФормаОбъекта", ПараметрыФормы, Параметры.ЭтаФорма);
КонецЕсли;
```
Может быть и так

**Comment by Stepa86** [comment]
@pallid Да, и что? В ссылке можно что угодно зашифровать и как угодно потом распарсить при клике, но по умолчанию 1Ска просто переходит по ссылке, что и произошло в https://github.com/BlizD/Tasks/issues/31#issuecomment-296117956

**Comment by pallid** [comment]
Просто далее можно переход делать не только на задачи, но и на другие объекты

**Comment by Stepa86** [comment]
@pallid Еще раз. Я это все понимаю и знаю что и как делается. Но @BlizD спрашивает почему у него открылся ИЕ, и я отвечаю, что он открылся, потому что в ссылке есть префикс.

**Comment by Stepa86** [comment]
Нужно или префикс убрать или обработчик навесить и в нем обрабатывать

**Comment by pallid** [comment]
@Stepa86 и потому что это реквизит с типом ФорматированныйДокумент

**Comment by Stepa86** [comment]
@pallid Форматированный документ так же умеет в навигационный ссылки по умолчанию и у него так же можно это переопределить в обработчике

**Comment by pallid** [comment]
@Stepa86 Ооо, а как это, можно скрин где у него обработчик ПриНажатии?

**Comment by pallid** [comment]
Форматированный документ откроет только новое окно "БРАУЗЕРА"

**Comment by Stepa86** [comment]
@pallid Да, перепутал с форматированной строкой

**Comment by BlizD** [comment]
> @Stepa86 @BlizD
кусок из ДО
"v8tasks:" - это как роутер где потом получаем НавигационнаяСсылкаПоля

Понял, попробую, спасибо.

**Comment by Stepa86** [comment]
@pallid Если в форматированный документ вставить внешнюю навигационную ссылку, то можно открыть объект в 1Ске. Но окно експлорера все равно откроется. Если в реестре подшаманить слегка, как в http://infostart.ru/public/586481/

**Comment by pallid** [comment]
@Stepa86 спасибо, буду знать

**Comment by BlizD** [comment]
@pallid 
Получается, чтобы это реализовать мне надо отказываться от использования ФорматированногоДокумента? 
Что то на такие жертвы не готов=)

**Comment by BlizD** [comment]
Ну или делать по аналогии с Markdown - редактируем в одном окне, а смотрим в другом...

**Comment by pallid** [comment]
Ну и вообще, зачем ФорматированныйДокумент, если есть текст, markdown и его просмотр. По мне так с головой

**Comment by BlizD** [comment]
Проще в этом случае собрать все задачи в тексте HTML и показать их в отдельном поле и оттуда уже делать переходы

**Comment by BlizD** [comment]
> Ну и вообще, зачем ФорматированныйДокумент, если есть текст, markdown и его просмотр. По мне так с головой
Ну, все таки удобнее для пользователей это привычное "Word"-подобное редактирование
Особенно радует вставка картинки из буфера - она отрабатывает корректно.

**Comment by Stepa86** [comment]
Так редактировать можно в форматированном документе, а выводить только в html

**Comment by BlizD** [comment]
Пока реализовал вот так:
![default](https://cloud.githubusercontent.com/assets/10989306/25301727/47d85a8e-2737-11e7-801d-8c12f432372e.gif)
