### ISSUE TITLE
Связанные Задачи исчезает Связь задач при смене наименования

### ISSUE THREAD

**Issue by ComAz007** [BlizD/Tasks#311]
Версия конфигурации "Управление задачами" 1.0.5.016

**Как воспроизвести (Как сейчас)**
Если завести две задачи и связать одну с другой, то при смене Наименования задачи связь исчезает 
Регистр 
e1cib/list/РегистрСведений.узСвязанныеЗадачи
Очищается

**Как должно быть**

**Comment by BlizD** [comment]
Добрый день, 

пришлите скриншоты с ошибкой.
Наименование не учитывается при связывании.
Связь происходит если в тексе описания задачи есть "#НомерЗадачи"

Посмотрите, что указано для проблемной ситуации в регистре сведений 
e1cib/list/РегистрСведений.узСвязанныеЗадачи
![image](https://user-images.githubusercontent.com/10989306/226359102-7da628c6-2e6c-4b36-92e1-f1c6c99ce97c.png)

**Comment by ComAz007** [comment]
Связь происходит если в тексе описания задачи есть "#НомерЗадачи" - да я номер не указывал а связывал указывая связь непосредственно в регистре. 
![изображение](https://user-images.githubusercontent.com/74769318/226708328-1fb04e4b-c2cc-4d24-aabc-312b6f3893ec.png)
вот так связь вручную
![изображение](https://user-images.githubusercontent.com/74769318/226708591-8157c8f8-d79c-4314-9618-1cddf081637b.png)
после добавления 2 к наименованию задачи
![изображение](https://user-images.githubusercontent.com/74769318/226709092-4667564c-67a4-4edb-8d04-6bd1d53a519c.png)

[Ошибка_20230321213742.zip](https://github.com/BlizD/Tasks/files/11032451/_20230321213742.zip)
