### ISSUE TITLE
Нет прав на команду "узПрисоединенныеФайлыПисемПоЗадаче"

### ISSUE THREAD

**Issue by hawkxtreme** [BlizD/Tasks#312]
Версия конфигурации "Управление задачами" 1.0.5.016

**Как воспроизвести (Как сейчас)**
Создать профиль с неполными правами на таскер.
Создать вложение к задаче

**Как должно быть**
Под не полными правами должна быть возможность использования
* Команда "узПрисоединенныеФайлыПисемПоЗадаче"
* Общая форма "узПрисоединенныеФайлыПисемПоЗадаче"

**Comment by BlizD** [comment]
Привет, пришлешь cf с изменениями?

**Comment by BlizD** [comment]
>а там мелочи в роль "узПользователь" воткнул роли для объектов
Команда "узПрисоединенныеФайлыПисемПоЗадаче"
Общая форма "узПрисоединенныеФайлыПисемПоЗадаче"

**Comment by BlizD** [comment]
Внес изменения.
