### ISSUE TITLE
Обновление БСП до 3.1.9.277

### ISSUE THREAD

**Issue by pro1c** [BlizD/Tasks#319]
Обновление Библиотеки стандартных подсистем до версии 3.1.9

При обновлении может быть ошибка:

![image](https://github.com/BlizD/Tasks/assets/32923952/00fa82ac-b852-449a-899a-0c35abd1820c)

Для этого надо очистить регистр сведений "Значения групп доступа по умолчанию", для этого можно убрать из групп доступа участников. На своей только что развернутой базе не нашел лучшего решения.

не могу прицепить большой файл [1Cv8 БСП 3.1.9.179 + версионирование 20230119.cf](https://drive.google.com/file/d/1CnPstZq813ISBgrNspU7AINLA393cw-W/view?usp=sharing)

**Comment by pro1c** [comment]
не могу прицепить 150мб файл, поэтому [линк на файл на гугл диске](https://drive.google.com/file/d/1CnPstZq813ISBgrNspU7AINLA393cw-W/view?usp=sharing)

**Comment by BlizD** [comment]
@pro1c Виктор, спасибо.
Подскажите при обновлении с 3.0.3.184 на 3.1.9.179 Вы использовали следующую инструкцию?
https://its.1c.ru/db/metod8dev#content:5856:hdoc
_>Порядок перехода с предыдущей версии
Общий порядок обновления подсистем БСП, используемых в конфигурациях, до актуальной версии приведен в [документации](https://its.1c.ru/db/bspdoc). Особенности обновления с предыдущих версий описаны в файле UpdateSSL.htm, входящем к комплект поставки (в каталоге \ExtFiles\Docs). При обновлении «через» несколько версий, необходимо отработать инструкции разделов Переход с предыдущих версий файла UpdateSSL.htm последовательно для всех предыдущих версий библиотеки.
Для обновления версий БСП в прикладных решениях рекомендуется использовать специализированные инструменты, входящие в дистрибутив библиотеки:_

**Comment by pro1c** [comment]
https://drive.google.com/file/d/1AoPj0yO1pJCJf-Yl9Wdi4d1f4PUd2ne4/view?usp=sharing
Файл не пролезает, по ссылке с гугл диска

**Comment by BlizD** [comment]
У меня еще ругнулся на регистр 

Записи регистра сведений стали неуникальными: узНаличиеЗаметокПоПредмету

![image](https://github.com/BlizD/Tasks/assets/10989306/7ee82ba9-8c1d-4665-a54b-d189c2e0390c)

**Comment by BlizD** [comment]
Пользовательские виды содержат тип, не соответствующий типу значений плана видов характеристик: ДополнительныеРеквизитыИСведения

**Comment by BlizD** [comment]
Минимальная платформа 8.3.22.1923
![image](https://github.com/BlizD/Tasks/assets/10989306/c815ca28-3faa-4ced-9404-15ffa4df636e)

**Comment by BlizD** [comment]
Процедура "Справочники.Пользователи.ОбработатьДанныеДляПереходаНаНовуюВерсию" обработки данных завершилась с ошибкой:

Произошло зацикливание процедуры обработки данных. Выполнение прервано.
{ОбщийМодуль.ОбновлениеИнформационнойБазыСлужебный.Модуль(10859)}:ВызватьИсключение ТекстИсключения;
{ОбщийМодуль.ОбновлениеИнформационнойБазыСлужебный.Модуль(4967)}:ПослеЗапускаПроцедурыОбработкиДанных(КонтекстОбработчика, КонтекстОбработчика.ИмяОбработчика);
{ОбщийМодуль.ОбновлениеИнформационнойБазыСлужебный.Модуль(10399)}:ЗавершитьВыполнениеОтложенногоОбработчика(КонтекстОбработчика, АдресРезультата);
{ОбщийМодуль.ОбновлениеИнформационнойБазыСлужебный.Модуль(587)}:ОбработчикиВыполнялись = ВыполнитьОтложенныйОбработчикОбновления(ПараметрыОбновления); // @skip-check query-in-loop - выполнение отложенных обработчиков.
{ОбщийМодуль.ОбновлениеИнформационнойБазыСлужебный.Модуль(2562)}:ВыполнитьОтложенноеОбновлениеСейчас(Параметры);
{ОбщийМодуль.ОбновлениеИнформационнойБазыСлужебный.Модуль(111)}:ВыполнитьДействияПриОбновленииИнформационнойБазы(ПараметрыОбновления, ДополнительныеПараметры);
{ОбщийМодуль.ОбновлениеИнформационнойБазыСлужебный.Модуль(2891)}:Результат = ВыполнитьОбновлениеИнформационнойБазы(ПараметрыОбновления);
{(1)}:ОбновлениеИнформационнойБазыСлужебный.ВыполнитьОбновлениеИнформационнойБазыВФоне(Параметры[0],Параметры[1])
{ОбщийМодуль.ОбщегоНазначения.Модуль(5940)}:Выполнить ИмяМетода + "(" + ПараметрыСтрока + ")";
{ОбщийМодуль.ДлительныеОперации.Модуль(1693)}:ОбщегоНазначения.ВыполнитьМетодКонфигурации(ИмяПроцедуры, ПараметрыВызова);
{ОбщийМодуль.ДлительныеОперации.Модуль(1672)}:ВызватьПроцедуру(ВсеПараметры.ИмяПроцедуры, ВсеПараметры.ПараметрыПроцедуры, ПараметрыВыполнения);

[ОшибкаВоВремяВыполненияВстроенногоЯзыка, ИсключениеВызванноеИзВстроенногоЯзыка]

**Comment by BlizD** [comment]
![image](https://github.com/BlizD/Tasks/assets/10989306/a991be28-5d69-4e59-bd0b-c8ed6485498c)

**Comment by BlizD** [comment]
Проблема была с пользователями в которых указан одинаковый адрес электронной почты

**Comment by BlizD** [comment]
Режим совместимости Версия 8.3.21

**Comment by BlizD** [comment]
Выпустил тестовый релиз 1.0.5.020 в которой выполнено обновление БСП до 3.1.9.179 
Минимальная платформа 8.3.22.1923
Режим совместимости теперь 8.3.21

Скачать тестовый релиз 1.0.5.020 https://drive.google.com/file/d/18Szfs6vIGdXjdUNGJhqPRqCKSLnBrMrS/view?usp=sharing

**Comment by tahallus** [comment]
Почему нельзя удалить явно не используемые объекты ?
Например объекты ниже, действительно нужны в конфигурации про учет задач.
АктОбУничтоженииПерсональныхДанных
СогласиеНаОбработкуПерсональныхДанных
ОтзывСогласияНаОбработкуПерсональныхДанных

**Comment by BlizD** [comment]
> Почему нельзя удалить явно не используемые Подсистема ? Например подсистема "Защита персональных данных" (часть объектов из подсистемы ниже), действительно нужны в конфигурации про учет задач. АктОбУничтоженииПерсональныхДанных СогласиеНаОбработкуПерсональныхДанных ОтзывСогласияНаОбработкуПерсональныхДанных

Добрый день, @tahallus.
Да, вначале так и было, были только подсистемы нужные.
Но это очень большая проблема при обновлении БСП на новый релиз, слишком много трудозатрат по обновлению.
Поэтому принято решение брать БСП целиком без вырезаний.

**Comment by ViktorErmakov** [comment]
Я уже точно не помню, но было несколько проблем при обновлении.
У меня уже  стояла версия УЗ предыдущая, скачал cfu обновление, обновил и начались ошибки которых не было.
То что я написал в телеге:
"Обновился, слетел определяемый тип шаблоны, справочник задачи пропал. Так же в шаблон не уходят комментарии в задачах, и еще внешняя ссылка на задачу  формируется как внутренняя."
Все проблемы связаны с отправкой писем по задачам, это то что я тестил пока.
№1. Вот первая проблема, после обновления пропадает назначение шаблона такое как "Задача", до обновления оно было.
![image](https://github.com/BlizD/Tasks/assets/39617680/67754f4b-f346-4ba5-847b-44cf911a1f3b)
Это из за того, что в определяемом типе "ПредметШаблонаСообщения" пропал тип "узЗадачи"
![image](https://github.com/BlizD/Tasks/assets/39617680/31ad71e8-f841-437c-ba50-e7aba0f8db68)

№2. Вот вторая проблема отсюда пропала ссылка вроде на справочник "Задачи" или какая то ссылка была полезная.
![image](https://github.com/BlizD/Tasks/assets/39617680/c1a750c9-d462-4e75-9129-ad3273a6b63b)

№3. Еще вроде бы была проблема что если в задаче оставить комментарий, то он в письме перестал уходить, но это надо проверить.

№4. Внешняя ссылка на задачу формировалась как внутренняя, т.е. не полная.

**Comment by BlizD** [comment]
@pro1c да, много объектов не были перенесены при обновлении на БСП
Взял базу разработки до обновления на БСП.
Запустил сравнение с конфигурацией поставщика.
Показало расхождения.
По определяемым типам много объектов, которые не перенесены в новую БСП:
* ВладелецДополнительныхСведений
* ВладелецКонтактнойИнформации
* ПредметНапоминания	
* ПредметНапоминанияОбъект
Еще 
* ХранилищеВариантовОтчетов
* НапоминанияПользователяПереопределяемый
* ОбменДаннымиПереопределяемый
* ОбновлениеИнформационнойБазыКлиентПереопределяемый
* ИспользоватьШаблоныСообщений
* ОграничиватьДоступНаУровнеЗаписей
* и т.д.

Очень много объектов из прошлой БСП не перенесены в новую БСП.
Необходимо повторно выполнять перенос с учетом адаптированных объектов.

![image](https://github.com/BlizD/Tasks/assets/10989306/add342aa-e0aa-40b6-8db3-fae05cb36849)

**Comment by pro1c** [comment]
принято, нужно переделать

**Comment by pro1c** [comment]
1. Обновил "с нуля" поэтому взял крайнюю 3.1.9.277
2. Версия УправлениеЗадачами изменена на 1.0.5.023
3. Модуль "РаботаСФайлами" переименован, поэтому если делать через "сравнение и объединение" ругается что удаляемы модуль включен в подсистему - я просто загрузил новую конфигурацию
4. Некоторые моменты переработаны в соответствии с отчетом о проверке внедрения. Отчет выдает пару ошибок, но думаю они не критичны

**Требуется проверка после обновления!**

файл CF выложен на диске
https://drive.google.com/file/d/1r4EYydxbjbLyaDYH374LwkFd1boD7F7C/view?usp=sharing

**Comment by pro1c** [comment]
Исправлена ошибка в модуле работы с почтой.
https://drive.google.com/file/d/1Vgc-Sm04YoWcvUvol_L48AFy1_SkQFQh/view?usp=sharing

**Comment by BlizD** [comment]
Залил изменения, выпустил релиз 

Коллеги, 

выпущена тестовая версия 1.0.5.023 в которой обновлена БСП до версии 3.1.9.277 и теперь режим совместимости 8.3.21.

Минимальная версия платформы 8.3.22.1923, 8.3.21.1775, 8.3.24.1342, 8.3.23.2040

Спасибо @victor_qeos.

Прошу на копии своих баз проверить обновление, если обнаружите проблемы, прошу писать их в задачу (https://github.com/BlizD/Tasks/issues/319)

Скачать тестовый релиз 1.0.5.023 (https://drive.google.com/file/d/12QJp5OhkHvmNPlMWnp4z5c8iiRBHIGsN/view?usp=sharing)

**Comment by ViktorErmakov** [comment]
как протестите все, отпишитесь пожалуйста, пока некогда тестить новый релиз.
