### ISSUE TITLE
Доска канбан на HTML

### ISSUE THREAD

**Issue by ViktorErmakov** [BlizD/Tasks#326]
1. Добавить опционально доску канбан на HTML. Доска от 1С не очень красивая, и перетаскивание работает кое как.
Делаю это самостоятельно, возможно сделаю как библиотеку встраиваемую в любое решение/конфигурацию.

**Если хотите сами выполнить доработку, то укажите следующие шаги**
1. Если по задаче необходимы новые метаданные, то необходимо написать ТЗ на это и отправить в задачу ([пример ТЗ](https://github.com/BlizD/Tasks/files/2544687/117_._031118.docx))
1. Возьмите последний CF из дев ветки в задаче [#123](https://github.com/BlizD/Tasks/issues/123)
1. Выполните доработку в этом CF;
1. Укажите в задаче список измененных объектов метаданных;
1. Прикрепите к созданной задачи Ваш CF.
1. Спасибо за Ваш, вклад в разработку;

Код необходимо обрамлять в следующем формате: 
```
// [+] #1014 Иванов А.Б. 2016-04-06
//Старый код
....НовыйКод....
// [-] #1014 Иванов А.Б. 2016-04-06
```

Обрамлять необходимо каждую новую функцию и процедуру это важно при сравнении объединении.

**Comment by BlizD** [comment]
@ViktorErmakov - предлагаю Вам вынести это в отдельное расширение.

Канбан доску - намеренно делал только средствами 1с, чтобы ее могли легко дорабатывать все участники.

Также прошу обратить внимание на уже реализованные канбан доски HTML на инфостарте - там их было несколько, возможно там уже Ваши идеи реализованы.

**Comment by ViktorErmakov** [comment]
> @ViktorErmakov - предлагаю Вам вынести это в отдельное расширение.
Да, думаю сделать в виде расширение если позволят ограничения. 
 
> Канбан доску - намеренно делал только средствами 1с, чтобы ее могли легко дорабатывать все участники.
В настоящее время хороший 1Сник еще знает HTML, это видно по инфостарту и гитхабу))

> Также прошу обратить внимание на уже реализованные канбан доски HTML на инфостарте - там их было несколько, возможно там уже Ваши идеи реализованы.
Вбил сегодня поиск, да канбан досок много, но такой что я хочу именно нет, что бы была универсальная, можно было встроить в любую конфигурацию.

**Comment by ViktorErmakov** [comment]
Закрываю задачу, т.к. она будет делаться в другом репозитории, спасибо!)
