### ISSUE TITLE
Убрать старые не используемые реквизиты "Спринт", "Удалить_ИспользоватьФорматированиеВСодержании", "Удалить_ЧасыФакт"  в задаче

### ISSUE THREAD

**Issue by 7OH** [BlizD/Tasks#328]
Версия конфигурации "Управление задачами"
Управление задачами (2024.04.07.0)

**Как воспроизвести (Как сейчас)**
1. Открыть канбан доску
2. На вкладке "Настройки" добавить отбор "Задача.Спринт" и выбрать значение из задачи, которая была видна в списках на доске
3. Возвращаемся на доску - пусто
4. Меняем отбор на "Спринт"  - отбор отлично работает.

**Как должно быть**
Должно работать и так и так.
Попутно в обычном выборе, который работает - не хватает поля ПРОЕКТ, из-за чего была попытка настроить отбор через точку - что и привело к наблюдаемой проблеме.

**Comment by 7OH** [comment]
1. Пора удалять реквизит "Удалить_Спринт" из справочника "узЗадачи". Синоним у него старый и путает.
2. Что-то надо решить с реквизитом Проект с этом же справочнике. На форме показывает значение, а данных нет. Похоже при открытии тянет из основной задачи. Может записывать подчиненным это поле ??

**Comment by BlizD** [comment]
#328 Убрал старые не используемые реквизиты "Удалить_Спринт", "Удалить_ИспользоватьФорматированиеВСодержании", "Удалить_ЧасыФакт" в задаче

**Comment by BlizD** [comment]
Вернул реквизиты.
