### ISSUE TITLE
Отчет "Факт по задачам" с выводом комментариев (примечаний)

### ISSUE THREAD

**Issue by 7OH** [BlizD/Tasks#332]
Иногда просят отчет не только в виде итоговых часов, а именно с расшифровкой - когда и что сделано.
Разработчик оставляет рядом с часами комментарий, но в отчете сейчас этого не видно.
Готов предоставить CF с доработкой

**Comment by 7OH** [comment]
Изменения:
Отчеты.узОтчетПоЗадачам.Макеты.ОсновнаяСхемаКомпоновкиДанных
добавлено необязательное соединение с таблицей регистра РегистрНакопления.узФактПоЗадачам и поле Примечание из этой таблицы.
Файл - на диске https://disk.yandex.ru/d/zOoO-zo3i6OPmg

**Comment by 7OH** [comment]
Необязательным полем не выходит - заменил обороты на таблицу.
Возможно для оптимального решения - использовать свой отчет как внешний ?
Если да - закрывайте задачу, но охота из коробки уметь показывать детальную информацию тоже

**Comment by BlizD** [comment]
_>Необязательным полем не выходит - заменил обороты на таблицу.
Возможно для оптимального решения - использовать свой отчет как внешний ?
Если да - закрывайте задачу, но охота из коробки уметь показывать детальную информацию тоже_

Мне кажется для детализации лучше создать отдельный отчет.

**Comment by 7OH** [comment]
> Мне кажется для детализации лучше создать отдельный отчет.

Такой же рядом с суффиксом - (Детальный) - нормально будет ?

**Comment by BlizD** [comment]
Давай назовем его "Отчет по задачам и часам с комментариями"

**Comment by 7OH** [comment]
Доработку скинуть или есть возможность новый отчет в виде копии с указанным наименованием принять?

**Comment by BlizD** [comment]
_>Доработку скинуть или есть возможность доработанный отчет в виде копии с указанным наименованием принять?_

Да, нужно скинуть доработку.
Может лучше этот отчет как то "облегчить", чтобы выводилось меньше информации, чем в основном отчете?
Например вывести только 
Задача, ЧасыФакт, КомментарийПоЧасам?

**Comment by 7OH** [comment]
Ну остальное скд же обрежет
Возможно кому-то надо будет и остальная информация.
В текущем отчете не хватает только вот тех комментариев - "что именно было сделано".
Сложно понять - насколько обрезать надо.

**Comment by 7OH** [comment]
![изображение](https://github.com/BlizD/Tasks/assets/3063507/13064a4c-eb81-401f-9554-a792f1bebc8e)
Нормально по итогу ?
Если не обрезать функционал - файл готов

**Comment by BlizD** [comment]
Да, кидай. 
Когда буду заливать еще подумаю.
Сегодня у меня время уже закончилось свободное.

**Comment by 7OH** [comment]
Выложил доработку - https://disk.yandex.ru/d/drKxdB6JCfvPMw

**Comment by BlizD** [comment]
В таком виде не готов заливать.
В новом отчете ресурсы "Часы (план)", "Часы к оплате", "Количество задач" - начинают показывать неверные данные

![image](https://github.com/BlizD/Tasks/assets/10989306/c3dbf959-21ee-4670-9cc8-fb7488f6f7d8)

В качестве альтернативы реализовал отчет "Факт по задачам" с выборкой только по регистру узФактПоЗадачам с возможностью расшифровки до регистратора.

![image](https://github.com/BlizD/Tasks/assets/10989306/6a0b07a3-5325-4ef6-be60-8c29d5c5f01d)


[узФактПоЗадачам_040524.zip](https://github.com/BlizD/Tasks/files/15208403/_040524.zip)
