### ISSUE TITLE
Не видно сохраненных настроек КанБан доски если ИмяПользователяИБ отличается от ФИО пользователя (изменен ключ привязки к пользователю) 

### ISSUE THREAD

**Issue by 7OH** [BlizD/Tasks#333]
Управление задачами (2024.04.07.0)

**Как воспроизвести (Как сейчас)**

Получение настроек происходит по странному имени, похожему на "%ИмяПользователяИБ%;%ИмяПользователяИзСправочника%".

Удаление варианта настроек пытается найти по "%ИмяПользователяИзСправочника%".

Сохранение варианта всем - по имени пользователя справочника.

Сама же система сохраняет настройки только по %ИмяПользователяИБ%, если не указывать.

**Как должно быть**

Должно быть так, как в системе.

**Comment by 7OH** [comment]
Изменения:
Обработка.узКанбанДоска.Форма
ФормаДинамическая - сохранение всем на сервере
ФормаЗагрузкиВарианта - удаление варианта
МодульМенеджера - ПолучитьСписокВариантов

Файл на диске - https://disk.yandex.ru/d/1Qy56DjNXb0OIw

**Comment by BlizD** [comment]
@7OH  У меня вроде ок, ошибки нет.
![image](https://github.com/BlizD/Tasks/assets/10989306/301b0b42-e18b-44cb-8dd3-bc46dad1f67f)

Варианты тоже есть

![image](https://github.com/BlizD/Tasks/assets/10989306/caeafccf-d1b6-461b-9c69-61390b2d0034)

**Comment by 7OH** [comment]
Надо проверить с пользователем, у которого имя ИБ и имя в справочнике не совпадает (завели с шибкой, смена фамилии и прочее).
У меня старая база была, где на своём же пользователе и попался на такое поведение.

**Comment by 7OH** [comment]
Провел тест на дев ветке
![изображение](https://github.com/BlizD/Tasks/assets/3063507/ab17cbaa-01aa-406d-9f59-999056cf8a2c)
Сохранил вариант настройки - вижу для выбора
далее меняем имя пользователю в справочнике - вариантов необходимости можно придумать пачку.
![изображение](https://github.com/BlizD/Tasks/assets/3063507/1c638dc7-13cb-4920-b7e4-bba8fe4e5a7e)
И при загрузке пусто для выбора.
Сама платформа сохраняет с именем ИБ - возможно не стОит отклоняться от этой практики ?

**Comment by BlizD** [comment]
>И при загрузке пусто для выбора.
Сама платформа сохраняет с именем ИБ - возможно не стОит отклоняться от этой практики ?


Да, было бы правильнее имя ИБ. Если изменять, то как перенести исторические настройки?

**Comment by 7OH** [comment]
Мне ИР не показал почему-то сохраненное для других пользователей.
Да - обработку по переносу надо подумать

**Comment by BlizD** [comment]
> Да - обработку по переносу надо подумать

Без обработки, вносить изменения будет означать потерю сохраненных настроек для тех у кого сейчас все работает.

**Comment by 7OH** [comment]
Думал на неделе.
По сути сейчас у всех работает и будет работать (у тех , у кого имена совпадают - иначе бы уже спрашивали массово).
А вот у кого не совпадает - у тех как раз не работает, но таких мало мои они скромно молчат.
Проблема же только у того, у кого имена разные.

**Comment by BlizD** [comment]
>По сути сейчас у всех работает и будет работать (у тех , у кого имена совпадают - иначе бы уже спрашивали массово).
А вот у кого не совпадает - у тех как раз не работает, но таких мало или они скромно молчат.
Проблема же только у того, у кого имена разные.

А можно как то использовать оба варианта сохранения и чтения настроек?

**Comment by 7OH** [comment]
А зачем оба? Старый работает только для совпадающих. Новый (типовой) для обоих

**Comment by BlizD** [comment]
@7OH чтобы не сломать сохраненные настройки у которых все работает

**Comment by BlizD** [comment]
Переделал сохранение и восстановление настроек на имя пользователя ИБ.

Старые сохраненные настройки, если имя ИБ отличается от имени пользователя, то их нужно заново настроить.
