### ISSUE TITLE
Возможность видеть в отчете по задачам Проект

### ISSUE THREAD

**Issue by 7OH** [BlizD/Tasks#334]
В отчете по задачам однозначного поля проект нет.
В задаче оно определяется через выбор по основной задаче.
Охота использовать так же - одним полем.

**Comment by 7OH** [comment]
Добавил в макет отчета поле через выбор
Файл на диске - https://disk.yandex.ru/d/gCbhKAbLj1tp_A

**Comment by BlizD** [comment]
Залил изменения. Спасибо.
Добавил еще в быстрые отборы "Проект"

![image](https://github.com/BlizD/Tasks/assets/10989306/d5b360ab-2245-4489-a076-c72e6d2bb963)
