### ISSUE TITLE
Ошибка параметра сеанса узЗапретитьВводФактаДляОсновныхЗадач

### ISSUE THREAD

**Issue by 7OH** [BlizD/Tasks#335]
Управление задачами (2024.04.07.0)

**Как воспроизвести (Как сейчас)**

Попытаться внести факт по задаче, подчиненной основной.
Текст ошибки
`Ошибка при выполнении обработчика - 'ОбработкаПроверкиЗаполнения'
по причине:
Ошибка при получении значения атрибута контекста (узЗапретитьВводФактаДляОсновныхЗадач)
{Документ.узВводФактаПоЗадаче.МодульОбъекта(28)}:Если ПараметрыСеанса.узЗапретитьВводФактаДляОсновныхЗадач Тогда

[ОшибкаВоВремяВыполненияВстроенногоЯзыка]
по причине:
Попытка получения неинициализированного значения параметра сеанса
[ОшибкаИспользованияВстроенногоЯзыка]`

В процедуру установки параметра сеанса (при этом не по имени , а сводно) - код не заходит.

**Как должно быть**

Ошибки быть не должно - параметр должен устанавливаться в процедуре установки параметров при запросе его по имени.

**Comment by 7OH** [comment]
Могу предложить на рассмотрение решение.
Изменения в общих модулях:
ОбщегоНазначенияПереопределяемый - добавлен обработчик для параметров "уз*" в модуль узОбщийМодульСервер
узОбщийМодульСервер - Заменена процедура УстановкаПараметровСеанса. Добавлены параметры, код установки по имени и убрано узВыполнитьНастройкуПанелей - эта штука должна выполняться где-то в другом месте (а так как она по сути и не вызывалась - значит можно жить и без неё).
Файл на диске - https://disk.yandex.ru/d/21JedgD6k20nUg

**Comment by BlizD** [comment]
Немного адаптировал код, залил изменения. Спасибо.
