### ISSUE TITLE
(Дубль задачи) Выбор сохраненных настроек в канбан доске не показывается

### ISSUE THREAD

**Issue by BlizD** [BlizD/Tasks#336]
Возможно после обновления платформы или БСП в версии 2024.04.07.0 - сломалось.
Обработка.узКанбанДоска.МодульМенеджера строка 111
"ТекущийПользовательСтрока 	= "" + СтандартныеПодсистемыСервер.ТекущийПользователь();"
тут возвращает странные имена в виде "ФамилияИ; Полное имя"
Если заменить на
ТекущийПользовательСтрока 	= "" + СтандартныеПодсистемыСервер.ТекущийПользователь().Имя;
то появляется список ранее сохраненных вариантов - как при сохранении, так и при восстановлении

_Originally posted by @7OH in https://github.com/BlizD/Tasks/issues/283#issuecomment-2053762904_

**Comment by BlizD** [comment]
@7OH  У меня вроде ок, ошибки нет.
![image](https://github.com/BlizD/Tasks/assets/10989306/301b0b42-e18b-44cb-8dd3-bc46dad1f67f)

Варианты тоже есть

![image](https://github.com/BlizD/Tasks/assets/10989306/caeafccf-d1b6-461b-9c69-61390b2d0034)

**Comment by 7OH** [comment]
> У меня вроде ок, ошибки нет.

А у вас имя пользователя ИБ совпадает с именем в справочнике ? 
Я проверял на старой базе.
У меня нет - потому ошибку видел, наверное. 
Попробую на чистом релизе к обеду ещё раз.

**Comment by BlizD** [comment]
Давай в рамках этой задачи обсуждать
Не видно сохраненных настроек КанБан доски #333
