### ISSUE TITLE
Не запускается канбан доска на 2024.04.20.0

### ISSUE THREAD

**Issue by serg33rus** [BlizD/Tasks#337]
После обновления Канбан доска валится с ошибкой.
Полный текст отчета об ошибке прилагается.
Откатился на 2024.04.07.0 - все работает штатно.

[Report.json](https://github.com/BlizD/Tasks/files/15047875/Report.json)

**Comment by 7OH** [comment]
Можем быстро починить, а можем правильно, но долго.
Если быстро, то ищем строку под было и меняем на
`// [+] #337 Павлюков С.Ю. 2024-04-20
// было
//НужныйЦвет = Задача.Удалить_Спринт.ЦветСпринта.Получить();
//неоптимально, так как через получение таблицы работает
текущийСпринт = Справочники.узСпринты.ПолучитьТекущийСпринтДляЗадачи(ТекущаяДата(), Задача);
НужныйЦвет = ?(ЗначениеЗаполнено(текущийСпринт), текущийСпринт.ЦветСпринта.Получить(), НужныйЦвет);
// [-] #337 Павлюков С.Ю. 2024-04-20`

**Comment by BlizD** [comment]
В канбан доске поправил, чтобы спринт брался правильно.
Но реквизиты в задачу также вернул.

**Comment by BlizD** [comment]
Промежуточный релиз
[Tasks_2024.04.20.1.zip](https://drive.google.com/file/d/12NzlnsmgFvsz7Cnclv4TUQQG3aSBV4QM/view?usp=sharing)
