### ISSUE TITLE
После обновления на с 1.0.5.хх до 2024.04.хх отключается Система взаимодействия.

### ISSUE THREAD

**Issue by serg33rus** [BlizD/Tasks#338]
После обновления показывает что СВ вообще не подключена.
Судя по всему слетают настройки.
Чтобы решить проблему ПЕРЕД обновлением с помощью внешней обработки сохранить настройки подключения к СВ, а после обновления ей же восстановить настройки подключения.
Проверено - метод рабочий. 
Обработка в файлике.
[Сохранение подключения к системе взаимодействия.zip](https://github.com/BlizD/Tasks/files/15047881/default.zip)

**Comment by BlizD** [comment]
Спасибо за инструкцию.
