### ISSUE TITLE
Не открывается отчет узГрафикСгоранияСпринта на 2024.04.20.0

### ISSUE THREAD

**Issue by 7OH** [BlizD/Tasks#339]
![изображение](https://github.com/BlizD/Tasks/assets/3063507/62185db5-3b6c-45a8-9a6e-8551f21f0ec3)
Ошибка похожая на #337

**Comment by BlizD** [comment]
Вернул реквизит "Удалить_Спринт" https://github.com/BlizD/Tasks/issues/337
