### ISSUE TITLE
Многострочные комментарии при указании факта по задачам

### ISSUE THREAD

**Issue by 7OH** [BlizD/Tasks#341]
При выполнении задачи комментарий можно ввести многострочным.
Но в регистре узФактПоЗадачам оно хранится уже без.
Так же можно в форме документа узВводФактаПоЗадаче показывать ранее введённый комментарий целиком.

Задачу создал под коммит

**Comment by 7OH** [comment]
#341
Многострочные комментарии в выполнении задач

Изменения:
РегистрыСведений.узФактПоЗадачам.Реквизит.Примечание
	МногострочныйРежим = Истина
Документы.узВводФактаПоЗадаче.Форма.ФормаДокумента
	РеквизитФормы.ДанныеПримечание.МногострочныйРежим = Истина

https://disk.yandex.ru/d/-w5bgc6-3Yk3Bw

**Comment by BlizD** [comment]
Залил изменения.
