### ISSUE TITLE
Определение основной задачи, теперь учитывается возможность отсутствия у родителей основной задачи

### ISSUE THREAD

**Issue by 7OH** [BlizD/Tasks#342]
Версия конфигурации "Управление задачами": 2024.04.20.1
**Как воспроизвести (Как сейчас)**

Добавить в иерархии задача несколько уровней без галки "Это Основная Задача"
Добавить ниже задачу с галкой.
У задач выше будет проставлена основная задача, наследуемая выше.
![изображение](https://github.com/user-attachments/assets/3eeebb7b-fac4-4b3a-b256-126ba58b7970)

**Как должно быть**
Простановка основной задачи должна учитывать галку "это основная задача"

**Comment by 7OH** [comment]
#342
Основная задача без причины

Изменения:
Справочники.узЗадачи.МодульОбъекта
	ПолучитьОсновнуюЗадачу
		Поправил логику, чтобы учитывало возможность отсутствия у родителей основной задачи

https://disk.yandex.ru/d/2O7_NkxX-Z0d_Q

**Comment by BlizD** [comment]
Залил изменения
