### ISSUE TITLE
При переходе из задачи во вкладку взаимодействие и создании письма на основании созданного шаблона выходит ошибка.

### ISSUE THREAD

**Issue by PahomovAA** [BlizD/Tasks#343]
Версия конфигурации Управление задачами (2024.05.11.1)

При переходе из задачи во вкладку взаимодействие и создании письма на основании созданного шаблона выходит ошибка.
![image](https://github.com/user-attachments/assets/94648262-11fb-4bd0-8625-67804fc86b3f)
[ЕШ_00001.zip](https://github.com/user-attachments/files/17529777/_00001.zip)

**Comment by BlizD** [comment]
Залил изменения
