### ISSUE TITLE
Устранение ошибки перехода к странице Вопросы и ответы при не записанной задаче

### ISSUE THREAD

**Issue by PahomovAA** [BlizD/Tasks#344]
Версия конфигурации Управление задачами (2024.05.11.1)

1. При создании новой задачи не записывая её перейти на вкладку "Вопросы и ответы", вылетает ошибка.
![image](https://github.com/user-attachments/assets/4e510ea7-0658-4929-928f-b549ebfc7b31)

2. В вопросах и ответах не учитываются помеченные на удаление вопросы и ответы.
[ЕШ_00002.zip](https://github.com/user-attachments/files/17529780/_00002.zip)

**Comment by BlizD** [comment]
Залил изменения
