### ISSUE TITLE
Быстрое переключение настроек в КанБан доске

### ISSUE THREAD

**Issue by 7OH** [BlizD/Tasks#345]
На форму канбан доски вынесли панель с динамически формируемыми кнопками загрузки ранее сохраненных настроек.
Данное действие уменьшит количество нажатых кнопок для загрузки ранее сохраненного варианта.
Сейчас надо переключить вкладку на настройки, в подменю найти кнопку загрузки, в открывшейся форме найти нужную настройку, загрузить и опять сменить вкладку.

**Comment by 7OH** [comment]
ГруппаКанбанДоска - вернул группировку вертикальную - не было вообще.
Добавлен реквизит КомандыВариантов (СписокЗначений) для хранения списка команд
Небольшие правки в модуле формы.
https://disk.yandex.ru/d/bzDHZ06RZkVpqw

**Comment by BlizD** [comment]
Залил изменения. Спасибо.
![FastButtonKanban](https://github.com/user-attachments/assets/87b062be-74a3-4583-8b04-df76695e66f7)

**Comment by BlizD** [comment]
@7OH 

Промежуточный релиз 
[Tasks_2024.11.17.1.zip](https://drive.google.com/file/d/1m0Yyswb7270JzXU_IG-7sGYo9WWFlQpl/view?usp=sharing)
