### ISSUE TITLE
При чтении сохраненных вариантов под обычным пользователем, выдается ошибка

### ISSUE THREAD

**Issue by ComAz007** [BlizD/Tasks#347]
Версия конфигурации "Управление задачами"
![image](https://github.com/user-attachments/assets/499588f2-f268-4acb-96ce-d1815190a8c5)

С какими ролями воспроизводится ошибка
![image](https://github.com/user-attachments/assets/e7de68ef-0dc5-494c-b030-21cc17c2605c)

![image](https://github.com/user-attachments/assets/55b17525-b06c-4e1e-95e5-68af116d28f6)

![image](https://github.com/user-attachments/assets/37398c26-fba5-4103-8d61-354a6092eb28)

**Как воспроизвести (Как сейчас)**
У пользователя с правами выше не открывается Канбан доска.
Описание проблемы
При входе в приложение выдает ошибка доступа. Канбан доска не открывается.

Шаги воспроизведения
Скрины
При входе сообщение
![image](https://github.com/user-attachments/assets/374d7d95-5782-4519-9eb1-8fddfb0bf5ad)

в конфигураторе кидает на эти строки
![image](https://github.com/user-attachments/assets/46ca8d3d-c3ea-4977-a400-f9315bf91ef9)

Выставление у профиля Уз_Пользователь "Администрирование данных" частично решает проблему Пользователь обычный не Админ (права выше показаны)
![image](https://github.com/user-attachments/assets/09439259-5f1f-4a82-98bc-f3ed20c049c8)

Хоть и стало пускать в канбан нет кнопок с вариантами Кабана у обычного пользователя(Права Выше)
![image](https://github.com/user-attachments/assets/7c9c8ecd-3c7e-47f5-b2c6-76fee84207f2)

Полный текст ошибки

**Так же дополнительно, ошибка после перехода с версии (1.0.5.016) на версию (2024.11.04.1)**

**Как должно быть**
Открываться Канбан Доска и наличие возможности сохранять отборы

**Comment by ComAz007** [comment]
Так же дополнительно, ошибка после перехода с версии (1.0.5.016) на версию (2024.11.04.1)

**Comment by BlizD** [comment]
@ComAz007, добрый день.

>У пользователя с правами выше не открывается Канбан доска.
При входе в приложение выдает ошибка доступа. Канбан доска не открывается.

Добавил право "Администрирование данных" в роли узПользователь, узПользовательОграничениеДоступаЧтение, узПользовательОграничениеДоступаИзменение

Переделал сохранение и восстановление настроек на имя пользователя ИБ.
Старые сохраненные настройки, если имя ИБ отличается от имени пользователя, то их нужно заново настроить.

Чуть позже пришлю тестовый релиз, чтобы проверить ушла ли ошибка у Вас.

>Так же дополнительно, ошибка после перехода с версии (1.0.5.016) на версию (2024.11.04.1)

Какая ошибка?
Можете в рамках нового тикета (задачи) описать проблему?

**Comment by BlizD** [comment]
@ComAz007 

Попробуйте промежуточный релиз, проблема должна уйти.
[Tasks_2024.11.17.1.zip](https://drive.google.com/file/d/1m0Yyswb7270JzXU_IG-7sGYo9WWFlQpl/view?usp=sharing)

**Comment by RuDaVa** [comment]
Проблема ушла!

**Comment by BlizD** [comment]
Отлично, закрываю.
