### ISSUE TITLE
При открытии канбан доски выдается ошибка прав доступа для пользователя (RLS)

### ISSUE THREAD

**Issue by BlizD** [BlizD/Tasks#349]
Доброе время суток Антон
эта ошибка возникает не на всех установках, но я ее несколько раз ловил ,
вот ссылка на DT ку , в ней точно есть
https://disk.yandex.com/d/u1ehcrZZhS4eVg ,
записал   действия, там при вызове канбана и вылезала ошибка у всех
пользователей с правами как на прицепном скрине :
![2024-11-16_19-54-35](https://github.com/user-attachments/assets/e80156aa-a2f7-4cde-8080-2829952da6ba)
https://disk.yandex.com/i/8W5RnejRwxDBGg
Дополнительные параметры запуска ввел
"/с ЗапуститьОбновлениеИнформационнойБазы"
но не ушло, все как было

_Originally posted by @RuDaVa in https://github.com/BlizD/Tasks/issues/348#issuecomment-2480607447_

**Comment by BlizD** [comment]
@RuDaVa

Проблема из за ошибки по задаче "#347 При чтении сохраненных вариантов под обычным пользователем, выдается ошибка".
Пришлю тестовый релиз, проверите уходит или нет.

**Comment by BlizD** [comment]
@RuDaVa

Попробуйте промежуточный релиз, проблема должна уйти.
[Tasks_2024.11.17.1.zip](https://drive.google.com/file/d/1m0Yyswb7270JzXU_IG-7sGYo9WWFlQpl/view?usp=sharing)

**Comment by RuDaVa** [comment]
Да ошибка, после обновления, ушла, здорово!

**Comment by BlizD** [comment]
Отлично, закрываю задачу.
