### ISSUE TITLE
В версии Tasks 2024.11.17.1 не отбирается список  "Группы доступа задач"

### ISSUE THREAD

**Issue by RuDaVa** [BlizD/Tasks#350]
Версия конфигурации "Управление задачами"
2024.11.17.1
файловая 
платформа 8.3.25.1445
Если есть доп. расширения, прошу приложить к задаче их.
Нет
С какими ролями воспроизводится ошибка
(УЗ) Пользователь с ограничениями доступа (Изменение)

Описание проблемы
в версии Управление задачами (2024.05.11.1) при выборе в закладке Задачи >>  Дополнительно в поле на "Группа доступа", в форме "Группы доступа задач" если у пользователя доступ ограничен "Профилем", то список ограничен выбором приписанной "группой доступа". В версии Управление задачами (2024.11.17.1) данный список не "не фильтруется" . Пользователь может присвоить новой задаче не свою группу доступа к задаче..

 

![2024-11-17_18-02-12](https://github.com/user-attachments/assets/300d689c-9c58-46eb-90be-6ac034f1f743)

**Comment by BlizD** [comment]
@RuDaVa 

Не удается повторить проблему, можешь прислать выгрузку DT?

**Как тестировал**

Конфигурация 
Управление задачами (2024.11.17.1)
Под пользователем "Назар Агаджанов"

1. Права пользователя 
![image](https://github.com/user-attachments/assets/0fa03316-530c-4b26-9106-c2372b4d4d35)

2. Ограничение доступа = грд.Азар
![image](https://github.com/user-attachments/assets/5b223dc5-f82d-4ccc-ad10-ac7b4388f197)

3. Доступны только группы = грд.Азар
![image](https://github.com/user-attachments/assets/cb8139d4-0c92-4366-b655-faa92992087f)

**Comment by BlizD** [comment]
>но я понял что дело в в роли , стояла роль (уз) Пользователь а не пользователь с (УЗ) Пользователь с ограничениями доступа (Изменение) и потому так, так что это я видимо недопонял..

Получается проблемы нет, все ок?

**Comment by RuDaVa** [comment]
Да, гоняю неделю, все норм
