### ISSUE TITLE
Отчет диаграммма по проектам, где видно сколько сделано задач по каждому проекту

### ISSUE THREAD

**Issue by BlizD** [BlizD/Tasks#39]
Отчет диаграмма по проектам, где видно сколько сделано задач по каждому проекту

![image](https://cloud.githubusercontent.com/assets/10989306/26725842/1b1c385c-47a9-11e7-8241-676c035909ad.png)

**Comment by Dimanchik00** [comment]
Может лучше показать количество и проценты по отношению к основной задаче?  Можно тогда получить по всей иерархии проекта(основной задачи) картину состояния

**Comment by BlizD** [comment]
@Dimanchik00 
Думаю, да можно и проценты, другой вопрос, что от чего считать процент.
Если считать от общего числа задач по основной задачи, то в нашем случае не подойдет, т.к. задачи добавляются по мере выполнения проекта.

**Comment by JohnyDeath** [comment]
А может как во всяких гитлабах/зенхабах добавить "Вехи" (Milestones)?
https://docs.gitlab.com/ce/user/project/milestones/
И потом наслаждаться примерно таким графиком:
<img width="1007" alt="burndown_chart 1" src="https://user-images.githubusercontent.com/5936030/29701907-392f88c0-8977-11e7-8a51-f201d4ea992d.png">

**Comment by BlizD** [comment]
@JohnyDeath 
Уже есть задача по созданию Burndown диаграммы #44 
Это оно?

**Comment by JohnyDeath** [comment]
@BlizD да, наверное.

P.S. Все-таки надо мне поближе ознакомиться с архитектурой конфигурации. А то вот уже и боянить начинаю.

**Comment by BlizD** [comment]
@JohnyDeath 
Тут же хотелось бы видеть другой график, есть ли движения по проектам, не по отдельным спринтам.

**Comment by Dimanchik00** [comment]
> Если считать от общего числа задач по основной задачи, то в нашем случае не подойдет, т.к. задачи добавляются по мере выполнения проекта.

Для нас подойдет.

**Comment by capitoshko** [comment]
Считать процент выполнения можно по уже внесённых задачах.

Эта задача ещё актуальная?

**Comment by capitoshko** [comment]
?

**Comment by BlizD** [comment]
Пока не актуальна

**Comment by capitoshko** [comment]
Может закроем задачу?
