### ISSUE TITLE
Перенести cf и cfu из репозитория в гитхаб релизы

### ISSUE THREAD

**Issue by nixel2007** [BlizD/Tasks#4]
Извиняюсь, что со своим уставом, но аж глаза резануло. 
Причины:
* бинарники в гит - это не хорошо. Диффы по ним не посмотреть, нужны они раз в пятилетку, а раз используется механизм поставок, то скорее всего эти бинарники параллельно лежат в шаблонах конфигурации 
* стремительно растёт размер репозитория и страдает время выкачивания для доработки или CI/CD

Ни в коем случае не наезд, скорее дружеский совет. Больше конфигураций на гитхабе хороших и разных.

**Comment by BlizD** [comment]
Добрый день, Никита.

Согласен с Вами. 
Правда мне пока некуда убрать бинарники (cf, cfu, exe поставку) из гит. 
Сейчас они лежат в гит, чтобы у пользователей была возможность скачать нужный им релиз.
Надо подумать куда их вынести. 

Спасибо за совет.

P.S. спасибо за отличный доклад на Инфостарт =)

**Comment by nixel2007** [comment]
Если выбрать раздел code на гитхабе, то можно увидеть кнопку releases. Там по тегу или коммиту гита можно создать release или pre-release и приложить бинарные файлы. 

Пожалуйста :) надеюсь, что-то из сказанного как можно больше людей начнёт применять :)

**Comment by BlizD** [comment]
Спасибо, буду пробовать=)
В ближайшее время уберу из гит бинарники, Переделаю на релизы.

**Comment by BlizD** [comment]
Убрал бинарники.
