### ISSUE TITLE
Неодинаковый размер кнопок в форме задачи

### ISSUE THREAD

**Issue by pallid** [BlizD/Tasks#41]
1С:Предприятие 8.3 (8.3.10.2505)
Управление задачами (1.0.3.021)

![image](https://user-images.githubusercontent.com/4147815/28987236-1c23ce44-7973-11e7-81bf-7a2978634eef.png)

Возможно это проблема только моей текущей платформы, на других не проверял

**Comment by pallid** [comment]
Проверил, действительно размер кнопки увеличивается только в 8.3.10

**Comment by BlizD** [comment]
@pallid 
Да, об этой проблеме писали на инфостарте, в единичном порядке ее поправил, но новый релиз еще не выложил.
Спасибо, что написал, сейчас свои изменения выложу и твои в пул реквесте тоже приму.

**Comment by BlizD** [comment]
Перенес изменения в Dev ветку
