### ISSUE TITLE
Подскажите нужна ли возможность Экспорта/Импорта задач из Excel?

### ISSUE THREAD

**Issue by BlizD** [BlizD/Tasks#45]
Подскажите нужна ли возможность Экспорта/Импорта задач из Excel?

**Comment by pallid** [comment]
Для первоначального заполнения базы по мне так можно и обработкой ЗагрузкаИзТабличногоДокумента обойтись

**Comment by pallid** [comment]
А для импорта можно отчет по задачам сохранить в xls

**Comment by pallid** [comment]
Т.е экспорта

**Comment by Dimanchik00** [comment]
Согласен с @pallid . Можно Типовыми средствами можно воспользоваться.

**Comment by BlizD** [comment]
Ок. спасибо, тогда закрываю
