### ISSUE TITLE
Новая команда "Открыть папку задачи на диске"

### ISSUE THREAD

**Issue by BlizD** [BlizD/Tasks#51]
Открывать для задачи папку на диске продолжение задачи #38

**Comment by pallid** [comment]
@BlizD открывать после создания или новая команда Открыть папку задачи?

**Comment by BlizD** [comment]
@pallid 
Новая команда "Открыть папку на диске".
* Папку для задачи надо искать в каталоге пользователя по ключу
`#+[НомерЗадачи]`
А не пытаться построить иерархию как в задаче #38 и ее открывать.
* Также надо выдавать сообщение если не найдена папка или найдено более 1 папки с номером такой задачи.

**Comment by BlizD** [comment]
@pallid не увидел изменений в макете узСловарьПоУмолчанию

**Comment by BlizD** [comment]
{Обработка.узКанбанДоска.Форма.ФормаДинамическая.Форма(250)}: Поле объекта не обнаружено (Текст101)
	пКомандаОткрытьПапкуЗадачиНаДиске.Заголовок=СтруктураСообщений.Текст101;

**Comment by pallid** [comment]
@BlizD Забыл закоммитить, сегодня постараюсь добавить

**Comment by BlizD** [comment]
@palid Отлично, спасибо.

**Comment by BlizD** [comment]
@pallid ругается, что есть 2 папки по задаче, хотя вторая папка, это файл для задачи.

![image](https://user-images.githubusercontent.com/10989306/31089773-fbf6130c-a7ad-11e7-866b-4d1fbba967e6.png)

**Comment by BlizD** [comment]
@pallid 
Отлично, все работает, залил изменения в дев ветку.
Тебе надо дев релиз скинуть?

**Comment by pallid** [comment]
@BlizD супер.
Не, спасибо

**Comment by pallid** [comment]
@BlizD я к сожалению еще пока не пользуюсь конфигурацией. Если что и релиза дождусь
