### ISSUE TITLE
Дополнительные реквизиты к задаче - в отчет отдельной колонкой

### ISSUE THREAD

**Issue by Dimanchik00** [BlizD/Tasks#54]
При разработке задачи выполняют пользователи с разными ролями (PM, Dev, BA), причем один и тот же пользователь в маленькой команде на разных задачах может быть с различными ролями.
Попробовали с помощью доп реквизитов расширить аналитику задачи. В отчет доп реквизит к задаче в отдельную колонку так и не смогли вывести.

**Comment by nixel2007** [comment]
> В отчет доп реквизит к задаче в отдельную колонку так и не смогли вывести.

Доп реквизиты добавлены как характеристики в объект?

**Comment by Dimanchik00** [comment]
@nixel2007 Как "Дополнительный реквизит". Все как обычно. На  форме задачи все ок. В отчете если группировкой отдельной делать, то в принципе получается.
