### ISSUE TITLE
Настройка отображения задания на доске

### ISSUE THREAD

**Issue by exterani** [BlizD/Tasks#57]
Было бы очень удобно, если бы в шапку задания на доске можно было вывести родителя задания, а не только основное.
и исполнителя перенести из шапки вниз

а в идеале сделать какую-то настройку, как рисовать задание

**Comment by BlizD** [comment]
Спасибо за предложение. 
Думал об этом. 
Если кто то захочет реализовать это. Подумаем как лучше это сделать.

**Comment by capitoshko** [comment]
это разве не готовое?
