### ISSUE TITLE
Ошибка при открытии обработки "Канбан доска"

### ISSUE THREAD

**Issue by BUDIVAL** [BlizD/Tasks#6]
Если в справочнике "Статусы задачи" есть хоть один не предопределенный элемент, то выскакивает ошибка.

**Comment by BUDIVAL** [comment]
Если проблема не срочная, оставьте, я сделаю через pull request.
Хочу потренироваться :)

**Comment by BlizD** [comment]
Пока обработка "Канбан доска" не будет формироваться динамически. 
Добавлять новые элементы в справочник "Статусы задачи" нет смысла.
Но ошибку надо подправить.

**Comment by BlizD** [comment]
Перенес твои изменения в обработку "Канбан доски". Не через pull request.
