### ISSUE TITLE
Заполнять текст задачи при смене с текста на форматированный текст 

### ISSUE THREAD

**Issue by BlizD** [BlizD/Tasks#64]
Александр Иванов (seducer)  77 06.10.17 16:36

Есть один момент. Пишем что-нибудь на вкладке "Содержание" в режиме форматированного текста. Переключаемся на режим "текст". Все нормально, введенный текст отобразился. Переключаемся обратно в режим форматированного текста и введенный текст не отображается.

**Comment by pallid** [comment]
[тут](https://github.com/BlizD/Tasks/blob/00a94ab29e232f0aa26d1daf67c33bee90a7bdf6/src/cf/Catalogs/%D1%83%D0%B7%D0%97%D0%B0%D0%B4%D0%B0%D1%87%D0%B8/Forms/%D0%A4%D0%BE%D1%80%D0%BC%D0%B0%D0%AD%D0%BB%D0%B5%D0%BC%D0%B5%D0%BD%D1%82%D0%B0/Ext/Form/Module.bsl#L871)

строку
```
ФорматированныйТекст = Объект.ТекстСодержания;
```

поменять на 
```
ФорматированныйТекст.УстановитьHTML(Объект.ТекстСодержания, Новый Структура);
```

только вернется голый текст, без прежнего форматирования.

**Comment by pallid** [comment]
Может вообще сделать глобальную настройку, типа формат Оформления задачи.
И на форме выводить только один из трех вариантов.

**Comment by pallid** [comment]
Или можно сделать предупреждение при смене формата на форме, что все форматирование сделанное ранее не сохраниться, а только содержание.

**Comment by BlizD** [comment]
@pallid да этого будет достаточно

**Comment by Kim1C** [comment]
Думаю можно закрыть это (#64) ишуз и также #28 ))

**Comment by BlizD** [comment]
@Kim1C да, ток сначала проверю.

**Comment by BlizD** [comment]
@Kim1C обновил дев ветку, задачу закрываю.
Еще раз спасибо=)
