### ISSUE TITLE
Уведомления (Нова задача, изменен статус, добавлен комментарий, ect...)

### ISSUE THREAD

**Issue by pallid** [BlizD/Tasks#67]
Хотелось бы иметь возможность получать уведомления на почту:
- при создании новой задачи 
- при изменении статуса задачи (опционально)
- при добавлении комментария (т.е адресованного вопроса)
- при закрытии задачи

**Comment by BlizD** [comment]
@pallid 
Привет, 

расскажу как сейчас есть, потом допишем чего не хватает.
>при создании новой задачи

Когда отправляется:
* Отправляются "Исполнителю" задачи и он не сам ее создал
* Если задача отражена в статусе в котором указаны наблюдатели. В этом случае наблюдателям за этим статусом будут отправлены уведомления.

>при изменении статуса задачи (опционально)

Когда отправляется:
* Исполнителю - если не он сам двинул задачу;
* Наблюдателям за задачей - если кто то указал что следит именно за этой задачей, и не он двинул задачу;
* Наблюдателям за статусом;

>при добавлении комментария (т.е адресованного вопроса)

Когда отправляется:
* Исполнителю;
* Наблюдателю за задачей;

>при закрытии задачи

Когда отправляется:
* Наблюдателю за статусом;
* Наблюдателю за задачей;

**Comment by BlizD** [comment]
Возможно, что то неправильно написал, но в целом подход такой:
Уведомление отправляются:

* Исполнителю;
* Наблюдателю за задачей;
* Наблюдателю за статусом;

**Comment by BlizD** [comment]
@pallid 
Расписал в Wiki как уведомления должны рассылаться
https://github.com/BlizD/Tasks/wiki/Уведомления

**Comment by pallid** [comment]
@BlizD Понял, спасибо большое
