### ISSUE TITLE
Реализовать возможность указать наблюдателя за основной задачей

### ISSUE THREAD

**Issue by BlizD** [BlizD/Tasks#68]
Реализовать возможность указать наблюдателя за основной задачей.

**Как сейчас**

Сейчас можно указать наблюдателя за задачей. В этом случае уведомление будет рассылаться только если будет изменена именно эта задача.
Схема какие сейчас уведомления приходят: https://github.com/BlizD/Tasks/wiki/Уведомления

**Как надо**

Если указали наблюдателя за задачей и эта задача является основной (реквизит в задаче ЭтоОсновнаяЗадача). 
Это должно означать, что мы наблюдаем за всеми задачами в этой основной задаче.

**Comment by BlizD** [comment]
№284 Добавить возможность указывать Наблюдателя за основной задачей

**Comment by capitoshko** [comment]
Я попробую сделать. Заодно разберусь с выгрузкой на gitnub своих изменений. В жизни пригодиться.

**Comment by BlizD** [comment]
@capitoshko вроде это уже реализовано

**Comment by BlizD** [comment]
@capitoshko единственно как понял лучше на 1 задачу делать отдельную ветку и именно ее уже отправлять через pull request

**Comment by BlizD** [comment]
Тогда не будет проблем с внесением исправлений и т.п.

**Comment by capitoshko** [comment]
Так это делать или нет?

**Comment by BlizD** [comment]
Нет, это уже реализовано.
