### ISSUE TITLE
Пересмотр структуры папок

### ISSUE THREAD

**Issue by BUDIVAL** [BlizD/Tasks#7]
Предлагаю перенести файлы выгруженной конфигурации из папки «src» в папку «src\cf» т.к. если использовать «precommit1c» все обработки разбираются в папку «src» и получается каша.

**Comment by BlizD** [comment]
Думаю лучше разбирать обработки в папку src_epf. 
Для этого в файле pre-commit указать папку src_epf

`#!/bin/sh
echo "Start hooks before commit for v8unpack erf and epf"
#python.exe .git/hooks/pyv8unpack.py --g --index
oscript -encoding=utf-8 .git/hooks/v8files-extractor.os --git-precommit epf_epf`

**Comment by nixel2007** [comment]
Такс. Вижу, коммит сделан из консоли, айда переделывать

**Comment by nixel2007** [comment]
1. Git reset --hard HEAD~1
2. Git push -f

Это чтобы восстановить историю на предыдущщий шаг

**Comment by nixel2007** [comment]
Далее, если перемещение делается из консоли, то тут два выхода. 
1. Перемещать файлы не в проводнике, а потом делать обычный Git add, а выполнить переименование через `git mv src src/cf`. Потом уже git add
2. Если все же перемещать через проводник, то для `git add` нужно добавлять какой-то специальный флаг, который я на вскидку не помню, поэтому рекомендую первый вариант.

**Comment by nixel2007** [comment]
P.S. Совсем забыл, что SourceTree это делает автоматически, а при ручной работе надо это контроллировать

**Comment by BlizD** [comment]
Делал через SourceTree.

**Comment by nixel2007** [comment]
@BlizD в окне staged files были розовые иконки R (переименование)?

**Comment by BlizD** [comment]
Да, были

**Comment by BlizD** [comment]
Вот скрин 
[http://f1.s.qip.ru/m9euvvIj.png](url)

**Comment by nixel2007** [comment]
Хм... Действительно, гитхаб не добавляет параметр --follow к команде git log. Из-за этого не выводится полная история файла. Причём просят это аж с 2010 года. Что любопытно, git blame показывает все коммиты, даже предшествующие переименованию. 

Вот здесь есть ссылка на экстеншн для хрома, но в целом ситуация не очень приятная http://stackoverflow.com/questions/17213046/see-history-in-github-after-folder-rename

Решений я вижу два - либо все же использовать для обработок отдельную папку src_epf, как было предложено, либо же смириться с таким неудобством на данном этапе развития продукта (на сколько я понимаю - относительно относительно молодой)

**Comment by BlizD** [comment]
Да, я готов пойти на такие "жертвы". 
Раз ты говоришь, что уже есть некий стандарт src\cf.
