### ISSUE TITLE
№260 Новая строка в текущих делах должна добавляться в тек строку а не в конец списка

### ISSUE THREAD

**Issue by BlizD** [BlizD/Tasks#71]
№260 Новая строка в текущих делах должна добавляться в тек строку а не в конец списка

**Comment by 7OH** [comment]
Вопрос - куда добавлять ?
Выше выделенной строки или ниже ?
И какую считать нужной при множественном выделении ?

**Comment by BlizD** [comment]
@7OH  это не надо делать. Это уже работает.
