### ISSUE TITLE
Расширение функционала

### ISSUE THREAD

**Issue by Kim1C** [BlizD/Tasks#75]
Добрый день.
Планируется ли расширение функционала конфигурации?
На данный момент используем вашу конфигурацию (по крайней мере стараюсь внедрить в полноценную работу) в своей команде. И вот стало понятно, что часть задач приходят от пользователей. Часть из них надо делать т.к. это ошибка релиза, часть - надо анализировать руководителю для того, чтобы понять делать сейчас, поставить в очередь либо поднять вопрос на совещании для понятия необходимости данной доработки. 
Для учета обращений вижу отдельный документ/справочник, который бы содержал время, суть и пользователя, который обратился. и на основании данного обращения создавалась задача - которую и необходимо выполнять и тратить на нее время. 
Есть ли в планах движение куда-то в эту сторону?

**Comment by BlizD** [comment]
Да такие планы есть. 
Это то что буду делать следующее.

**Comment by Kim1C** [comment]
Не буду спрашивать про приблизительные сроки, но данный вопрос мне очень интересен. Я думаю, можно объединить наши усилия

**Comment by BlizD** [comment]
@Kim1C 
Да, по срокам мне сообщить сложно.

>Я думаю, можно объединить наши усилия
Отлично.

**Comment by capitoshko** [comment]
Если делать. то у же как бизнес - процесс. Есть обращение - создаеться задача. и она уже двигает объекты системы.

**Comment by capitoshko** [comment]
Я вот пробую вносить пробные задания. И все думаю - а что если справочник задачи сделать аналогом user story, и если задачу берут в спринт - тогда запускаеться бизнес - процес работі над заданием из заведомо определеннім набором действий. В существующей редакции такие єтапі как разработка, тестирование, сдача функц3іонала приходиться всегда вносить или руководителю или ответственному. Можна забіть что-то внести, можна заведомо и целеустремленно не внести все єтапі. Такое ручное управление не очень хорошо. Какое мнение ваше?

Вопрос также общий - система оказалась непопулярной? я так понимаю мало кто хочеть участвовать в ее безплатной разработке?

**Comment by BlizD** [comment]
@capitoshko 
По поводу:
>И все думаю - а что если справочник задачи сделать аналогом user story, и если задачу берут в спринт - тогда запускаеться бизнес - процес работі над заданием из заведомо определеннім набором действий. В существующей редакции такие єтапі как разработка, тестирование, сдача функц3іонала приходиться всегда вносить или руководителю или ответственному. Можна забіть что-то внести, можна заведомо и целеустремленно не внести все єтапі. Такое ручное управление не очень хорошо. Какое мнение ваше?

Правильно ли понимаю, что необходимо, чтобы задача, жестко переходила из одного этапа в другой. Верно?
С другой стороны, что мешает сотруднику просто последовательно передвинуть из одного этапа в другой уже на финале задачи? 
В текущем варианте сотрудник может перевести из любого статуса в любой другой, каких то ограничений не накладывается. 
Если действительно требуется ограничить выбор следующего и предыдущего статуса, то лучше это реализовывать через отдельную функциональную опцию, также необходимо понимать, где именно задавать очередность статусов (в спринте? в основной задаче(проекте)? или для каждой задачи своя очередность?)
В нашем случае это не требуется, пользователи тоже об этом не просили. Но в целом не против если бы была такая возможность. Единственное, это реализовывать без создания бизнес процесса.

>Вопрос также общий - система оказалась непопулярной? я так понимаю мало кто хочеть участвовать в ее безплатной разработке?

Мне сложно судить о популярности могу лишь сказать, что скачали ее около 1000-1500 раз.
По поводу бесплатной доработки, это да, мало кто хочет бесплатно это делать, так как это тоже требует времени.

**Comment by capitoshko** [comment]
Давайте. Вы правы. Попробую так.

Буду дорабатывать. Думаю, что такие проекты должны быть. Мы всё-таки не одними деньгами должны жыть

**Comment by capitoshko** [comment]
Есть ещё вид статуса. Это удобно. Верно ли понимаю, что статусы и в другой статусов можно добавлять вручную?

**Comment by capitoshko** [comment]
У нас исполнителей задач несколько. Есть аналитик, который ставит задачу. Есть программист, который пишет код, есть тестировщик. В существующей длгике каждому исполнителю нужно создавать отдельные задачи по одной user story.

Менеджера интересует реализация конкретной фичи и на какой стадии задачи в каждого исполнителя, потому что каждый сотрудник тратит время на реализацию.

Нам логика работы только со статусами недостаточна

**Comment by BlizD** [comment]
@capitoshko 
>Есть ещё вид статуса. Это удобно. Верно ли понимаю, что статусы и в другой статусов можно добавлять вручную?

Новые статусы добавлять можно. 
А вот новые Виды статусов (Backlog, В работе, Готово) сейчас добавлять нельзя.

>У нас исполнителей задач несколько. Есть аналитик, который ставит задачу. Есть программист, который пишет код, есть тестировщик. В существующей логике каждому исполнителю нужно создавать отдельные задачи по одной user story. Либо менять исполнителя в задаче при переходе между статусами, что плохо ибо теряется история исполнителей - всегда будет видеть только последний.

В один момент времени у задачи один исполнитель. Что касается истории исполнителей, то она сохраняется, при чем есть информация сколько задача была у какого исполнителя. Пожалуйста обратите внимание на закладку "История - История статусов":

![image](https://user-images.githubusercontent.com/10989306/45953948-4982fc00-c014-11e8-9fbf-796ef66929c1.png)

**Comment by capitoshko** [comment]
Спасибо.

Если добавить учёт времени, о котором мы переписывались, то впринципе в задачи можно и менять исполнителя. Сейчас учесть время можно по истории изменения статусов и данными по использовано у времени на странице "учёт времени"?

**Comment by BlizD** [comment]
>Сейчас учесть время можно по истории изменения статусов и данными по использовано у времени на странице "учёт времени"?

Да, верно. Только на закладке учет времени нет разделения по исполнителю. 
Это все больше подталкивает к тому, чтобы фактическое время стало отдельным документом. А в задаче показывалось все фактическое время в разрезе исполнителей, спринтов и т.п.

**Comment by capitoshko** [comment]
Согласен. Прив'язку спринта и задач кто-то делать будет? Я бы мог делать понемногу

**Comment by BlizD** [comment]
>Прив'язку спринта и задач кто-то делать будет? Я бы мог делать понемногу

Если Семен @7OH  не начал, то я тоже не делал. 
На работе у меня аврал, уже долгое время, поэтому пока могу лишь только отвечать на вопросы.
Сам кодировать пока не могу... Надеюсь аврал когда нибудь закончится.

**Comment by 7OH** [comment]
Я завтра начну - тоже понедельник )

**Comment by capitoshko** [comment]
Семён, я тогда жду ваших изменений, буду делать исправление мелких ошибок

**Comment by capitoshko** [comment]
Я пока напишу изменения, чтобы вы посмотрели и сказали утвердили изменения.

**Comment by capitoshko** [comment]
Может эту задачу закрыть? у нас уже есть по учету времени.
