### ISSUE TITLE
Не отображаются картинки на форме Входящего и Исходящего сообщения

### ISSUE THREAD

**Issue by also1988** [BlizD/Tasks#79]
Версия Управление задачами (1.0.4.002) (8.3.10.2580) Файловая
Не отображаются картинки на форме Входящего и Исходящего сообщения. В исходящем сообщение картинки видны только при отправке. При повторном открытии формы письма отражаются пустые картинки с красным крестиком. Во входящем письме аналогично.

**Comment by BlizD** [comment]
А можете отправить пример письма на sdesk1c@bk.ru

**Comment by also1988** [comment]
Само письмо приходит корректно, и вложения сохраняются в присоединенных файлах. Они не корректно отражаются на форме документа уже после отправки (ну или всегда для входящего письма). У Вас судя по всему это тоже воспроизводится, тк ошибка видна в видео https://youtu.be/r6tNabne97s?t=2m15s

**Comment by BlizD** [comment]
Попробовал сейчас отправить исходящее письмо

после отправки:
![image](https://user-images.githubusercontent.com/10989306/37019262-b020cf22-2128-11e8-8901-57b68008a14d.png)

база файловая, платформа 8.3.9.1850

С серверной тоже отправил. Там платформа 8.3.10.2639

**Comment by BlizD** [comment]
В файловой базе: при входящем письме поймал ошибку
![image](https://user-images.githubusercontent.com/10989306/37019491-79789904-2129-11e8-8343-1baf794622bb.png)

В серверной базе: все корректно пришло с картинками.
У Вас есть возможность проверить тоже самое в серверной базе? Это бы сильно помогло.

**Comment by also1988** [comment]
Протестировал в серверной. Действительно работает корректно

**Comment by BlizD** [comment]
Спасибо, значит пока проблема только в файловом режиме.

**Comment by also1988** [comment]
Похоже все таки проблема в другом. Сейчас развернул серверную базу на другом сервере и ошибка опять появилась.

**Comment by BlizD** [comment]
>Похоже все таки проблема в другом. Сейчас развернул серверную базу на другом сервере и ошибка опять появилась.

Надо понять закономерность. Заполнение входящего письма это поведение БСП, т.е. найти и исправить там ошибку будет не так просто. Надо зафиксировать последовательность действий которые приводят к ошибочному случаю.

**Comment by also1988** [comment]
везде 8.3.10.2580. Под отладкой прошелся. все бспшные механизмы отрабатывают корректно. Присоединенный файл есть. Переделал отображение с ПолеHTMLДокумента на ПолеФорматированногоДокумента и тоже работает. А вот штатно нет (

**Comment by BlizD** [comment]
>Переделал отображение с ПолеHTMLДокумента на ПолеФорматированногоДокумента и тоже работает. А вот штатно нет (

Под штатно, что имеете ввиду?

**Comment by also1988** [comment]
Ну без доработок, на полеHTMLДокумента

**Comment by BlizD** [comment]
@also1988

>Ну без доработок, на полеHTMLДокумента

Правильно ли понял, что Вы заменили форматированный документ на поле html документа и картинки стали отображаться корректно?

**Comment by also1988** [comment]
Да, но еще обработал текстhtml как это сделано в исходящем письме

`			СтруктураВложений = Новый Структура;
			Объект.ТекстHTML = Взаимодействия.ОбработатьТекстHTMLДляФорматированногоДокумента(
			Объект.Ссылка, Объект.ТекстHTML,СтруктураВложений);
			ТекстПисьмаФорматированныйДокумент.УстановитьHTML(Объект.ТекстHTML, СтруктураВложений);
			Элементы.ТекстПисьма.Видимость = Ложь;
			Элементы.ТекстПисьмаФорматированныйДокумент.Видимость = Истина;
`

**Comment by BlizD** [comment]
Не пробовали такое же сделать для форматированного документа?

**Comment by also1988** [comment]
Так это и сделано для форматированного документа

**Comment by BlizD** [comment]
>Так это и сделано для форматированного документа

Похоже  запутался, перечитаю позже еще раз все, что Вы написали.
Попробую понять, что Вы сделали и что необходимо подправить в связи с этим.

**Comment by BlizD** [comment]
@also1988 
Если у Вас есть понимание, что и где необходимо подправить - напишите, скиньте CF (если Pull Request не получается).

**Comment by BlizD** [comment]
@also1988 
Еще заметил странное, если в письме есть предыдущее письмо, то картинок уже не показывает. Хотя присоединенные файлы есть.
Переделал по Вашему варианту, стало показывать картинки.
Но не хотел бы по этому пути идти, т.к. там с таблицами еще есть проблема.

В форматированном документе они не отображаются.
А в ПолеHTMLДокумента отображаются:
![image](https://user-images.githubusercontent.com/10989306/37149223-487286a6-22de-11e8-9e51-5f1a5007e076.png)

**Comment by BlizD** [comment]
Думал может это как то связано с уникальным идентификатором в методе ПоместитьВоВременноеХранилище
![image](https://user-images.githubusercontent.com/10989306/37149277-81c465c8-22de-11e8-8384-7a6a0e6a4d73.png)
Но это не помогло

**Comment by BlizD** [comment]
Еще непонятно это проблема кода или поведение HTML в 1с?
Еще вопрос может ли повлиять на это смена платформы или обновление БСП.

**Comment by also1988** [comment]
@BlizD я пока тоже решения не нашел. Можно конечно БСП попробовать обновить до свежей, но боюсь это трудоемко

**Comment by BlizD** [comment]
Отправил то же самое проблемное письмо в серверную базу.
Там тоже не показываются сообщения.

**Comment by BlizD** [comment]
@also1988 

Можете у себя попробовать заменить код следующим образом.
Как в коммите 28398fb

**Comment by also1988** [comment]
@BlizD протестировал. Во входящем письме теперь все работает, в исходящем - нет (но оно и раньше работало)

**Comment by BlizD** [comment]
а в исходящем как поймать ошибку?

**Comment by also1988** [comment]
@BlizD у меня просто пишешь новое письмо исходящее, вставляешь картинку, отправляешь. После этого если перезайти в него, то картинка в нем не будет отображаться

**Comment by BlizD** [comment]
@also1988 

Попробуйте изменить как в коммите: 1ec08e4

**Comment by also1988** [comment]
@BlizD Все работает, отлично!

**Comment by BlizD** [comment]
@also1988 
Супер!
Чуть позже выложу релиз.
