### ISSUE TITLE
Ошибка при занесении заказчика вручную

### ISSUE THREAD

**Issue by paul-cpp** [BlizD/Tasks#81]
```
{ОбщийМодуль.УправлениеКонтактнойИнформациейСлужебный.Модуль(1836)}: Сведения о виде контактной информации "Телефон" были повреждены или некорректно заполнены,
т.к. обязательное поле тип не заполнено.
		ВызватьИсключение СтроковыеФункцииКлиентСервер.ПодставитьПараметрыВСтроку(ТекстОшибки, ?(ЗначениеЗаполнено(ОжидаемыйВид), """" + ОжидаемыйВид.Наименование + """", ""));
```

**Comment by BlizD** [comment]
@paul-cpp 
Попробуйте сначала записать Заказчика, а затем указать телефон и номер.

**Comment by BlizD** [comment]
@paul-cpp 

Да, ошибка себя проявила на пустой базе.

Способ обхода:
Необходимо запустить обработку:
* ОбновлениеНаВерсию_1_0_3_035.epf, 6 Кб

[ОбновлениеНаВерсию_1_0_3_035.zip](https://github.com/BlizD/Tasks/files/1858725/_1_0_3_035.zip)
