### ISSUE TITLE
Отображение дополнительных реквизитов на канбан доске

### ISSUE THREAD

**Issue by paul-cpp** [BlizD/Tasks#82]
Было бы очень удобно видеть на канбан доске дополнительную информацию, например:
- исполнитель
- заказчик
- аватар исполнителя
Это позволит удобнее ориентироваться на доске и видеть кто какие задачи делает

**Comment by BlizD** [comment]
@paul-cpp 
Согласен, это было бы удобно, чтобы можно было настраивать, что именно показывать.

Похожая задача:
* Настройка отображения задания на доске #57

**Comment by BlizD** [comment]
@paul-cpp в релизе 1.0.4.010 добавлено отображение 3 строки в карточке задачи.
См. описание релиза  https://github.com/BlizD/Tasks/releases/tag/1.0.4.010
