### ISSUE TITLE
Задачи через почту создаются без присоединенных файлов

### ISSUE THREAD

**Issue by paul-cpp** [BlizD/Tasks#83]
При получении письма и автоматическом создании задачи вложения не попадают в присоединенные файлы в задаче

**Comment by BlizD** [comment]
@paul-cpp 
Да, сейчас вложения из письма не прикладываются в задачу, а остаются в письме.

**Comment by BlizD** [comment]
@etnety 
Классно сделал, спасибо. Мне понравилось=)
Залил в основную ветку. 

![image](https://user-images.githubusercontent.com/10989306/44956827-a63a3d80-aed2-11e8-9ccc-1f0fc16c260d.png)

Единственное, если меняем код в типовых модулях БСП надо код обрамлять комментариями и добавлять префикс "уз" для новых процедур и функций. Это важно, если вдруг потребуется обновить версию БСП.
Обрамление добавил, функции оставил как есть, менять не будем.

**Comment by capitoshko** [comment]
Давайте сделаю вмести с ошибками. Сегодня начинаю.

Есть тут возможножность указать кто выполняет задачи? что бы потом отобрать по себе? Или опция "Взять себе задачу"?

**Comment by BlizD** [comment]
@capitoshko данная задача реализована. Пока еще не выпущена в релиз новый.
