### ISSUE TITLE
Не корректно обрабатывается входящая почта при использовании IMAP

### ISSUE THREAD

**Issue by 79vlad** [BlizD/Tasks#84]
Не корректно обрабатывается входящая почта!
При получении нового письма, создается задача и отправляется уведомление заказчику о том, что задача зарегистрированна.
При следующей проверки почты - письмо затягивается повторно и опять создается новая задача с отправкой уведомления заказчику, что задача зарегистрированна.

**Comment by BlizD** [comment]
Необходимо в настройках учетной записи указать чтобы письма удалялись на сервере

**Comment by BlizD** [comment]
@79vlad посмотрите что сейчас у Вас указано?

**Comment by BlizD** [comment]
![image](https://user-images.githubusercontent.com/10989306/38680400-ec60888e-3e6e-11e8-9a4f-16dabe95ffa8.png)

Точнее настройка называется:
* Оставлять копии писем на сервере (она должна быть снята)

**Comment by 79vlad** [comment]
К сожалению, не помогло - продолжает дублировать и не удаляет из входящих.
![image](https://user-images.githubusercontent.com/38312005/38693882-f290acc6-3e90-11e8-9c52-8ddfe167dddd.png)

ЗЫ Фоновое получение писем "каждую минуту" (для тестирования)

Попробую повторно перезалить крайний релиз 1.0.4.007 (после обновления на этот релиз проявилась данная ошибка).

ЗЫ Флаг установить смог, только обработкой "Инструменты разработчика", т.к. с самыми полными правами - этот реквизит на управляемой форме не отображается :-(
![image](https://user-images.githubusercontent.com/38312005/38693816-b89d357a-3e90-11e8-8595-dd480d9e6030.png)

**Comment by BlizD** [comment]
Попробуйте на другом ящике почтовом. Будет ли повторяться?

**Comment by BlizD** [comment]
Зайдите еще в настройки заказчика по этому ящику и поставьте не отправлять уведомления

**Comment by BlizD** [comment]
Получается вы с одного и то же ящика отправляете заявку, да?

**Comment by 79vlad** [comment]
Да. Один ящик и на получение и на отправку

чт, 12 апр. 2018 г., 21:27 Anton Ivanov <notifications@github.com>:

**Comment by BlizD** [comment]
>ЗЫ Флаг установить смог, только обработкой "Инструменты разработчика", т.к. с самыми полными правами - этот реквизит на управляемой форме не отображается :-(

Это странно, посмотрю у себя

**Comment by BlizD** [comment]
Адрес электронной почты поддержки и адрес электронной почты заказчика не должны совпадать. Если правильно понял то Вы отправили письмо с адреса поддержки на адрес поддержки.

**Comment by 79vlad** [comment]
Нет, для СервисДеск выделен отдельный аккаунт со своим ящиком.
Работа с этим ящиком только программная.




чт, 12 апр. 2018 г., 21:35 Anton Ivanov <notifications@github.com>:

**Comment by BlizD** [comment]
Получается проблема в том что письма не удаляются из входящих. Попробуйте указать другой ящик(не с вашего почтового сервера) в качестве ящика поддержки.  допустим gmail, yandex. Чтобы локализовать проблему.

**Comment by BlizD** [comment]
Проблема только с IMAP?

**Comment by 79vlad** [comment]
В других вариантах работы с почтой проверить не могу, по причине того, что
сервер без выхода в мир.
На днях попробую доработать учётную запись под работу с IMAP (вычитку
только не прочтённые и если будет у меня время - то и вычитку по папкам в
почтовом ящике)

чт, 12 апр. 2018 г., 22:00 Anton Ivanov <notifications@github.com>:

**Comment by 79vlad** [comment]
@BlizD 
> Отлично, можешь потом скинуть изменения? Включу в основную поставку. 

Сделанными изменениями - обязательно поделюсь :-)

**Comment by 79vlad** [comment]
Антон, добрый вечер.
Наконец дошли руки довести это до ума (рабочая выгрузка: [1Cv8_IMAP_v_1_0_4_007.7z](https://drive.google.com/open?id=1H_lVJZnNxGLbbbSR6EuKLCUrbqjjYI59) )
PS все мои изменения помечены //+++ #84 79Vlad

**Comment by BlizD** [comment]
@79vlad 
Спасибо, за CF, себе все сохранил. 
Постараюсь включить изменения в следующий релиз.

**Comment by BlizD** [comment]
@79vlad 
//+ #84 Иванов А.Б. 2018-07-23
Перенесены следующие объекты из твоей конфигурации:
* ОбщийМодуль.РаботаСПочтовымиСообщениямиСлужебный
	* в процедуру добавил префикс узПолучитьСписокПапокIMAP 				
* ОбщийМодуль.УправлениеЭлектроннойПочтой							
* Справочник.УчетныеЗаписиЭлектроннойПочты
	* Добавил префиксы уз в реквизиты справочника 
		* узПапкаВходящейПочтыIMAP
		* узИсключатьДублиПисем

**Comment by BlizD** [comment]
@79vlad 
Нужна мини инструкция, что надо заполнить, чтобы работал IMAP.
Потом ее в Wiki добавлю.

**Comment by 79vlad** [comment]
Антон, добрый день.
Ниже описана краткая настройка получения почты по протоколу IMAP:

В справочнике "Учетные записи электронной почты", на закладке "Получение
писем", необходимо:

Выбрать протокол "IMAP"
После этого будет доступно поле "Папка входящей почты IMAP":
[image: image.png]
При нажатии на кнопку выбора, выполняется подключение к почтовому ящику и
получение списка доступных папок почтового ящика.
[image: image.png]

Необходимо выбрать папку, из которой будет происходить получение почты
(обычно это "INBOX").

*Если с почтовый ящик используется не только для данной программы, то
желательно на почтовом клиенте, создать отдельную папку для входящих писем,
в которую, по заранее настроенным правилам фильтрации, перемещать письма,
для последующей их загрузки в программу "Управление задачами".

**Если это поле не заполнено - то по умолчанию письма будут загружаться из
папки "INBOX".

Если, при получении писем, программа два раза получает одно и тоже письмо -
то для исправления этой ошибки, необходимо установить флаг "Исключать дубли
писем"


пн, 23 июл. 2018 г. в 15:44, Anton Ivanov <notifications@github.com>:

**Comment by 79vlad** [comment]
Антон, добрый день.

Помимо доработки IMAP, я столкнулся с тем, что мне необходимо было
загрузить всю историю хранилища, но это не получилось из-за отсутствия
метки с номером задачи (также иногда вносятся мелкие изменения, на которые
нет задач).

Пришлось "подшаманить" загрузку истории хранилища:
1) Добавил константу "Задача по умолчанию для хранилища" - число
(соответствует номеру задачи)
2) В обработке "узЗагрузкаИзмененийИзХранилища", в модуле объекта, изменил
следующий кусок кода:
Функция ПолучитьЗадачу(СтрокаТЗИсторияХранилища)
Перем пЗадача;
пКомментарий = СокрЛП(СтрокаТЗИсторияХранилища.Комментарий);
// +++ Григорьев  01.06.2018
Если НЕ ЗначениеЗаполнено(пКомментарий) Тогда
пКомментарий = "#" + Константы.узЗадачаПоУмолчаниюДляХранилища.Получить() +
" " +  пКомментарий;
КонецЕсли;
// --- Григорьев  01.06.2018
Если НЕ ЗначениеЗаполнено(пКомментарий) Тогда
ТекстОшибки = "Ошибка! Не заполнен комментарий в хранилище";
ОтправитьУведомлениеОшибкаВКомментарииХранилища(ТекстОшибки,СтрокаТЗИсторияХранилища);
Возврат пЗадача;
Конецесли;
ПозРешетки = СтрНайти(пКомментарий,"#");
// +++ Григорьев  01.06.2018
Если ПозРешетки = 0 Тогда
пКомментарий = "#" + Константы.узЗадачаПоУмолчаниюДляХранилища.Получить() +
" " +  пКомментарий;
КонецЕсли;
ПозРешетки = СтрНайти(пКомментарий,"#");
// --- Григорьев  01.06.2018
Если ПозРешетки = 0 Тогда
ТекстОшибки = "Ошибка! В комментарии не указан номер задачи. Необходимо
указать #НомерЗадачи";
ОтправитьУведомлениеОшибкаВКомментарииХранилища(ТекстОшибки,СтрокаТЗИсторияХранилища);
Возврат пЗадача;
Конецесли;
КоличествоУказанныхЗадач = СтрЧислоВхождений(пКомментарий,"#");
Если КоличествоУказанныхЗадач > 1 Тогда
ТекстОшибки = "Ошибка! В комментарии можно указывать только один номер
задачи. В будущем всегда разбивайте помещения объектов в хранилище на
отдельные задачи.";
ОтправитьУведомлениеОшибкаВКомментарииХранилища(ТекстОшибки,СтрокаТЗИсторияХранилища);
Возврат пЗадача;
Конецесли;
ДлинаСтроки = СтрДлина(пКомментарий);
НомерСимвола = ПозРешетки + 1;
НомерЗадачи = "";
Пока НомерСимвола <= ДлинаСтроки Цикл
Символ = Сред(пКомментарий,НомерСимвола,1);
пКодСимвола = КодСимвола(Символ);
Если 48 <= пКодСимвола
И пКодСимвола <= 57 Тогда
НомерЗадачи = НомерЗадачи + Символ;
Иначе
Прервать;
Конецесли;
НомерСимвола = НомерСимвола + 1;
Конеццикла;
Если НЕ ЗначениеЗаполнено(НомерЗадачи) Тогда
Возврат пЗадача;
Конецесли;
НомерЗадачи = Число(НомерЗадачи);
ПараметрыПоиска = Новый Структура();
ПараметрыПоиска.Вставить("Код",НомерЗадачи);
пЗадача = ПолучитьСсылкуНаОбъект("узЗадачи",ПараметрыПоиска);
Возврат пЗадача;
КонецФункции


После этой доработки - у меня никогда не возникала проблема с получением
истории хранилища из-за отсутствия номера задачи.
Проверенно - работает.


пн, 23 июл. 2018 г. в 15:44, Anton Ivanov <notifications@github.com>:

**Comment by BlizD** [comment]
@79vlad спасибо за инструкцию. Позже добавлю в вики.

**Comment by BlizD** [comment]
@79vlad 
>Помимо доработки IMAP, я столкнулся с тем, что мне необходимо было
загрузить всю историю хранилища, но это не получилось из-за отсутствия
метки с номером задачи (также иногда вносятся мелкие изменения, на которые
нет задач).

Создал задачу, реализация немного другая будет:
* Сделать признак, который бы позволял указывать комментарии без задач (Загрузка изменений из хранилища) #88 (есть кто хочет сделать?)

**Comment by BlizD** [comment]
@79vlad добавил инструкцию в Вики.
https://github.com/BlizD/Tasks/wiki/Настройка-получения-почты-по-протоколу-IMAP
