### ISSUE TITLE
Ошибка получения почты, если используются правила обработки электронной почты

### ISSUE THREAD

**Issue by etnety** [BlizD/Tasks#85]
_узОбщийМодульСервер_ процедура _ЗаполнитьПредметВПисьме_ЗадачаПоТемеПисьма_.

При установленном флаге _ЕстьДопНастройкиИзПравилОбработки_ 
падает в строке 
`Если ЗначениеЗаполнено(НастройкиИзПравилОбработки.узСтатусДляЗадачи) Тогда`
т.к. функция _ОпределитьНастройкиИзПравилОбработки_ не устанавливает статус из правил.

Вариант решения:
`
Функция ОпределитьНастройкиИзПравилОбработки(УчетнаяЗапись,Письмо)
	
	РезультатФункции = Новый Структура();
	РезультатФункции.Вставить("ЕстьДопНастройкиИзПравилОбработки",Ложь);
	РезультатФункции.Вставить("узНеСоздаватьЗадачуПриПолученииПисьма",Ложь);
	РезультатФункции.Вставить("узСозданнуюЗадачуПомещатьВВеткуЗадач",Неопределено);
	РезультатФункции.Вставить("узСтатусДляЗадачи",Неопределено);
	
	Запрос = Новый Запрос;
	Запрос.Текст = 
	"ВЫБРАТЬ
	|	ПравилаОбработкиЭлектроннойПочты.Владелец КАК УчетнаяЗапись,
	|	ПравилаОбработкиЭлектроннойПочты.КомпоновщикНастроек,
	|	ПравилаОбработкиЭлектроннойПочты.ПомещатьВПапку,
	|	ПравилаОбработкиЭлектроннойПочты.узНеСоздаватьЗадачуПриПолученииПисьма,
	|	ПравилаОбработкиЭлектроннойПочты.узСозданнуюЗадачуПомещатьВВеткуЗадач,
	|	ПравилаОбработкиЭлектроннойПочты.узСтатусДляЗадачи
	|ИЗ
	|	Справочник.ПравилаОбработкиЭлектроннойПочты КАК ПравилаОбработкиЭлектроннойПочты
	|ГДЕ
	|	ПравилаОбработкиЭлектроннойПочты.Владелец = &УчетнаяЗапись
	|	И НЕ ПравилаОбработкиЭлектроннойПочты.ПометкаУдаления
	|
	|УПОРЯДОЧИТЬ ПО
	|	ПравилаОбработкиЭлектроннойПочты.РеквизитДопУпорядочивания";
	
	Запрос.УстановитьПараметр("УчетнаяЗапись", УчетнаяЗапись);
	
	РезультатЗапроса = Запрос.Выполнить();
	Если РезультатЗапроса.Пустой() Тогда
		Возврат РезультатФункции;	
	КонецЕсли;	
	
	Выборка = РезультатЗапроса.Выбрать();
	Пока Выборка.Следующий() Цикл
		
		пУсловиеВыполнено = ВыполненоУсловиеИзПравилОбработки(Выборка,УчетнаяЗапись,Письмо); 
		
		Если пУсловиеВыполнено Тогда
			РезультатФункции.ЕстьДопНастройкиИзПравилОбработки = Истина;
			РезультатФункции.узНеСоздаватьЗадачуПриПолученииПисьма = Выборка.узНеСоздаватьЗадачуПриПолученииПисьма;
			РезультатФункции.узСозданнуюЗадачуПомещатьВВеткуЗадач = Выборка.узСозданнуюЗадачуПомещатьВВеткуЗадач;
			РезультатФункции.узСтатусДляЗадачи = Выборка.узСтатусДляЗадачи;
			
			Прервать;
		КонецЕсли;
		
	КонецЦикла;
	
	Возврат РезультатФункции;
	
КонецФункции
`

**Comment by BlizD** [comment]
Спасибо что сообщили. Можете еще прислать текст ошибки?

**Comment by etnety** [comment]
... произошла ошибка
{ОбщийМодуль.узОбщийМодульСервер.Модуль(585)}: Поле объекта не обнаружено (узСтатусДляЗадачи)
		Если ЗначениеЗаполнено(НастройкиИзПравилОбработки.узСтатусДляЗадачи) Тогда

**Comment by BlizD** [comment]
@etnety внес исправления можно посмотреть вот [https://github.com/BlizD/Tasks/commit/112d5b310a6ddd29410224466fd4cfbd5a3a3b1b](url)
