### ISSUE TITLE
Спринты, добавление табличной части с задачами

### ISSUE THREAD

**Issue by BlizD** [BlizD/Tasks#86]
>[7OH](https://infostart.ru/profile/102644/)  32 28.07.18 19:10
Есть просьба - добавить в регистр учета времени измерение - Спринт. 
Сделал у себя расширением кнопку в спринте - перенести задачи в новый спринт (ну не успели в текущем доделать). 
Задача то мигрирует в новый спринт, а вот учет времени становится под вопросом - часть времени потрачено будет в одном спринте, вторую часть доделают во втором - как учитывать при этом не ясно. 
Доп измерение думают никому не помешает.

**Comment by BlizD** [comment]
Семен, 
дело в том, что регистра учета времени нет. 
Сейчас "Спринт" это реквизит справочника "Задачи".
Как мне кажется в первую очередь необходимо:
* добавить табличную часть "ТЧЗадачи" в справочник "Спринты" и именно там указывать список задач вошедших в спринт.
* добавить префикс "Удалить_" в реквизит "Спринт" в справочник "Задачи";
* написать обработку, которая заполнит "ТЧЗадачи" из реквизита "Удалить_Спринт";
* переделать команды существующие: "Добавить в спринт", "Убрать из спринта".

**Comment by 7OH** [comment]
Почему не надо - задача оказалась слишком большой (или зависела от других возникающих задач). Время на неё потрачено, она частично сделана - заказчик не против оплачивать часть работы.
При наличии в регистре измерения - отчет вполне сможет показать сколько времени было потрачено в этом спринте, и мы удачно переносим остаток работы на завтра.
--
А вот про отсутствие регистра - да - только заметил, что оно всё в самой задаче хранится.
В регистром было бы всё просто - в новую запись пишем спринт из задачи и всё - остальные не трогаем.

**Comment by BlizD** [comment]
Мне кажется в это случае лучше дробить задачу.

**Comment by BlizD** [comment]
@7OH Если большая - разбить на ту что сделано и на то, что осталось сделать

**Comment by 7OH** [comment]
Ну вот хочется в одной видеть - чтобы было сделано, когда, комментарии.

**Comment by 7OH** [comment]
Ну и момент - регистра нет  это же ТЧ справочника - реализация выходит ещё проще.
Если идейно добавление не выглядит корректным - буду пробовать расширением это сделать - только скажите.

**Comment by BlizD** [comment]
@7OH 
Добрый день, Семен. 
Можете описать идею, как, Вы предлагаете это реализовать? 
Чтобы понять какие изменения в метаданых требуются.

**Comment by 7OH** [comment]
Уже сделал так:
В табличной части учета времени добавил спринт, туда записал на момент запуска текущие значение из шапки. 
При добавлении записи времени - ставлю в строчку спринт из шапки.
Если перенесли (изменили спринт у задачи) - то дальше в ТЧ пишется с новым значениям спринта.
Ну и отчет переделал, чтобы учетное время брало не итоговое из шапки, а складывало построчно. Спринт соответственно тоже из табличной части. 
Итого - почти ничего не изменилось, но отчет можно отфильтровать для показа - сколько времени потрачено в текущем спринте (например) или просто общее время в разрезе - в какие спринты он попал.
---
Кнопку переноса задач сделал в самом спринте - возможно не совсем айс - но пока так: зашел и видишь все задачи спринта - нажал кнопку, выбрал куда перенести, выбрал статусы для переноса, выбрал по этим статусам задачи - вуаля.

**Comment by BlizD** [comment]
@7OH 
Понятно, рад, что у Вас получилось.

**Comment by capitoshko** [comment]
Может проще добавить оборотный регистр накопления с измерениями задача + спринт? Спринт как реквизит буде выбираться из задачи.  и писаться в регистр на момент записи времени по задаче. ТЧ для спринта, по-моэму, не имеет значения.

**Comment by 7OH** [comment]
Я стараюсь сильно не менять текущую структуру : всего +1 реквизит в табличной части, которая сейчас всё же используется.

**Comment by capitoshko** [comment]
Я бы поменял. Если дальше делать бизнес-план ссылка, то пригодиться. И это верно с точки зрения архитектуры

**Comment by BlizD** [comment]
Тут надо подумать как лучше это реализовать. Так как для регистра накопления нужен регистратор. Вообщем думаю сначала лучше обсудить как это реализовать.

**Comment by BlizD** [comment]
Может быть даже спринт это должен быть документ...

**Comment by capitoshko** [comment]
Согласен. Регистрировать время можно документом. Спринт - может и документ, но тогда как задачи перемещать между спринтами?

**Comment by capitoshko** [comment]
Это позволит видеть когда именно делалась задача,  сколько было перерывов и оценить время на переключение между задачами

**Comment by 7OH** [comment]
А есть смысл делать именно оборотный ? Если период меньше месяца - всё равно по записям будет отчет складывать. А в основном отчет будет не в разрезе месяца. Как на мой взгляд регистра сведений хватит с головой. Заменить табличную часть регистром независимым.

**Comment by 7OH** [comment]
у меня сейчас реквизит спринт в табличной части - я тоже отлично вижу когда, в каких спринтах и сколько я её делал.

**Comment by capitoshko** [comment]
Если нужно что-то посчитать - то это не регистр сведений, как мне кажется.

**Comment by BlizD** [comment]
Вообщем, пока больше склоняюсь к такому варианту:

Исправить хранение спринтов (для Диаграммы Burndown это будет важно):
* добавить табличную часть "ТЧЗадачи" в справочник "Спринты" и именно там указывать список задач вошедших в спринт.
* добавить префикс "Удалить_" в реквизит "Спринт" в справочник "Задачи";
* написать обработку, которая заполнит "ТЧЗадачи" из реквизита "Удалить_Спринт";
* переделать команды существующие: "Добавить в спринт", "Убрать из спринта".

Исправление по учету времени: 
* Добавить в табличную часть "Фактические часы" реквизит "Спринт" (как сделал 7ОН)
* Сделать, чтобы при добавлении строки в ТЧ "Фактические часы" брался последний спринт для задачи;
* По поводу отчета для учета времени, если исправить существующий отчет по задачам (добавить отображение спринта из ТЧ фактические часы) тогда строки в отчете будут дублироваться на отдельные спринты.
   * В этом случае лучше сделать отдельный отчет для учета времени.

**Comment by 7OH** [comment]
Отлично. Отчет надо переделать и глянуть что выйдет по итогу. Дубли если и будут то по разным спринтам и разным временем. Как по мне - вполне понятно выйдет. 
Но, есть момент. Если реквизит спринт перекочует в тч - как это на доске отображать? Ведь не выйдет же

**Comment by BlizD** [comment]
Нужен регистр сведений в котором хранить последний спринт для задачи

**Comment by 7OH** [comment]
Как регистр двигать будем? При перемещении задачи в тч спринта?

**Comment by BlizD** [comment]
При записи спринта. Период брать из даты спринта. Задачу из тч.

**Comment by 7OH** [comment]
Ок.  Попробую переделать вот так.

**Comment by BlizD** [comment]
Регистр сведений надо назвать узЗадачиСпринта

**Comment by capitoshko** [comment]
Такое себе решение. Независимый регистр сведений в данном случае не очень уместен. Он же предназначен для хранения периодической информации. А у нас - регистрация факта работ. В том же ЗУП рабочее время работников это оборотный регистр накопления.

**Comment by capitoshko** [comment]
Или речь идёт об привязке задачи у спринту? Время тогда будет учитываться как и прежде?

**Comment by BlizD** [comment]
Пока речь о привязке задач к спринту. И возможность указать в факте работ еще и спринт.

**Comment by capitoshko** [comment]
А вот для простой привязки задач к спринту регистр сведений подойдёт. Тогда мы будем знать когда именно задача перешла с одного спринтами в другой. Для учета времени я бы всё-таки сделал отдельный документ "Выполнение задачи" и в этих документах указывал время выполнения с записью в регистр накопления учета времени.

**Comment by 7OH** [comment]
https://drive.google.com/open?id=1fvIPC_DX-ifSfhwTrZXnMRvGZQcQ2YCC
Сделал, что смог.
Осталось, как мне кажется, только функцию удаления из спринта сделать и теперь наверное не добавления, а переноса. 
В общем просьба эти функции добить.

**Comment by capitoshko** [comment]
У меня возник вопрос по плановой оценке задачи. Будь то время, числа Фибоначчи или ещё что-то... Нам это время нужно для оценки план/факта и в том числе для построения графика сгорания спринта. А если я перемещаю задачи между спринтами по идеи оценка задачи также меняется? Получается оценка задачи не может быть реквизитом справочника Задачи а периодическое значение?

**Comment by etnety** [comment]
> А если я перемещаю задачи между спринтами по идеи оценка задачи также меняется?
Регистр, который привязывает оценку задачи к текущему спринту?

**Comment by BlizD** [comment]
>А если я перемещаю задачи между спринтами по идеи оценка задачи также меняется? Получается оценка задачи не может быть реквизитом справочника Задачи а периодическое значение?

В целом, я все также придерживаюсь мнения, что если задача большая и не "влезает" в спринт ее надо дробить на подзадачи. Или же увеличивать длину спринта. А может быть вообще спринты не подходят для таких задач. Просто вроде как методологически в спринт должны включаться только те задачи, которые могут быть выполнены за спринт, если они не выполнены, они должны переезжать в другой спринт. 
Пока давайте оставим плановую оценку в самой задаче, когда проблема себя остро проявит, тогда будем думать как ее решить.

**Comment by BlizD** [comment]
@7OH 
>https://drive.google.com/open?id=1fvIPC_DX-ifSfhwTrZXnMRvGZQcQ2YCC
Сделал, что смог (без документов).
Осталось, как мне кажется, только функцию удаления из спринта сделать и теперь наверное не добавления, а переноса.
В общем просьба эти функции добить.

Изменения сделаны в выпущенном релизе (а не в CF от дев ветки), много расхождений.
Поэтому пока не заливал, есть некоторые моменты, которые надо иначе сделать.

**Comment by capitoshko** [comment]
> > А если я перемещаю задачи между спринтами по идеи оценка задачи также меняется? Получается оценка задачи не может быть реквизитом справочника Задачи а периодическое значение?
> 
> В целом, я все также придерживаюсь мнения, что если задача большая и не "влезает" в спринт ее надо дробить на подзадачи. Или же увеличивать длину спринта. А может быть вообще спринты не подходят для таких задач. Просто вроде как методологически в спринт должны включаться только те задачи, которые могут быть выполнены за спринт, если они не выполнены, они должны переезжать в другой спринт.
> Пока давайте оставим плановую оценку в самой задаче, когда проблема себя остро проявит, тогда будем думать как ее решить.

В таком случае имеет ли смысл такая привязка? Если строить график сгорания спринта то он будет другим в зависимости от того перемещена задача с спринта или нет. Что, как мне кажеться, не верно с точки зрения регистрации факта выполнения работ.

**Comment by capitoshko** [comment]
Если оставляете оценку в задачи, то и переносить задачи со спринта не надо давать возможность. Может добавить в регистр связки спринта и задачи при переносе на новый спринт оценку задачи в новом спринте? Задачу могли сделать наполовину, первая оценка будет скажем 20 часов. Половину сделали — значит новая оценка в новом спринте будет 20. В таком случае sprint burndown chart можно строить корректно независимости от движе6ий задач между спринтами

**Comment by 7OH** [comment]
> Изменения сделаны в выпущенном релизе (а не в CF от дев ветки), много расхождений.
> Поэтому пока не заливал, есть некоторые моменты, которые надо иначе сделать.

Я так понял, мяч теперь на вашей стороне, ожидать объединения с доработками ?

**Comment by capitoshko** [comment]
Так. Обсудил с коллегами. Думаю, что моя идея не верная. Если задача не выполнена ,то при переносе нужно переносить ее полностью с всей оценкою. Так что вы правы. Я усложняю в этом случае.

Я скачал последнюю Dev конфигурацию. Начну работу над Sprint burndown chart. По учёту времени сделаю как только согласуем архитектуру.

**Comment by BlizD** [comment]
@capitoshko - ок, хорошо.
@7OH 
>Я так понял, мяч теперь на вашей стороне, ожидать объединения с доработками ?

Да, верно.

**Comment by capitoshko** [comment]
Отчёт уже нарисовал. Жду на окончательную версию привязки задач к спринтам и тогда добавлю отчёт в конфигурацию.

**Comment by BlizD** [comment]
@capitoshko - отлично.

**Comment by BlizD** [comment]
@capitoshko 
Залил изменения по спринтам.

**Comment by BlizD** [comment]
CF из деф ветки (теперь там будет лежать последний CF из дев ветки)
https://drive.google.com/open?id=1Nt8N_ippLos_v3nUHZ89s8X9jR_SixZR

**Comment by capitoshko** [comment]
а можете создать отдельную папку и разшарить ее на google drive?

**Comment by BlizD** [comment]
https://drive.google.com/drive/folders/1PMLkmLSceiseHCCqN2hv2wAB0N8p7u7m?usp=sharing

**Comment by 7OH** [comment]
А спринты в часах не взяли ?

**Comment by capitoshko** [comment]
А что значит спринта в часах? Я делаю график сгорания спринта

**Comment by capitoshko** [comment]
Фактические часы сделаем через отделы регистр. У нас идёт обсуждение ТЗ. Гляньте задачу 104. Возможно ваши. Комментарии сильно помогут так как вы уже сделали учёт времени

**Comment by capitoshko** [comment]
При открытие списка задач выдает ошибку 

Ошибка при выполнении запроса.
по причине:
{(19, 21)}: Поле не найдено "СправочникузЗадачи.Спринт"
СправочникузЗадачи.<<?>>Спринт,

Нужно переделать запрос динамического списка.

**Comment by capitoshko** [comment]
Ошибка в канбан доске

{Обработка.узКанбанДоска.Форма.ФормаДинамическая.Форма(195)}: Ошибка при вызове метода контекста (Вставить)
	пЭлементГруппаКолонка = пЭлементыФормы.Вставить(ИменаЭлементов.ИмяГруппыКолонки,Тип("ГруппаФормы"),пЭлементыФормы.ГруппаКанбанДоска);
по причине:
Недопустимое значение параметров

**Comment by capitoshko** [comment]
Вы исправите или мне колупаться?

**Comment by 7OH** [comment]
Подозреваю, в дин списке не изменено на "Удалить_Спринт как Спринт". У себя это проходил. Если не горит - вечером поправлю (брать файл с гугла ?).

**Comment by capitoshko** [comment]
Актуальная последняя ссылка на папку

**Comment by 7OH** [comment]
https://drive.google.com/open?id=1J08oAsEnkasQRey8jTrfGK43aLZeqWH-
поправил

**Comment by capitoshko** [comment]
У меня замечания не очень критичные, Начинаю перерабатывать график сгорания спринта. Думаю сегодня выложу изменения. Выложу и на внешний ресурс и на git, если Антон зальет последний вариант изменений и утвердит мой варинт выгрузки в ветку develop

**Comment by 7OH** [comment]
я вечером уже гляну что с переносом (работа всё таки )) ) - тоже краем глаза увидел, что в регистр перенесло (и не спросило в какой спринт), а в ТЧ нет.

**Comment by capitoshko** [comment]
Ок :)

**Comment by capitoshko** [comment]
Отчет по задачах также не работает

Ошибка в схеме компоновки данных
по причине:
Ошибка получения информации набора данных
по причине:
Ошибка в запросе набора данных
по причине:
{(9, 11)}: Поле не найдено "узЗадачи.Спринт"
узЗадачи.<<?>>Спринт,

**Comment by capitoshko** [comment]
Я исправлю и выложу вместе с отчетом по сгоранию спринта

**Comment by capitoshko** [comment]
https://drive.google.com/file/d/16Z8ztXXwjU3Wv9QPsSpbJH8wGvQyOtlU/view?usp=sharing

**Comment by BlizD** [comment]
@capitoshko  посмотрю CF и залью к себе.
Пожалуйста на будущее версию релиза не изменяйте. Это мне необходимо делать.

**Comment by capitoshko** [comment]
Ок, больше не буду. Я просто хотел посмотреть как отчет будет работать, а быстрое решение - изменить номер релиза.

**Comment by BlizD** [comment]
>Если с доски добавлять задачу в спринт, то регистр сведений она добавляеться, он в табличную часть спринта - не добавляеться.
Удобно было бы добавить просмотр регистра спринтов из справочника Спринты.
Если задача в бек логе, то в регистр спринтов она не добавляеться?
Убрать видимость спринта с задачи или віводить отображенияя с регистра. Путой заблочений реквизит віглядит так себе.

Кнопки с канбан доски Добавить/Убрать из спринта на канбан доске еще не сделал, себе пометил.

**Comment by BlizD** [comment]
https://drive.google.com/open?id=1PMLkmLSceiseHCCqN2hv2wAB0N8p7u7m

**Comment by BlizD** [comment]
@7OH @capitoshko @etnety 

Всем привет.

Обновил информацию в Readme:

* Необходимо следовать стилю кодирования описанному в этом репозитории "1С: Руководство по стилю оформления" https://github.com/skyksandr/1c-styleguide;
* Необходимо использовать стандарты кодирования от 1с (стандарты доступны всем, подписка на ИТС не нужна): https://its.1c.ru/db/v8std 
* Почитать и следовать рекомендациям в хорошей статье «Правила программирования и автоматизации» https://infostart.ru/public/789709/
* Если разработка ведется через CF файлы, в этом случае новый код необходимо обрамлять в следующем формате: 
```
//+ #1014 Иванов А.Б. 2016-04-06
//Старый код
....НовыйКод....
//- #1014 Иванов А.Б. 2016-04-06
```

**Comment by capitoshko** [comment]
Нужно еще спринты поправить на канбан доске, там есть часть кода, где спринт вызываеться с реквизита задачи.

**Comment by BlizD** [comment]
Речь о кнопка "Добавить/Убрать" из спринта?

**Comment by capitoshko** [comment]
> Речь о кнопка "Добавить/Убрать" из спринта?

Да.

**Comment by BlizD** [comment]
Поправил, в последнем CF есть изменения.
https://drive.google.com/open?id=1a6XEPEKATejjbWXkFAgP6o9OCwbjE6zT

**Comment by capitoshko** [comment]
Это последний релиз? можно качать?

**Comment by BlizD** [comment]
Да, можно качать.

**Comment by capitoshko** [comment]
Надо сделать первичное заполнение регистра сведений по спринтах при обновле6нии на новый релиз. никто не против?

**Comment by BlizD** [comment]
Оно сделано

**Comment by capitoshko** [comment]
По коду вижу только заполнение табличной части справочника спринты

**Comment by capitoshko** [comment]
Я себе дописал.

**Comment by 7OH** [comment]
А почему РС.узСпринтыЗадач Задача без запрета незаполненных ? Ладно у задачи может не быть спринта, но зачем к пустой задаче лепить спринт ?

**Comment by capitoshko** [comment]
Можно добавить такое без проблем

**Comment by 7OH** [comment]
Ну рег же называется Спринты задач. Значит мы сохраняем для ЭТОЙ задачи вот этот спринт. Для чего к пустой задачи хранить спринт ? Отсутствие записи сделает то же самое, но будет легче понять.
---
Сижу пытаюсь понять, где что надо будет подтянуть, чтобы свою конфу перевести на новую. Нашел ещё Обработка.узТекущиеДела - ПолучитьПорядоДоп - букву К допишем ?

**Comment by capitoshko** [comment]
Подождите нового релиза. Не спешите переходить

**Comment by 7OH** [comment]
я свои данные в регистр узСпринтыЗадач перенёс  - далее спокойно уже на новый перейду. Жду обновок )

**Comment by BlizD** [comment]
@capitoshko 
>По коду вижу только заполнение табличной части справочника спринты 

Записи в рс формируются при записи спринта.

**Comment by capitoshko** [comment]
Ясно. Тогда я подправлю процедуру при обновлении и отправлю мы ещё раз

**Comment by 7OH** [comment]
Всем привет. 
Скачал сегодня 18-й релиз, пытаюсь переехать на него. Сижу думаю где ошибся, а вот не ошибся. В документе отражения работы в ТЧ спринт указан, а при проведении зачем-то берёт последний из регистра.
В регистре на дату документа пусто - не важно - при заполнении надо смотреть текущий возможно, а при проведении уже брать из ТЧ. 
Поправьте, если где-то ошибаюсь.

**Comment by BlizD** [comment]
@7oh Создай новую задачу
