### ISSUE TITLE
При создании задач из почты интерпретировать заголовки как простой текст (не HTML)

### ISSUE THREAD

**Issue by etnety** [BlizD/Tasks#87]
Приходят сообщения:
`Описание задачи:
-------- Пересылаемое сообщение --------
От кого: Наталья  &lt;email&gt;`

**Comment by BlizD** [comment]
@etnety 
Добрый день. 
Можете прислать такое письмо на sdesk1c@bk.ru.

**Comment by BlizD** [comment]
Хорошо, понял. Спасибо.
