### ISSUE TITLE
Сделать признак, который бы позволял указывать комментарии без задач (Загрузка изменений из хранилища)

### ISSUE THREAD

**Issue by BlizD** [BlizD/Tasks#88]
Сделать признак, который бы позволял указывать комментарии без задач (Загрузка изменений из хранилища).

### Как сейчас ###
Сейчас при загрузке изменений из хранилища, всегда контролируется комментарий. В нем всегда должна быть указана только одна задача в формате #НомерЗадачи

### Как надо ###

В справочник "Конфигурации" 
* добавить реквизит "РазрешеныКомментарииБезЗадач" (Булево)
* В обработку узЗагрузкаИзмененийИзХранилища сделать, чтобы при загрузке изменений 
Если задача не найдена и установлен признак "РазрешеныКомментарииБезЗадач" то просто продолжать загрузку, а не прерываться.
Место в коде
![image](https://user-images.githubusercontent.com/10989306/43894953-610d98a0-9bdc-11e8-85b1-7d6f48c12451.png)

**Comment by capitoshko** [comment]
и что тогда нужно сделать? сейчас без комментария изменения в конфигурации не грузяться вообще.

**Comment by BlizD** [comment]
Сейчас если только исправить в коде.

**Comment by BlizD** [comment]
Эту задачу сам сделаю.

**Comment by BlizD** [comment]
![image](https://user-images.githubusercontent.com/10989306/46732336-dcb76500-cc95-11e8-91e4-bcac13e446d1.png)
