### ISSUE TITLE
Ошибка создания администратора в новой базе

### ISSUE THREAD

**Issue by etnety** [BlizD/Tasks#90]
Платформа 8.3.9.1850
При первоначальной инициализации базы возникает ошибка в процедуре 
`Процедура узДобавитьАдминистраторИБ()`
...
`{ОбщийМодуль.узОбновлениеИнформационнойБазы.Модуль(704)}: Поле объекта не обнаружено (ЗащитаОтОпасныхДействий)
	ПользовательИБ.ЗащитаОтОпасныхДействий.ПредупреждатьОбОпасныхДействиях = Ложь;`

Режим совместимости конфигурации 8.3.7, а это свойство введено в 8.3.8

**Comment by BlizD** [comment]
@etnety 
Спасибо, себе отметил. 
Если можете это подправить это было бы круто.

**Comment by etnety** [comment]
Как сделать PR только по этой задаче?

**Comment by BlizD** [comment]
@etnety скорее всего необходимо в твоем форуме на каждую задачу создавать отдельную ветку. И PR делать из этой ветки.

**Comment by nixel2007** [comment]
да, нужно сделать ветки. если отдельный коммит уже есть, то можно на нем создать ветку и оформить из нее PR.
если коммитов несколько, то только через новые ветки от основного девелоп и cherrypick

**Comment by capitoshko** [comment]
Эта задача сделана?

**Comment by BlizD** [comment]
Да, сделана.
