### ISSUE TITLE
Добавление собственных характеристик (аналитик) к задачам

### ISSUE THREAD

**Issue by relieverz** [BlizD/Tasks#92]
Предлагаю к задачам и текущим делам добавлять свои характеристики. В идеале, если бы они были завязаны к полю "Конфигурация".

**Comment by BlizD** [comment]
@relieverz Добрый день. 
К задачам можно добавлять свои доп реквизиты.

https://youtu.be/uRX_iuWirtI - как добавить свой реквизит в задачу без программирования;

**Comment by relieverz** [comment]
@BlizD, не увидел сразу. Благодарю)
