### ISSUE TITLE
Мобильный клиент?

### ISSUE THREAD

**Issue by khorevaa** [BlizD/Tasks#96]
Как насчет создания мобильного клиента?

**Comment by BlizD** [comment]
@khorevaa 
Веб клиент пробовал, в целом вроде работал. 
Мобильный клиент при запуске выдавал ошибку, времени на разбор не было.

**Comment by capitoshko** [comment]
Думаю, ч томы побзаем мобыльный клиент уже на платформе 8.3.13

**Comment by capitoshko** [comment]
Надо поднять режим совместимости для мобильного клиента

**Comment by capitoshko** [comment]
При поднятии уровня совместимости и попытке опубликовать мобильный клиент, вохзникают ошибки

{ОбщийМодуль.ДлительныеОперацииГлобальный.Модуль(140,2)}: Процедура или функция с указанным именем не определена (ПоказатьОповещениеПользователя)
	<<?>>ПоказатьОповещениеПользователя(?(Оповещение.Текст <> Неопределено, Оповещение.Текст, НСтр("ru = 'Действие выполнено'")),  (Проверка: Мобильное приложение-клиент)
{ОбщийМодуль.ОбменДаннымиГлобальный.Модуль(32,3)}: Процедура или функция с указанным именем не определена (ПоказатьОповещениеПользователя)
		<<?>>ПоказатьОповещениеПользователя(НСтр("ru = 'Установить обновление'"), "e1cib/app/Обработка.ВыполнениеОбменаДанными", (Проверка: Мобильное приложение-клиент)
{ОбщийМодуль.СоединенияИБГлобальный.Модуль(85,3)}: Процедура или функция с указанным именем не определена (ПоказатьОповещениеПользователя)
		<<?>>ПоказатьОповещениеПользователя(НСтр("ru = 'Завершение работы пользователей'"),  (Проверка: Мобильное приложение-клиент)
{ОбщийМодуль.СоединенияИБГлобальный.Модуль(116,3)}: Процедура или функция с указанным именем не определена (ПоказатьОповещениеПользователя)
		<<?>>ПоказатьОповещениеПользователя(НСтр("ru = 'Завершение работы пользователей'"),  (Проверка: Мобильное приложение-клиент)
{ОбщийМодуль.СоединенияИБГлобальный.Модуль(135,4)}: Процедура или функция с указанным именем не определена (ПоказатьОповещениеПользователя)
			<<?>>ПоказатьОповещениеПользователя(НСтр("ru = 'Завершение работы пользователей'"),  (Проверка: Мобильное приложение-клиент)
{ОбщийМодуль.СоединенияИБГлобальный.Модуль(145,2)}: Процедура или функция с указанным именем не определена (ПоказатьОповещениеПользователя)
	<<?>>ПоказатьОповещениеПользователя(НСтр("ru = 'Завершение работы пользователей'"), (Проверка: Мобильное приложение-клиент)
Мобильное приложение содержит синтаксические ошибки.


Нужно поднимать версию БСП

**Comment by capitoshko** [comment]
І сразу надр на редакцію 3.0 :)

**Comment by BlizD** [comment]
Понятно, спасибо

**Comment by capitoshko** [comment]
Я предлагаю перенест и хзадачу в очень неактуальную, пока конфигурация не будет переведена на версию БСП, которая поддерживает мобильный клиент

**Comment by milanse** [comment]
Мобильный клиент работает, можно закрывать

**Comment by BlizD** [comment]
> Мобильный клиент работает, можно закрывать

Класс.
А пример настройки можете прислать?
И скрин как выглядит форма задачи в мобильном клиенте.

Добавлю в Wiki.
