### ISSUE TITLE
Ошибка при загрузке конфигурации с хранилища

### ISSUE THREAD

**Issue by capitoshko** [BlizD/Tasks#97]
При загрузке конфигурации с хранилища, при неуказанном пользователе, которому нужно отправлять системніе уведомления, и при наличии ошибок, загрузка остоновливаеться с ошибкой:

{Обработка.узЗагрузкаИзмененийИзХранилища.МодульОбъекта(572)}: Итератор для значения не определен
	Для каждого ЭлМассиваПользователейКомуОтправлятьСистемныеУведомления из мМассивПользователейКомуОтправлятьСистемныеУведомления цикл

**Comment by capitoshko** [comment]
Думаю,что нужно написать об этом пользователю, чтобы не капаться в коде

**Comment by BlizD** [comment]
Согласен, если поправишь у себя пришли cf

**Comment by capitoshko** [comment]
Ок. Мы попробуем юзать систему, нам делать доработки как в инструкции? Или можно просто сф-ку прислать?

**Comment by BlizD** [comment]
Можно просто cf прислать.

**Comment by BlizD** [comment]
@capitoshko единственное если будете менять метаданные, то надо предварительно их обсудить.

**Comment by capitoshko** [comment]
Структуру нет, просто добавлю сообщение

**Comment by capitoshko** [comment]
исправил
