### ISSUE TITLE
Ошибка при просмотре истории хранилища

### ISSUE THREAD

**Issue by capitoshko** [BlizD/Tasks#98]
Если хранилище размещено на отдельном сервере и имя указано по шаблону

tcp://<имя сервера>/<каталог хранилища>

то при попытке просмотреть хранилище возникает ошибка

{Обработка.узПросмотрИсторииХранилища.МодульОбъекта(543)}: Ошибка! Не удалось найти файл [tcp://vwa4.mg.ua/inagro2016_from_29092017\1cv8ddb.1CD]
		ВызватьИсключение ТекстОшибки;

**Comment by BlizD** [comment]
А при загрузке проблем нет?

**Comment by BlizD** [comment]
загрузка изменений работает?

**Comment by BlizD** [comment]
Еще посмотрите вот это https://github.com/BlizD/Tasks/wiki/%D0%9A%D0%B0%D0%BA-%D0%BD%D0%B0%D1%81%D1%82%D1%80%D0%BE%D0%B8%D1%82%D1%8C-%D0%B7%D0%B0%D0%B3%D1%80%D1%83%D0%B7%D0%BA%D1%83-%D0%B8%D0%B7%D0%BC%D0%B5%D0%BD%D0%B5%D0%BD%D0%B8%D0%B9-%D0%B8%D0%B7-%D1%85%D1%80%D0%B0%D0%BD%D0%B8%D0%BB%D0%B8%D1%89%D0%B0,-%D0%B5%D1%81%D0%BB%D0%B8-%D1%85%D1%80%D0%B0%D0%BD%D0%B8%D0%BB%D0%B8%D1%89%D0%B5-%D1%81%D0%B5%D1%80%D0%B2%D0%B5%D1%80%D0%BD%D0%BE%D0%B5

**Comment by capitoshko** [comment]
Посмотрю. Но нада бы пользователя уведомить о таком нюансе.

**Comment by capitoshko** [comment]
Загрузка работает, только для просмотра есть проблема.

**Comment by BlizD** [comment]
Если знаешь как подправить и есть желание, то подправь.

**Comment by capitoshko** [comment]
Может зсделать в обработке оповещение, що нужно указать папку хранения конфигурации, а не адрес tcp ?

**Comment by BlizD** [comment]
В подсказке, ты имеешь ввиду?
Да, можно сделать.

**Comment by capitoshko** [comment]
Да, в подсказке

**Comment by capitoshko** [comment]
исправил
